// Independently written operational drafts. The source PDFs are a topic map,
// never a source of copied body text, employee answers or completed forms.
export function extendedCatalog({make,IK,SAK,AML,UTF,PV,source}) {
 const law=(title,url)=>({...source(title,url),checked_on:'2026-10-06'});
 const guide=(title,url)=>({...source(title,url,'professional'),checked_on:'2026-10-06'});
 const BH=law('Byggherreforskriften','https://www.arbeidstilsynet.no/regelverk/forskrifter/byggherreforskriften/');
 const TEK=law('TEK17','https://www.dibk.no/regelverk/byggteknisk-forskrift-tek17/');
 const GDPR=law('Personopplysningsloven og personvernforordningen','https://lovdata.no/lov/2018-06-15-38');
 const r=(key,title,chapter,coverage,goal,responsibility,steps,documentation,references,match='',trades=[])=>({
  ...make(key,title,chapter,goal,responsibility,steps.map((s,i)=>`${i+1}. ${s}`).join('\n\n'),documentation,references.map(s=>({...s,checked_on:'2026-10-06'})),coverage,'Ved '+title.toLocaleLowerCase('nb-NO'),trades),
  recommendation:match,source_revision:1,
 });
 return [
 r('infection','Smittevern og trygg gjenopptakelse av arbeid',2,['K008','K009','K010','K011','K012'],
  'Redusere smitte ved kontakt med mennesker, biologisk materiale og urene arbeidsområder.',
  'Arbeidsleder vurderer eksponeringen sammen med ansatte og bruker helsefaglig bistand når oppgaven krever det.',
  ['Kartlegg nærkontakt, ventilasjon, avløp, forurensede flater og medarbeidere som trenger tilrettelegging. Vurder oppgaven og arbeidsstedet, også etter et driftsavbrudd.', 'Avtal rengjøring, håndhygiene, avfallshåndtering og arbeidsmåter som begrenser eksponering. Skaff nødvendig verneutstyr og opplæring før oppstart.', 'Ved sykdom eller mulig smitte avklares arbeid og tilrettelegging med leder uten å spre diagnoser. Følg aktuelle myndighetsråd og individuelle pålegg; eldre koronaregler i en håndbok brukes ikke som gjeldende karantene- eller isolasjonskrav.', 'Kontroller at tiltak og renhold er klare før arbeidet gjenopptas. Oppdater vurderingen ved nye råd, hendelser eller endret eksponering.'],
  'Datert eksponeringsvurdering, lokale tiltak, oppstartskontroll og nødvendig opplæring. Individuelle helseopplysninger oppbevares særskilt.',[UTF,guide('FHI – smittevernveiledning','https://www.fhi.no/sm/smittevernhandboka/')],'smitte|biolog|avløp|renhold'),
 r('ethics','Etikk, habilitet og gaver',0,['K017','K052'],
  'Sikre redelige beslutninger og unngå at gaver eller private interesser påvirker oppdrag.',
  'Ledelsen fastsetter firmaets gave- og habilitetsregler. Alle ansatte melder interessekonflikter før en beslutning.',
  ['Vurder om en relasjon, gave, rabatt eller invitasjon kan påvirke valg av leverandør eller kundebehandling. Opplys leder om egne eller nærståendes interesser.', 'Avstå fra ytelser som kan kjøpe en fordel. Be leder vurdere tvilstilfeller før mottak; en liten verdi gjør ikke automatisk en gave akseptabel.', 'La en annen kvalifisert person behandle saken ved inhabilitet. Registrer beslutningen og eventuell tilbakelevering.', 'Meld press, bestikkelsesforsøk eller brudd gjennom firmaets fortrolige varslingskanal. Ledelsen følger opp uten gjengjeldelse.'],
  'Firmaets vedtatte gaveregler og en avgrenset oversikt over vurderte tilbud/interessekonflikter.',[law('Straffeloven §§387–389','https://lovdata.no/lov/2005-05-20-28'),AML],'gave|etikk|habil|innkjøp'),
 r('confined','Arbeid i kum og lukkede rom',2,['K018'],
  'Hindre forgiftning, oksygenmangel og ulykker ved entring.',
  'Arbeidsleder godkjenner en konkret plan. Personer som entrer, overvåker og kan utføre redning må ha nødvendig kompetanse.',
  ['Undersøk tilgang, atmosfære, tilførsel av vann/gass, elektrisitet og andre energikilder. Avklar om arbeidet kan utføres uten entring.', 'Sperr og isoler relevante tilførsler. Vurder og mål atmosfæren med egnet kontrollert utstyr, og sørg for nødvendig ventilasjon og løpende overvåking.', 'Avtal kommunikasjon, vakthold og en gjennomførbar redningsplan med utstyr før entring. Ingen går inn alene eller forsøker ubeskyttet redning.', 'Stans og evakuer ved alarm, tap av kommunikasjon eller endrede forhold. Godkjenn ny oppstart først etter ny vurdering.'],
  'Entringsplan/SJA, måleresultater, isoleringskontroll, deltakerkompetanse og beredskapsøvelse.',[UTF,IK],'kum|lukket rom|tank|entring'),
 r('height','Arbeid i høyden, stillas og personlift',2,['K019'],
  'Forebygge fall og sikre hjelp dersom en person blir hengende i fallsikring.',
  'Arbeidsleder velger forsvarlig metode og kontrollerer kompetanse og utstyr. Bruker utfører kontroll før bruk.',
  ['Vurder om jobben kan løses fra bakken. Velg arbeidsplattform og kollektive sikringstiltak ut fra underlag, høyde, varighet, vær og adkomst.', 'Kontroller stillasets godkjenning/overlevering, lastgrenser og trygg adkomst. Lift brukes bare av personer med dokumentert nødvendig opplæring, på egnet underlag og etter bruksanvisningen.', 'Sikre verktøy og sperr området under arbeidet. Hvis personlig fallsikring er nødvendig, avklar forankring, klaring, egnet utstyr og redning før oppstart.', 'Stans ved mangler, endret vind eller ustabilitet. Endring av stillas eller sikring skal vurderes og utføres av kvalifisert person.'],
  'Risikovurdering, opplæring, stillas-/liftkontroll og redningsplan ved personlig fallsikring.',[UTF,guide('Arbeidstilsynet – arbeid i høyden','https://www.arbeidstilsynet.no/risikofylt-arbeid/arbeid-i-hoyden/')],'høyde|stillas|lift|tak|fasade'),
 r('hot-work','Varme arbeider og brannberedskap',2,['K021','U09'],
  'Hindre antennelse og brannspredning ved gnister, flamme og varme.',
  'Arbeidsleder avklarer tillatelse og sikkerhetstiltak. Utførende og brannvakt har nødvendig opplæring og eventuelle avtalekrav til sertifikat.',
  ['Vurder om kald metode eller et egnet fast arbeidssted kan brukes. Avklar brennbart materiale, skjulte hulrom, gass og støv, samt gjeldende forsikrings-/kontraktsvilkår.', 'Fjern eller beskytt brennbart materiale og tett åpninger som kan spre gnister. Avklar eventuell midlertidig frakobling av alarm med ansvarlig; gjeninnkobling må ha en eier.', 'Kontroller slokkeutstyr og avtal brannvakt, alarm og nødadkomst før start. Gjennomfør arbeidet innenfor den godkjente planen.', 'Kontroller området og skjulte risikosteder under og etter arbeidet. Varighet på etterkontroll følger risikovurdering og aktuelle sikkerhetsforskrifter, og dokumenteres.'],
  'Arbeidstillatelse/SJA, kompetanse, tiltak og signert etterkontroll. Sertifikat erstatter ikke vurdering av arbeidsstedet.',[UTF,IK,guide('DSB – brannsikkerhet','https://www.dsb.no/brannsikkerhet/')],'varme arbeid|sveising|flamme|gnist'),
 r('grinder','Bruk av vinkelsliper og kutteutstyr',2,['K023'],
  'Unngå skivesprengning, tilbakeslag, kuttskader og brann.',
  'Arbeidsleder sørger for egnet verktøy og opplæring. Bruker kontrollerer verktøy og arbeidsområde.',
  ['Velg riktig skive for materialet, maskinen og turtallet. Kontroller skive, vern, håndtak og strømtilførsel; skadet utstyr tas ut av bruk.', 'Fest emnet og plasser kroppen utenfor sannsynlig retning for tilbakeslag og sprut. Avklar støvavsug, støyvern, øye-/ansiktsvern og avsperring.', 'Bruk verktøyet etter produsentens anvisning. Kappeskive brukes ikke til sideveis sliping. Unngå løse klær og sikre kontrollert grep.', 'Stopp maskinen og koble fra energi før skifte/justering. Vurder brannrisiko og kontroller gnistområdet etter arbeidet.'],
  'Utstyrskontroll, opplæring og SJA der oppgaven/området krever det. Feil og skader registreres.',[UTF],'vinkel|kutt|sliping|metall'),
 r('dust','Støv, kvarts og forurenset arbeidsatmosfære',2,['K024','K061'],
  'Redusere innånding og hindre at støv spres til andre arbeidere og brukere.',
  'Arbeidsleder kartlegger materialer og eksponering. Fagkyndig bistand brukes ved behov for måling og vernevalg.',
  ['Identifiser støvtypen før boring, kutting og riving. Ukjent materiale vurderes for blant annet asbest før inngrep.', 'Velg metode med minst mulig støv, egnet avsug ved kilden og nødvendig avskjerming. Planlegg transport av avfall og rengjøring uten tørrfeiing eller trykkluft som virvler opp støv.', 'Vurder eksponering mot gjeldende grenseverdier og behov for måling. Åndedrettsvern velges etter eksponeringen, tilpasses brukeren og brukes med nødvendig opplæring.', 'Kontroller at avsug og skille virker under arbeidet. Stans ved ukontrollert støvspredning og vurder tiltak på nytt.'],
  'Materialkartlegging, eksponeringsvurdering/målinger, metodevalg, avsugskontroll og opplæring.',[UTF,law('Forskrift om tiltaks- og grenseverdier','https://www.arbeidstilsynet.no/regelverk/forskrifter/forskrift-om-tiltaks--og-grenseverdier/')],'støv|kvarts|betong|riving|sliping'),
 r('execution','Ansvarlig utførende og egenkontroll',3,['K025','K029','K065','K066','U05'],
  'Utføre avtalt ansvarsområde etter gjeldende grunnlag og dokumentere kontrollen.',
  'Faglig leder vurderer kompetanse og ansvarsområde før foretaket erklærer ansvar. Prosjektleder følger opp produksjonen.',
  ['Avklar tiltaksklasse, ansvarsområde, kompetanse og grensesnitt før erklæring om ansvarsrett. Gjør tillatelser, tegninger og siste produksjonsgrunnlag kjent for utførende.', 'Lag kontrollpunkter for kritiske forhold og arbeid som blir skjult. Avklar produktdokumentasjon, toleranser og hvem som kontrollerer.', 'Registrer utførte kontroller med sted, resultat, dato og identitet. Stans og avklar manglende eller motstridende grunnlag; registrer avvik og endringer.', 'Kontroller at ansvarsområdet og avvikene er ferdig fulgt opp før samsvarserklæring gis til ansvarlig søker. Lever nødvendig FDV og kontrollgrunnlag.'],
  'Avklart ansvarsområde, kompetanse, gjeldende grunnlag, sjekklister/foto, avvik, samsvarserklæring og FDV.',[SAK,law('SAK10 kapittel 12 – ansvar','https://www.dibk.no/regelverk/sak/3/12/')],'utførende|ansvarsrett|egenkontroll|tiltaksklasse'),
 r('design','Ansvarlig prosjekterende og kontroll av løsninger',3,['K026','K031','U05'],
  'Gi utførende et entydig, kontrollert og oppdatert produksjonsgrunnlag.',
  'Faglig leder godkjenner oppdragets kompetanse og ansvar. Prosjekteringsleder følger grensesnitt og endringer.',
  ['Avklar funksjon, ansvarsområde, tiltaksklasse og krav fra tillatelsen. Kartlegg grunnlag og grensesnitt mot andre fag.', 'Dokumenter valgte ytelser, beregninger og løsninger opp mot relevante krav. Avklar særskilte kontrollkrav og nødvendige faglige kontroller.', 'Kontroller og merk tegnings-/dokumentversjoner før utgivelse. Mottaker skal kunne se hvilken utgave som gjelder og hvilke forutsetninger løsningen bygger på.', 'Behandle endringer og avvik før revidert grunnlag utgis. Lever samsvarserklæring og nødvendig dokumentasjon for eget område når prosjekteringen er avsluttet.'],
  'Kravgrunnlag, fagkontroller, beregninger, tegninger, versjonslogg, grensesnitt og samsvarserklæring.',[SAK,TEK],'prosjekter|beregning|tegne|ansvarsrett'),
 r('applicant','Ansvarlig søker og oppstart av søknadspliktige tiltak',3,['K027','K033','K057','U05'],
  'Avklare søknadsplikt og sørge for at et tiltak ikke starter med manglende tillatelser eller ansvar.',
  'Ansvarlig søker koordinerer byggesaken. Tiltakshaver og ansvarlige foretak utfører sine egne plikter.',
  ['Avklar søknadsplikt og eventuell dispensasjon før planlagt oppstart. Avgrens søkeroppdraget og innhent nødvendig grunnlag og nabovarsling.', 'Kontroller at alle ansvarsområder og eventuelle krav om uavhengig kontroll er dekket. Hold gjennomføringsplanen oppdatert.', 'Formidle tillatelsens vilkår og avklar igangsetting før arbeid starter. Følg opp endringer i foretak, ansvar og myndighetskrav.', 'Samle samsvars-/kontrollerklæringer og nødvendig sluttgrunnlag. Følg opp midlertidig brukstillatelse/ferdigattest og utestående vilkår.'],
  'Søknad, tillatelser, gjennomføringsplan, varsling, erklæringer, endringer og avslutningsgrunnlag.',[SAK,law('Plan- og bygningsloven','https://lovdata.no/lov/2008-06-27-71')],'søker|søknadsplikt|byggesak|ansvarsrett'),
 r('ppe','Velge, bruke og kontrollere verneutstyr',2,['K028'],
  'Sørge for at personlig verneutstyr passer risikoen og brukeren.',
  'Arbeidsleder vurderer tiltak og sørger for egnet utstyr, opplæring og utskifting. Medarbeider bruker og kontrollerer utstyret.',
  ['Reduser faren gjennom metode og kollektive tiltak først. Vurder deretter behov for blant annet hode-, øye-, hørsel-, hånd-, fot- og åndedrettsvern.', 'Velg utstyr etter risiko, størrelse og samvirke med annet verneutstyr. Kontroller merking og produsentanvisning, og avklar tilpasning og opplæring.', 'Kontroller utstyret før bruk. Skadet, forurenset eller utgått utstyr tas ut av bruk og erstattes; privat reparasjon av sikkerhetskritisk utstyr tillates ikke.', 'Rengjør, oppbevar og gjennomfør periodisk kontroll slik at beskyttelsen bevares. Meld ubehag eller manglende beskyttelse til leder.'],
  'Verneutstyrsvurdering, utlevering/opplæring og kontroll av utstyr som krever sporbar kontroll.',[UTF],'verneutstyr|støy|støv|høyde'),
 r('signage','Skilting, merking og prosjektopplysninger',0,['K032','K049'],
  'Gjøre farer, adkomst og viktige kontaktopplysninger forståelige på arbeidsstedet.',
  'Arbeidsleder holder skilt og lokal informasjon oppdatert. Prosjektleder avklarer krav og grensesnitt med byggeplassen.',
  ['Kartlegg nødvendig avsperring, sikkerhetsskilt, rømningsmerking og lokale prosjektopplysninger før oppstart.', 'Plasser lesbar informasjon der den trengs. Avklar språk og forståelse, og beskytt personopplysninger som ikke skal være offentlig tilgjengelige.', 'Gå gjennom kontaktpersoner, nødadkomst, møtepunkt og hvem som har adgang med medarbeiderne.', 'Kontroller merking ved vernerunde og endring av rigg eller risiko. Fjern skilt som gir feil beskjed etter at forholdet er avsluttet.'],
  'Lokal oversikt, kontroller og oppdaterte skilt/kontaktpunkter.',[UTF,BH],'skilt|rigg|byggeplass'),
 r('core-drilling','Planlegge og utføre kjerneboring',2,['K034'],
  'Unngå skade på skjulte installasjoner, konstruksjon og personer under borestedet.',
  'Arbeidsleder avklarer boring med prosjekterende/byggeledelse. Operatør har nødvendig utstyrsopplæring.',
  ['Kontroller borested og nødvendig godkjenning mot tegninger og faktisk forhold. Lokaliser elektriske ledninger, rør og eventuell armering som ikke kan skades.', 'Avklar bæreevne, maskinforankring, fall av borekjerne og avsperring på begge sider. Bruk egnet elektrisk beskyttelse ved vannkjøling.', 'Planlegg støv-/slamoppsamling, støy og transport av kjernen. Utfør etter maskinens anvisning og godkjent løsning.', 'Stans ved ukjent motstand eller installasjon. Kontroller åpningen og dokumenter eventuell tetting, endring eller avvik.'],
  'Godkjent boreplan, kontroll av skjulte installasjoner, SJA og dokumentasjon av ferdig åpning/tetting.',[UTF,SAK],'kjernebor|boring|betong'),
 r('documents','Styresystem, dokumentversjoner og regelverksendringer',0,['K036','K037'],
  'Gjøre riktig grunnlag tilgjengelig og hindre bruk av utgåtte dokumenter.',
  'KS/HMS-ansvarlig vedlikeholder regelverks- og dokumentoversikten. Dokumenteier vurderer endringene før godkjenning.',
  ['Identifiser lover, forskrifter, kontraktskrav og faggrunnlag som gjelder aktiviteten. Oppgi kilde, dato, dokumenteier og hvem som skal varsle om endringer.', 'Gi dokumenter entydig navn, versjon og godkjenning. Arbeidsstedet skal kunne finne gjeldende utgave; merk eldre utgaver som historikk.', 'Vurder konsekvensene av en kildeendring for arbeid, opplæring og eksisterende rutiner. Endre rutinen som utkast og få ny utgave godkjent før bruk.', 'Bevar nødvendig historikk med avgrenset tilgang. Kontroller tilgang, gjenfinning og gjenoppretting; personopplysninger har egne bevaringsvurderinger.'],
  'Dokument-/kildeoversikt, revisjoner, godkjenninger, vurderte regelendringer og lagrings-/tilgangsregler.',[IK,SAK,GDPR],'dokument|regelverk|revisjon'),
 r('water-edge','Arbeid ved sjø og vann',2,['K039'],
  'Forebygge fall i vann og sikre gjennomførbar redning.',
  'Arbeidsleder vurderer lokale vann-, vær- og redningsforhold. Alle på arbeidsstedet kjenner alarm og redningsutstyr.',
  ['Vurder kant, underlag, strøm, tidevann, kulde, vær, båter og mulighet for adkomst fra land. Unngå arbeid tett på usikret kant når det kan løses tryggere.', 'Avklar barrierer, belysning, flyteutstyr og eventuell sikring ut fra oppgaven. Sperr for uvedkommende og sikre løse materialer.', 'Plasser egnet redningsutstyr og avtal kommunikasjon og redning uten at hjelper må utsette seg for samme fare. Øv nødvendige oppgaver.', 'Stans ved endrede vær-/vannforhold eller manglende redningsberedskap. Kontroller sikring ved hvert skift.'],
  'Lokal risikovurdering, redningsplan, utstyrskontroll og øvelse.',[UTF,IK],'sjø|vannkant|brygge|kai'),
 r('road','Arbeid ved trafikkert vei',2,['K040'],
  'Skille arbeidere og trafikanter og opprettholde trygg ferdsel.',
  'Prosjektleder avklarer tillatelser og arbeidsvarsling med veieier. Utpekt ansvarlig følger opp sikring og kompetanse.',
  ['Avklar behov for arbeidstillatelse, godkjent arbeidsvarslingsplan og kvalifikasjoner før inngrep ved vei.', 'Planlegg fysisk sikring, adkomst for gående/syklende, maskinbevegelse og synlighet. Gjennomgå løsningen med arbeidslaget.', 'Sett ut og kontroller skilt og sikring i riktig rekkefølge. Trafikkdirigering utføres bare innenfor godkjent ordning og med nødvendig kompetanse.', 'Før tilsyn under arbeidet og ved endret trafikk, sikt eller arbeidsområde. Rett mangler straks og dokumenter avslutning/fjerning.'],
  'Godkjent plan/tillatelse, kompetanse, kontroll-/tilsynslogg og avvik.',[UTF,guide('Statens vegvesen – arbeidsvarsling','https://www.vegvesen.no/fag/veg-og-gate/arbeidsvarsling/')],'vei|trafikk|arbeidsvarsling'),
 r('hms-plan','HMS-plan og medvirkning',2,['K041','U08'],
  'Omsette virksomhetens risiko til tiltak som faktisk blir gjennomført.',
  'Arbeidsgiver eier HMS-arbeidet. KS/HMS-ansvarlig koordinerer planen sammen med ansatte og verneombud.',
  ['Kartlegg arbeid, lokaler, organisering og eksponeringer med dem som utfører oppgavene. Vurder både skadehendelser og belastning over tid.', 'Beskriv vesentlige risikoer og velg tiltak med ansvar, frist og hvordan effekt skal kontrolleres. Koble prosjektets særlige risiko til lokal plan og relevant SHA-plan.', 'Gjør tiltak og rutiner kjent og sørg for nødvendig opplæring og ressurser. Medarbeidere melder mangler og deltar i oppfølgingen.', 'Følg opp frister og effekt jevnlig. Vurder planen ved hendelser, endring av arbeid og ledelsens gjennomgang.'],
  'Risikovurderinger, handlingsplan, medvirkning, opplæring og datert oppfølging av tiltak.',[IK,AML,BH],'hms-plan|internkontroll|sha'),
 r('inspection','Gjennomføre vernerunder',2,['K042'],
  'Oppdage mangler og følge dem til dokumentert retting.',
  'Arbeidsleder planlegger runden med verneombud og aktuelle medarbeidere. Tiltakseier følger opp funn.',
  ['Avtal deltakere, område og frekvens ut fra risiko, hendelser og arbeidsstedets krav.', 'Kontroller blant annet adkomst, orden, fall-/brannfare, maskiner, verneutstyr og arbeidsmiljøbelastninger. Snakk med medarbeiderne om forhold som ikke er synlige.', 'Sikre akutte farer straks. Registrer øvrige funn med sted, tiltak, ansvarlig og frist i egnet avviks-/handlingsregister.', 'Kontroller at tiltak virker før funnet avsluttes. Ta gjentakende mangler inn i risikovurderingen og ledelsens oppfølging.'],
  'Datert runderapport med deltakere, funn, ansvar, frister og kontrollert retting.',[IK,AML],'vernerund|byggeplass|hms'),
 r('crew','Mannskapsoversikt og HMS-kort',2,['K044','K072'],
  'Ha riktig oversikt over hvem som arbeider på byggeplassen og kontrollere relevante kortkrav.',
  'Prosjektleder avklarer føring med byggherre/hovedbedrift. Arbeidsgiver følger opp HMS-kort for egne medarbeidere.',
  ['Avklar hvem som holder elektronisk oversiktsliste og hvilke opplysninger som kreves etter byggherreforskriften. Bidra med korrekte opplysninger og avtal oppdatering.', 'Kontroller gyldige HMS-kort og nødvendige arbeidsgiver-/identitetsforhold for arbeid som omfattes. Kortet er ikke bevis på fagkompetanse eller opplæring.', 'Meld oppstart, endring og avslutning til listeansvarlig. Håndter besøk og leveranser etter lokale adgangsregler.', 'Begrens tilgangen til oversikten og oppbevar den etter det relevante lovkravet. Rett feil og meld manglende kort til leder.'],
  'Avklart listeansvar, oppdateringsrutine og nødvendige kortkontroller uten unødvendige kopier av identitetsdokumenter.',[BH,law('Forskrift om HMS-kort på bygge- og anleggsplasser','https://www.arbeidstilsynet.no/regelverk/forskrifter/forskrift-om-hms-kort-pa-bygge--og-anleggsplasser/')],'mannskap|hms-kort|byggeplass'),
 r('rig','Rigg, adkomst og felles sikkerhet',2,['K046','K043','K048'],
  'Organisere arbeidsstedet slik at aktiviteter, transport og beredskap kan fungere trygt sammen.',
  'Prosjektleder avklarer riggen med hovedbedrift og byggherre. Arbeidsleder følger lokale endringer.',
  ['Avklar adkomst, laste-/losseområder, rømningsveier, nødadkomst og skille mellom personer og maskiner. Ta hensyn til naboer og publikum.', 'Planlegg lager, avfall, kjemikalier, strøm, belysning og velferdsrom. Gjennomgå prosjektets SHA-tiltak og samordningsregler med arbeidslaget.', 'Marker områder og kontaktpunkter. Kontroller at flytting av lager eller maskiner ikke blokkerer sikring eller andre fag.', 'Oppdater planen ved nye aktiviteter, faseendringer eller hendelser. Mangler med ansvar og frist følges til retting.'],
  'Riggplan, avklarte grensesnitt, lokale gjennomganger og dokumenterte endringer.',[BH,IK],'rigg|byggeplass|samordn'),
 r('electrical','Tilsyn med elektrisk anlegg og utstyr',2,['K047','U09'],
  'Hindre strømulykker og brann uten at ukvalifiserte personer utfører elektrisk arbeid.',
  'Arbeidsleder sørger for tilsyn. Reparasjon og inngrep som krever elektrofaglig kompetanse overlates til kvalifisert/registrert virksomhet.',
  ['Kontroller kabler, plugger, skap og elektrisk håndverktøy visuelt før bruk. Avklar beskyttelse for fukt, mekanisk skade og aktuell belastning.', 'Merk og koble fra skadet eller mistenkelig utstyr. Sikre mot gjenbruk og meld feilen; ikke utfør improviserte reparasjoner.', 'Hold tavler tilgjengelige og kabler beskyttet. Avklar sikker frakobling før arbeid nær installasjoner, og bruk fagkyndig person ved tvil.', 'Planlegg nødvendig periodisk kontroll og før oversikt over feil/retting. Ved strømulykke sikres energikilden og nødetatene varsles.'],
  'Tilsynsplan, feilmerking, dokumentert fagmessig retting og eventuelle kontrollrapporter.',[UTF,guide('DSB – elsikkerhet','https://www.dsb.no/elsikkerhet/')],'elektr|strøm|kabel|maskin'),
 r('welfare','Orden, hygiene, røyk og pauser',1,['K051'],
  'Ha rene og forsvarlige fellesarealer og tydelige lokale ordensregler.',
  'Arbeidsgiver avklarer velferdstilbud og ordensregler med medarbeiderne. Alle rydder etter eget arbeid.',
  ['Avklar toalett, vask, skift, spiserom og nødvendige pausemuligheter før oppstart på et nytt sted.', 'Hold mat og drikke utenfor områder med kjemikalier eller biologisk forurensning. Avtal renhold og håndtering av søl/avfall.', 'Røyking følger lovkrav og lokale brann-/arbeidsplassregler. Firmaets regler om kaffe, mineralvann og private innkjøp gjøres tydelige uten å fremstilles som lovkrav.', 'Meld mangler ved lokaler, hygiene eller pauser til leder/verneombud. Følg opp arbeidsmiljøproblemer uten å legge private opplysninger i felles håndbok.'],
  'Lokale velferds-/ordensregler og oppfølging av mangler.',[AML,law('Arbeidsplassforskriften','https://www.arbeidstilsynet.no/regelverk/forskrifter/arbeidsplassforskriften/')],'pause|velferd|rigg'),
 r('board','Styrets ansvar og ledelsens rapportering',1,['K053'],
  'Avklare beslutningsmyndighet og sikre at styret får nødvendig oversikt.',
  'Styret ivaretar sitt ansvar etter selskapsformen. Daglig leder følger opp vedtak og rapporterer vesentlige risikoer.',
  ['Beskriv styrets, daglig leders og delegerte roller. Avklar hvilke saker som krever styrebehandling og hvem som kan forplikte firmaet.', 'Planlegg rapportering om drift, økonomi, kvalitet, arbeidsmiljø og vesentlige hendelser. Gi styret tilstrekkelig grunnlag uten unødvendige personalsaksdetaljer.', 'Protokollfør beslutninger og habilitetsvurderinger. Tildel oppfølging med frist og kontroller at vedtak gjennomføres.', 'Oppdater fullmakter ved organisasjonsendringer. Avklar når lovpålagt handling eller ekstern fagbistand er nødvendig.'],
  'Rolle-/fullmaktsoversikt, styreprotokoller og oppfølging av vedtak med avgrenset tilgang.',[law('Aksjeloven kapittel 6 (for aksjeselskap)','https://lovdata.no/lov/1997-06-13-44')],'styre|daglig leder|ledelse'),
 r('procurement','Leverandørpriser og kontraktsforberedelse',0,['K055','K056','U04'],
  'Sammenligne samme leveranse og avklare ansvar før bestilling eller kontrakt.',
  'Innkjøps-/prosjektansvarlig innhenter grunnlag. Person med fullmakt godkjenner avtalen.',
  ['Beskriv leveransen, kvalitet, mengder, dokumentasjon og grensesnitt. Avklar krav til HMS, kompetanse og eventuell ansvarsrett før prisinnhenting.', 'Innhent sammenlignbare tilbud og kontroller forbehold, leveringsbetingelser, kapasitet og referanser. Registrer habilitetsforhold.', 'Avklar betalings-/endringsvilkår, frister, garanti, kontroll, dokumentleveranser og håndtering av forsinkelse eller feil. Vurder kontraktsgrunnlaget og behov for faglig/juridisk bistand.', 'Godkjenn innen fullmakt og lagre avtalt grunnlag. Overfør forutsetninger til dem som skal følge opp leveransen; avvik håndteres skriftlig.'],
  'Prisgrunnlag, leverandørvurdering, sammenligning, avklaringer, fullmakt og godkjent avtale.',[SAK,IK],'innkjøp|leverandør|kontrakt'),
 r('gas','Gassanlegg og sikker overlevering',3,['K058'],
  'Hindre lekkasje, eksplosjon og bruk av et anlegg uten kontrollert grunnlag.',
  'Faglig ansvarlig avklarer kompetanse, regelverk og kontrollkrav. Bare kvalifisert person utfører arbeid innen sitt område.',
  ['Avklar gasstype, bruk, tegninger, produktkrav og ansvar for prosjektering/installasjon. Undersøk nødvendige meldinger, tillatelser og uavhengige kontroller for anlegget.', 'Vurder lekkasje, ventilasjon, tennkilder og sikker isolering før arbeid. Avtal beredskap og sperring av området.', 'Monter etter godkjent løsning og produsentanvisninger. Prøving og lekkasjekontroll følger anleggets krav og utføres av kvalifisert person.', 'Overlever bare når kontroller og mangler er fulgt opp. Gi bruker nødvendig sikkerhetsinformasjon, drifts-/vedlikeholdsdokumentasjon og kontakt ved feil.'],
  'Kompetanse, prosjekteringsgrunnlag, prøver/kontroller, avvik og overlevering/FDV.',[law('Forskrift om håndtering av farlig stoff','https://lovdata.no/forskrift/2009-06-08-602'),TEK],'gass|propan'),
 r('sprinkler','Sprinkleranlegg og endring av brannsikring',3,['K059'],
  'Bevare brannsikkerheten under arbeid og dokumentere anleggets funksjon.',
  'Faglig ansvarlig avklarer løsning og kompetanse. Byggeier/brannansvarlig godkjenner planlagt utkobling og midlertidige tiltak.',
  ['Gjennomgå brannkonsept, prosjektgrunnlag, dimensjonering og relevante standard-/kontraktskrav. Avklar grensesnitt mot alarm, vannforsyning og andre fag.', 'Planlegg eventuell utkobling med eier og avtal alternative tiltak, varsling og tidspunkt for gjeninnkobling.', 'Utfør etter kontrollert grunnlag. Registrer produkter, kritiske montasjedetaljer, prøver og funksjonskontroller; avvik avklares før tildekking/bruk.', 'Bekreft gjeninnkobling og ferdig funksjonskontroll. Overlever ajourførte tegninger, driftsinformasjon og plan for ettersyn.'],
  'Godkjent grunnlag, utkoblingsavtale, prøver, avvik, funksjonskontroll og FDV.',[SAK,TEK,law('Forskrift om brannforebygging','https://lovdata.no/forskrift/2015-12-17-1710')],'sprinkler|slokkeanlegg'),
 r('machines','Maskiner, kjøretøy og vedlikehold',2,['K060'],
  'Sikre at utstyr er egnet, kontrollert og brukes av personer med nødvendig kompetanse.',
  'Utstyrsansvarlig fører kontroll/vedlikehold. Arbeidsleder avklarer bruk, og fører utfører kontroll før start.',
  ['Velg utstyr etter oppgave, underlag, last og omgivelser. Kontroller nødvendig opplæring, førerrett og eventuell sakkyndig kontroll.', 'Kontroller vern, nødstopper, lekkasjer og øvrige kontrollpunkter etter anvisningen før bruk. Feilmerket utstyr sperres.', 'Avklar sikkerhetssoner og kommunikasjon med personer rundt maskinen. Ingen går inn i faresonen uten avtalt sikring.', 'Isoler energi før vedlikehold og bruk kvalifisert person. Registrer vedlikehold, kontroll og retting før utstyret frigis.'],
  'Utstyrsregister, opplæring, vedlikehold, nødvendig sakkyndig kontroll og feil-/rettingslogg.',[UTF],'maskin|truck|kjøretøy|lift'),
 r('warehouse','Lager, mottak og sikker stabling',0,['K062','K069'],
  'Bevare produktkvalitet og hindre ras, fall og blokkert adkomst.',
  'Lageransvarlig organiserer lagringen. Mottaker kontrollerer leveransen og melder skader/mangler.',
  ['Kontroller levering mot bestilling, merking, skade og nødvendig produktdokumentasjon. Sett tvilsomme eller skadde varer til side.', 'Velg lagringssted etter vekt, bæreevne, temperatur/fukt og produktkrav. Skill kjemikalier og varer som ikke kan lagres sammen.', 'Stabl stabilt innen tillatt last/høyde og sikre mot velt. Hold gangveier, rømningsveier, slokkeutstyr og elektriske skap frie.', 'Kontroller lager og reoler jevnlig. Rett feil, registrer svinn/skader og unngå bruk av utgåtte eller uidentifiserte produkter.'],
  'Mottakskontroll, lagerplassering, lastgrenser, tilsyn og avvik.',[UTF,SAK],'lager|stabl|vare|leveranse'),
 r('lifting','Tunge løft og ergonomisk arbeid',2,['K063','U11'],
  'Redusere belastning og unngå klemskader og fallende last.',
  'Arbeidsleder planlegger håndtering med dem som utfører arbeidet. BHT/fagkyndig bistår ved belastningsvurdering.',
  ['Vurder vekt, grep, avstand, repetisjon, arbeidshøyde, plass og underlag. Del leveransen eller endre metoden der dette reduserer belastningen.', 'Bruk egnet løfte-/transporthjelpemiddel og planlegg plassering før levering. Avklar nødvendig kompetanse og kontroll ved mekaniske løft.', 'Avtal roller og signaler ved felles løft. Sperr fareområdet og unngå opphold under hengende last; hender/føtter holdes utenfor klemsoner.', 'Varier arbeid, vurder pauser og følg opp smerter tidlig. Kontroller effekt av tilrettelegging og nye hjelpemidler.'],
  'Belastningsvurdering, metode/hjelpemiddel, løfteplan ved behov, opplæring og oppfølging.',[UTF,AML],'løft|tung|ergonomi|bæring'),
 r('transport','Varetransport og servicebil',2,['K064','K078'],
  'Sikre last og hindre at transport, verktøy eller kjemikalier skader personer.',
  'Fører kontrollerer kjøretøy og last. Utstyrsansvarlig følger opp vedlikehold og firmaets bilregler.',
  ['Kontroller tillatt last, dekk, lys og nødvendig utstyr. Velg plassering som gir stabilitet og ikke hindrer sikt eller trygg adkomst.', 'Sikre last mot forskyvning og fall, også ved åpen transport. Velg sikringsutstyr og eventuell merking etter last og transportkrav.', 'Oppbevar verktøy og kjemikalier forsvarlig. Avklar krav til transport av farlig gods for den aktuelle mengden/varen før kjøring.', 'Planlegg trygg lasting/lossing og parker uten å blokkere beredskap eller gangveier. Meld skade, mangler og uhell.'],
  'Bil-/lastkontroll, vedlikehold og nødvendig transportdokumentasjon. Privatbruk og eventuell sporing har egne regler.',[law('Vegtrafikkloven','https://lovdata.no/lov/1965-06-18-4'),UTF],'transport|servicebil|kjøretøy|leveranse'),
 r('withdrawal','Avslutte eller endre ansvarsrett',3,['K067'],
  'Unngå ansvarshull og dokumentere status når foretaket fratrer.',
  'Faglig leder og prosjektleder avklarer opphør med ansvarlig søker, tiltakshaver og eventuell ny ansvarlig.',
  ['Avklar hvilket ansvarsområde som avsluttes, hvorfor og hvilken del som faktisk er ferdig.', 'Gi nødvendige meldinger etter SAK10 og avklar videre dekning av ansvar før arbeidet fortsetter.', 'Overlever kontrollert grunnlag, utførte kontroller, samsvar for ferdig del og åpne avvik/mangler til relevant mottaker.', 'Bevar dokumentasjon for egen leveranse og avklar utestående kontraktsforhold separat. Endring i ansvarsrett fjerner ikke ansvar for tidligere utført arbeid.'],
  'Opphørsmelding, status, avgrenset samsvarsgrunnlag, åpne avvik og dokumentert overlevering.',[SAK,law('SAK10 kapittel 12','https://www.dibk.no/regelverk/sak/3/12/')],'ansvarsrett|fratre|opphør'),
 r('inquiries','Henvendelser, klager og avklaringer',0,['K068'],
  'Sørge for at spørsmål og klager får en eier og et sporbar svar.',
  'Mottaker registrerer relevant henvendelse. Prosjekt-/kundeansvarlig avklarer hvem som svarer og følger opp.',
  ['Bekreft mottak og avklar hva saken gjelder, aktuelle frister og nødvendig grunnlag.', 'Fordel saken til person med kompetanse og fullmakt. Skill spørsmål, endringsbestilling, reklamasjon og sikkerhetsavvik.', 'Undersøk faktisk leveranse og avtal løsning skriftlig. Del bare nødvendig dokumentasjon med verifisert mottaker.', 'Kontroller gjennomføring og gi avsluttende beskjed. Ta gjentakende feil inn i avviks-/forbedringsarbeidet.'],
  'Henvendelse, ansvar, grunnlag, beslutning/svar og kontrollert oppfølging i eksisterende sakssystem.',[IK,GDPR],'klage|henvend|kunde|reklamasjon'),
 r('excavation','Arbeid i grøft og byggegrop',2,['K070'],
  'Hindre ras, påkjørsel, fall og skade på skjulte ledninger.',
  'Arbeidsleder sørger for vurdering av grunnforhold, sikring og nødvendig kompetanse før graving/entring.',
  ['Innhent ledningspåvisning, tillatelser og grunnlag om grunn/vann. Vurder rasfare og påvirkning på nærliggende konstruksjoner og trafikk.', 'Velg nødvendig prosjektert sikring, avstivning eller skråning ut fra forholdene. Hold masser og maskinbelastning på forsvarlig avstand fra kanten.', 'Sørg for trygg adkomst, avsperring og avklart samspill mellom maskin og personer. Vurder atmosfære/vann og redningsberedskap.', 'Kontroller grøften før entring og etter nedbør, frost/tining, vibrasjon eller andre endringer. Evakuer ved tegn til ustabilitet og få ny vurdering.'],
  'Grunn-/ledningsgrunnlag, sikringsplan, SJA, kontroll og endringsvurderinger.',[UTF,BH],'grøft|grave|byggegrop'),
 r('sewage','Arbeid på avløp og forurensede anlegg',3,['K071'],
  'Sikre teknisk kvalitet og beskytte mot biologisk eksponering og gass.',
  'Arbeidsleder avklarer hygienetiltak og energi-/strømningssikring. Faglig ansvarlig kontrollerer løsningen.',
  ['Kartlegg avløpsinnhold, tilbakeslag, gass og eksponering. Avklar stenging og sikker isolering før inngrep; kumarbeid krever egen entringsplan.', 'Velg metode, verneutstyr og hånd-/utstyrshygiene. Skill rent og urent område, og planlegg avfall og rengjøring.', 'Kontroller rørvalg, fall, skjøter, tetthet og grensesnitt etter prosjektgrunnlaget. Dokumenter kontroll før tildekking.', 'Rengjør og overlever nødvendig driftsinformasjon. Meld avvik, søl og eksponering for videre oppfølging.'],
  'Risiko-/hygieneplan, isoleringskontroll, tekniske kontroller, foto og FDV.',[UTF,TEK],'avløp|kloakk|sluk'),
 r('asbestos','Mistanke om asbest og sanering',2,['K073'],
  'Hindre fiberspredning og sikre at asbestarbeid bare utføres innenfor nødvendige tillatelser.',
  'Arbeidsleder stanser mistenkelig arbeid og innhenter kartlegging. Arbeidsgiver avklarer godkjent virksomhet og kompetanse.',
  ['Vurder eldre materialer før riving eller bearbeiding. Ved ukjent/mistenkelig materiale stanses inngrepet, området sikres og kvalifisert kartlegging/prøvetaking avklares.', 'Arbeid som omfattes av asbestreglene planlegges av virksomhet med nødvendig tillatelse. Avklar melding, arbeidsplan, opplæring, helseoppfølging og beredskap før start.', 'Avtal avskjerming, ren/uren sone, egnet verneutstyr og kontrollert avfallshåndtering. Andre fag skal ikke utsettes for spredning.', 'Frigi området først etter nødvendige rengjørings-/sluttkontroller. Bevar pålagt dokumentasjon og følg opp mulig eksponering fortrolig.'],
  'Kartlegging, tillatelse/melding, arbeidsplan, kompetanse, nødvendige eksponerings-/sluttkontroller og avfallsbevis.',[UTF,guide('Arbeidstilsynet – asbest','https://www.arbeidstilsynet.no/risikofylt-arbeid/asbest/')],'asbest|riving|rehabiliter'),
 r('whistleblowing','Varsle om kritikkverdige forhold',1,['K074','U15'],
  'Gjøre varsling tilgjengelig og håndtere saken fortrolig, forsvarlig og uten gjengjeldelse.',
  'Ledelsen angir mottaker og alternativ kanal hvis ordinær mottaker er involvert. Utpekt habil person undersøker saken.',
  ['Gjør interne kanaler og kontaktpersoner kjent. Varsling kan også skje via verneombud, tillitsvalgt eller advokat og direkte til offentlig myndighet etter lovens regler.', 'Mottaker bekrefter mottak, avklarer behov for beskyttelse og vurderer habilitet. Identitet og sak deles bare med personer som trenger opplysningene.', 'Undersøk innen rimelig tid og gi berørte personer mulighet til å svare, samtidig som varslerens arbeidsmiljø ivaretas. Dokumenter fakta og beslutninger fortrolig.', 'Følg opp tiltak og risiko for gjengjeldelse. En personalsak eller et varsel med sensitive opplysninger legges ikke i det ordinære prosjekt-/KS/HMS-avviksregisteret.'],
  'Vedtatt varslingsrutine og separat tilgangsstyrt sakslogg med mottak, habilitet, undersøkelser og oppfølging.',[AML,PV],'varsling|kritikkverdig|arbeidsmiljø'),
 r('class','Tiltaksklasse og kompetanse før oppdrag',3,['K075','K076','K077'],
  'Ta oppdrag innen faktisk kompetanse, kapasitet og kvalitetssikring.',
  'Faglig leder vurderer hvert ansvarsområde. Ledelsen avklarer ressurser og avstår fra oppdrag firmaet ikke kan utføre forsvarlig.',
  ['Vurder kompleksitet, vanskelighetsgrad og konsekvenser av feil for oppdragets ansvarsområder. Bruk gjeldende SAK10 til å avklare tiltaksklasse.', 'Kontroller relevante kvalifikasjoner og praksis for funksjon og fagområde. Tiltaksklasse 1, 2 og 3 gir ulike kvalifikasjonskrav; firmagodkjenning alene avgjør ikke hva en person kan utføre.', 'Avklar kapasitet, faglig ledelse, egenkontroll og eventuelle krav om uavhengig kontroll. Dokumenter grensesnitt mot andre foretak.', 'Revurder ved endret oppdrag eller bortfall av nøkkelperson. Avklar nytt ansvar før arbeid fortsetter uten nødvendig kompetanse.'],
  'Oppdrags-/klassevurdering, kvalifikasjoner, faglig ledelse, kontrollplan og beslutning om å ta oppdraget.',[SAK,law('SAK10 kapitlene 9 og 11','https://www.dibk.no/regelverk/sak/3/')],'tiltaksklasse|ansvarsrett|kompetanse'),
 r('legionella','Forebygge legionella i vanninstallasjoner',3,['K079'],
  'Avklare risiko og driftstiltak for installasjoner som kan spre aerosoler.',
  'Faglig ansvarlig prosjekterer/utfører innen sitt oppdrag. Anleggseier må ha ansvar for driftsoppfølging og helsefaglige vurderinger.',
  ['Kartlegg bruk, temperaturer, stagnasjon, blindledninger og aerosoldannende utstyr. Avklar relevante forskrifts- og prosjektkrav.', 'Velg løsning og driftsopplegg som begrenser vekst og spredning. Avklar nødvendige kontrollpunkter med kompetent fagperson.', 'Dokumenter installasjon, innregulering og nødvendig gjennomspyling/kontroll før overlevering. Ikke gi generell garanti om smittefrihet basert på én prøve.', 'Gi eier plan for temperatur-/driftskontroll, vedlikehold og handling ved avvik. Prøvetaking og sanering avklares faglig ut fra anlegget.'],
  'Risikovurdering, teknisk grunnlag, kontroller og overlevert drifts-/vedlikeholdsplan.',[TEK,law('Forskrift om miljørettet helsevern kapittel 3a','https://lovdata.no/forskrift/2003-04-25-486')],'legionella|varmtvann|vanninstall'),
 r('working-time','Arbeidstid, pauser og registrering',1,['K080'],
  'Ha riktig oversikt over faktisk arbeidstid og vurdere forsvarlig belastning.',
  'Leder avklarer arbeidstidsordningen og kontrollerer oversikten. Medarbeider registrerer faktisk arbeid etter firmaets rutine.',
  ['Avklar ordinær arbeidstid, pauser, hvile og eventuelle avtaler før arbeid planlegges. Vurder sikkerhet ved lange dager, nattarbeid og samlet belastning.', 'Registrer faktisk start, slutt og pauser i firmaets eksisterende system. Avklar reise, beredskap og andre tvilstilfeller ut fra gjeldende regelverk/avtale.', 'Overtid må ha et særskilt og tidsavgrenset behov og behandles innen lov-/avtalegrenser. Leder følger opp hvile, omfang og godkjenning.', 'Rett registreringsfeil sporbar og avklar lønnsgrunnlag. Gjentakende tidspress behandles i arbeidsmiljøarbeidet; denne rutinen oppretter ikke et nytt timesystem i ProffDok.'],
  'Arbeidstidsordning, faktiske registreringer, relevante avtaler og vurdering av overtid/hvile.',[AML],'arbeidstid|overtid|pause|turnus'),
 r('occupational-health','BHT og fysisk arbeidsmiljø',1,['K083','U11'],
  'Bruke forebyggende fagbistand til å redusere arbeidsrelatert helserisiko.',
  'Arbeidsgiver avklarer BHT-plikt og sørger for godkjent BHT der det kreves. Ansatte og verneombud deltar i planleggingen.',
  ['Vurder risiko og aktuell tilknytningsplikt. Avtal plan for BHT-bistand som dekker faktiske arbeidsforhold.', 'Kartlegg ergonomi, støy, lys, inneklima, kjemisk/biologisk eksponering og andre relevante belastninger. Avklar målinger og tiltak med fagkyndige.', 'Vurder målrettet helseundersøkelse når regelverket/risiko krever det. Helseopplysninger behandles hos riktig fortrolig instans og tas ikke inn i felles håndbok.', 'Følg opp anbefalinger med ansvar/frister og vurder effekt. Bruk anonymiserte felles funn til forbedring.'],
  'BHT-avtale/plan, arbeidsmiljøkartlegginger, målinger og tiltaksoppfølging uten individuelle journalopplysninger.',[AML,law('Forskrift om organisering, ledelse og medvirkning','https://www.arbeidstilsynet.no/regelverk/forskrifter/forskrift-om-organisering-ledelse-og-medvirkning/')],'bht|helse|støy|inneklima|ergonomi'),
 r('psychosocial','Psykososialt miljø, tilrettelegging og sykefravær',1,['U12'],
  'Forebygge skadelig arbeidspress og gi nødvendig støtte og tilrettelegging.',
  'Arbeidsgiver følger opp organiseringen sammen med ansatte/verneombud. Leder håndterer individuell oppfølging fortrolig og bruker BHT ved behov.',
  ['Kartlegg uklare eller motstridende krav, arbeidsmengde/tidspress, emosjonelle krav og tilgang til støtte. Vurder faktorene hver for seg og samlet, også på lang sikt.', 'Avtal tiltak som endrer arbeidsforholdene: tydelig ansvar, realistiske krav, støtte og håndtering av vold, trusler, trakassering eller annen utilbørlig opptreden.', 'Ved behov for tilrettelegging avklares funksjon og mulige tiltak med medarbeideren uten å kreve unødvendige diagnosedetaljer. Følg aktuelle krav til sykefraværsoppfølging og dialog.', 'Kontroller om tiltakene virker og om medarbeidere kan si fra trygt. Personkonflikter og helseopplysninger behandles utenfor felles avviksregister.'],
  'Medvirkning, risikovurdering og handlingsplan. Individuelle tilretteleggings-/oppfølgingsplaner lagres særskilt.',[AML,UTF,guide('Arbeidstilsynet – psykososialt arbeidsmiljø','https://www.arbeidstilsynet.no/arbeidsmiljo/psykososialt-arbeidsmiljo/')],'arbeidsmiljø|psykososial|sykefravær|tilrettelegg'),
 r('pay','Lønnsjustering og bonus',1,['K084'],
  'Behandle lønnsendringer etter avtalte kriterier og riktig fullmakt.',
  'Leder med fullmakt beslutter endringen. Lønnsansvarlig kontrollerer gjennomføring og lovpålagte plikter.',
  ['Avklar arbeids-/tariffavtale, eventuelle allmenngjorte krav og firmaets kriterier. Bonusvilkår skal være forståelige og avklart før perioden de gjelder.', 'Vurder grunnlaget saklig og konsistent. Kontroller habilitet og at ordningen ikke fremmer uforsvarlig arbeid eller strider mot diskrimineringsreglene.', 'Gi medarbeideren skriftlig informasjon om beslutning, virkningstidspunkt og eventuelle vilkår. Lønnsdata deles med dem som trenger dem.', 'Kontroller at godkjent endring er riktig registrert i eksisterende lønnssystem og at skatte-/rapporteringsplikter ivaretas.'],
  'Avtale/kriterier, godkjenning, medarbeiderinformasjon og kontrollert lønnsgrunnlag i avgrenset personalområde.',[AML,law('Likestillings- og diskrimineringsloven','https://lovdata.no/lov/2017-06-16-51')],'lønn|bonus|personal'),
 r('safety-representative','Verneombud og medvirkning',1,['K085'],
  'Gi ansatte en kjent og reell representant i arbeidsmiljøarbeidet.',
  'Arbeidsgiver sørger for ordning, opplæring og tid etter gjeldende krav. Ansatte velger verneombud etter relevant regelverk.',
  ['Avklar krav til verneombud, verneområder og eventuelt arbeidsmiljøutvalg ut fra firmaets størrelse og forhold. En annen lovlig ordning må vurderes og dokumenteres særskilt.', 'Gjør kontaktperson og rolle kjent. Gi nødvendig opplæring, informasjon og tid til oppgavene.', 'Involver verneombudet i risikovurdering, vernerunder, planlagte endringer og arbeidsmiljøtiltak. Ansvar for forsvarlig arbeid ligger fortsatt hos arbeidsgiver.', 'Ta opp farer med leder. Ved umiddelbar fare ivaretas verneombudets lovbestemte stansingsrett; oppfølgingen og trygg videre drift avklares.'],
  'Valg/ordning, verneområder, opplæring, medvirkning og oppfølging av henvendelser.',[AML],'verneombud|arbeidsmiljø|hms'),
 r('transparency','Åpenhetsloven og ansvarlige leverandørkjeder',0,['K087'],
  'Avklare lovplikter og følge opp risiko for menneskerettigheter og arbeidsforhold.',
  'Ledelsen vurderer om firmaet omfattes og fordeler ansvar for aktsomhetsvurderinger, redegjørelse og informasjonskrav.',
  ['Vurder lovens virkeområde og vilkår for større virksomheter for den aktuelle perioden. Et leverandørkrav er ikke det samme som at firmaet selv har alle lovpliktene.', 'Forankre arbeidet i ledelsen, kartlegg leverandørkjeden og vurder risiko. Prioriter alvorlige mulige/aktuelle negative konsekvenser.', 'Iverksett og følg opp tiltak, samarbeid med relevante leverandører og sørg for gjenoppretting når firmaets ansvar krever det. Dokumenter hva som faktisk er gjort.', 'Hvis firmaet omfattes: lag lovpålagt redegjørelse og håndter informasjonskrav innen gjeldende frister. Ikke publiser fortrolige personalopplysninger eller udokumenterte garantier.'],
  'Virkeområdevurdering, risikokartlegging, prioritering, tiltak, resultat og eventuell redegjørelse/informasjonslogg.',[law('Åpenhetsloven','https://lovdata.no/lov/2021-06-18-99'),guide('Forbrukertilsynet – åpenhetsloven','https://www.forbrukertilsynet.no/vi-jobber-med/apenhetsloven')],'åpenhetslov|leverandørkjede|aktsomhet'),
 r('environment-policy','Miljømål og oppfølging',4,['K088'],
  'Knytte miljøarbeidet til virksomhetens viktigste påvirkninger og faktiske tiltak.',
  'Ledelsen vedtar mål. Miljø-/KS/HMS-ansvarlig følger dem sammen med prosjektleder og medarbeidere.',
  ['Kartlegg avfall, utslipp, innkjøp, transport og energi i egne aktiviteter. Avklar lov-, kontrakts- og kundekrav.', 'Velg konkrete mål og tiltak med eier, frist og målbar oppfølging der det er hensiktsmessig.', 'Gjør tiltakene kjent og avklar praktiske valg på arbeidsstedet. Miljøpåstander skal kunne dokumenteres.', 'Gjennomgå resultater, hendelser og endringer. Oppdater planen og del erfaringer fra prosjektene.'],
  'Miljøkartlegging, vedtatte mål, handlingsplan og resultatgrunnlag.',[IK,TEK],'miljø|bærekraft'),
 r('environment-buying','Miljøhensyn ved innkjøp',4,['K089'],
  'Velge produkter og leveranser med dokumentert kvalitet og lavere relevant miljøbelastning.',
  'Innkjøpsansvarlig vurderer alternativer sammen med faglig/prosjektansvarlig.',
  ['Avklar nødvendige funksjons-/kvalitetskrav og prosjektets miljøkrav før valg. Vurder levetid, vedlikehold og mulig ombruk.', 'Innhent relevant produkt-/miljødokumentasjon og vurder kjemisk innhold, emballasje og avfall. Merking alene avgjør ikke om produktet passer løsningen.', 'Sammenlign alternativer innen godkjent prosjekteringsgrunnlag. Avklar endring før et annet produkt bestilles.', 'Kontroller mottatt produkt og dokumentasjon mot bestilling, og registrer vesentlige miljøavvik.'],
  'Produktgrunnlag, vurderte alternativer, godkjent valg og mottakskontroll.',[TEK,IK],'miljø|innkjøp|ombruk'),
 r('environment-transport','Miljøhensyn ved transport',4,['K090'],
  'Redusere unødvendige turer og utslipp uten å svekke sikkerheten.',
  'Prosjekt-/transportansvarlig planlegger levering og følger opp firmaets mål.',
  ['Samordne levering, retur og avfallshenting innenfor forsvarlig last og fremdrift.', 'Vurder rute, kjøretøy og transportmåte etter behov, utslipp og lokale krav. Sikring av last og trafikksikkerhet går foran effektivisering.', 'Unngå unødvendig tomgang og følg rutiner for vedlikehold og lekkasjekontroll.', 'Følg opp avtalt grunnlag som turer, drivstoff eller utslipp. Undersøk avvik og tilpass planleggingen.'],
  'Transporttiltak, relevant resultatgrunnlag og oppfølging av miljø-/sikkerhetsavvik.',[IK,law('Vegtrafikkloven','https://lovdata.no/lov/1965-06-18-4')],'miljø|transport'),
 r('environment-energy','Energi og avslutning av arbeidsdagen',4,['K092','U07'],
  'Unngå unødvendig energibruk og usikret utstyr etter arbeid.',
  'Arbeidsleder avklarer hvem som avslutter og hvilke anlegg som må fortsette drift.',
  ['Avklar oppvarming, belysning, uttørking og andre energibehov med hensyn til produktkrav, fukt og sikkerhet.', 'Bruk egnet styring og kontroller unødvendig forbruk. Ikke slå av nødvendig ventilasjon, alarmer eller sikring.', 'Ved slutt kontrolleres lys, varme og maskiner etter lokal liste; låsing og adgang følger firmaets sikringsrutine.', 'Følg opp forbruk der det finnes et egnet grunnlag og rett lekkasjer/feil som øker belastning.'],
  'Lokale avslutningspunkter, energitiltak og feil-/resultatoppfølging.',[IK,TEK],'energi|varme|uttørking|miljø'),
 r('privacy-register','Personvernansvar og behandlingsoversikt',5,['K093','K094'],
  'Ha oversikt over hvorfor firmaet behandler personopplysninger og hvordan de beskyttes.',
  'Ledelsen er ansvarlig for virksomhetens behandling. Utpekt personvernkontakt vedlikeholder oversikten med systemeiere.',
  ['Kartlegg behandlinger med formål, opplysningstyper, behandlingsgrunnlag, mottakere og oppbevaring. Avklar særlige kategorier og nødvendige supplerende vilkår.', 'Vurder risiko for de registrerte og behov for personvernkonsekvensvurdering før ny behandling eller vesentlig endring.', 'Gi forståelig informasjon og begrens innsamling/tilgang. Samtykke brukes bare når det er et egnet og frivillig grunnlag.', 'Kontroller tilgang, databehandleravtaler, overføring og sletting. Personvernbrudd vurderes raskt med eventuell melding og informasjon etter gjeldende krav.'],
  'Behandlingsoversikt, grunnlag, informasjon, risikovurderinger og avgrenset avviks-/slettelogging.',[GDPR,PV],'personvern|personopplys|it-system'),
 r('gps','GPS, lokalisering og andre kontrolltiltak',5,['K095'],
  'Avklare lovlig behov og begrense sporing av medarbeidere.',
  'Ledelsen vurderer tiltaket før anskaffelse og involverer tillitsvalgte/ansatte etter gjeldende regler.',
  ['Beskriv konkret formål og vurder mindre inngripende alternativer. Dokumenter saklig grunn, forholdsmessighet og eget personvernrettslig grunnlag.', 'Drøft tiltaket og gi informasjon før oppstart om formål, opplysninger, bruk, lagring og rettigheter.', 'Begrens sporing og tilgang til det avtalte behovet. Avklar privatbruk og unngå senere bruk til et annet formål uten ny vurdering.', 'Kontroller nødvendighet og sletting jevnlig. Ansatte kan henvende seg til personvernkontakt/verneombud om spørsmål eller feil.'],
  'Behovs-/forholdsmessighetsvurdering, drøfting, informasjon, tilgangsregler og bevarings-/sletteplan.',[AML,GDPR,PV],'gps|sporing|lokaliser|flåte'),
 r('customer-data','Personopplysninger om kunder og leverandører',5,['K096'],
  'Bruke kontakt- og leveransedata til avklarte formål og dele med riktig mottaker.',
  'Kunde-/leverandøransvarlig følger firmaets personvern- og dokumentrutine.',
  ['Samle kontakt- og prosjektopplysninger som er nødvendige for avtale, leveranse og aktuelle lovplikter. Gi relevant informasjon om behandlingen.', 'Unngå private opplysninger i prosjektnotater og bilder. Kontroller hvem som kan se rapporter og vedlegg.', 'Avklar grunnlag før bruk til markedsføring eller nytt formål. Databehandler/selvstendig behandlingsansvar må vurderes ut fra faktisk rolle.', 'Håndter rettighetskrav og sletting etter firmaets rutine, med særskilt vurdering av dokumenter som må bevares.'],
  'Formål/grunnlag, mottakere, relevant informasjon og dokumentert bevaringsvurdering.',[GDPR],'kunde|leverandør|personvern'),
 r('processors','Databehandlere, avtaler og overføringer',5,['K097','U06'],
  'Ha kontroll over tjenester som behandler opplysninger på firmaets vegne.',
  'Systemeier kartlegger tjenesten. Ledelsen godkjenner avtale, risiko og eventuelle overføringer.',
  ['Avklar om leverandøren er databehandler eller selvstendig ansvarlig. Før oversikt over system, opplysninger, databehandler og underleverandører.', 'Inngå egnet databehandleravtale før behandlingen starter. Avklar instruks, sikkerhet, bistand, hendelser, retur/sletting og revisjonsmulighet.', 'Vurder hvor data behandles og hvilket grunnlag som kreves for eventuell overføring utenfor EØS. Kartlegg underdatabehandlere og endringsvarsler.', 'Følg opp avtalte kontroller og vesentlige endringer. Ved avslutning kontrolleres dataretur og nødvendig sletting.'],
  'Databehandleroversikt, avtaler, underleverandører, overførings-/risikovurderinger og oppfølging.',[GDPR],'databehandler|skytjeneste|it-system|personvern'),
 r('physical-access','Adgang, nøkler og sikring av lokaler',5,['K098','U07'],
  'Begrense adgang og beskytte personer, utstyr og dokumentasjon.',
  'Lokal-/utstyrsansvarlig tildeler og tilbakekaller adgang. Medarbeider følger besøks- og avslutningsrutinen.',
  ['Avklar hvem som trenger adgang til hvilke områder. Registrer nøkler/adgangskort og håndter besøk med relevant ansvarlig.', 'Oppbevar sensitive dokumenter og utstyr i egnet låst område. Del ikke nøkler, koder eller adgang med uvedkommende.', 'Kontroller dører, vinduer, lys, utstyr og alarm etter lokal avslutningsliste. Utstyr som må gå videre drift markeres tydelig.', 'Meld tap og innbrudd straks. Sperr adgang ved endring/fratredelse og vurder nødvendige sikringstiltak.'],
  'Adgangsoversikt, nøkler, lokale kontrollpunkter og sporbar tilbakekalling. Adgangslogger har eget formål og lagringsbehov.',[IK,GDPR],'adgang|nøkkel|lokale|lager'),
 r('camera','Kameraovervåking og tilgang til opptak',5,['K099'],
  'Bruke eventuell overvåking bare etter dokumentert behov og innen lovlige rammer.',
  'Ledelsen godkjenner nødvendighet, område og behandlingsgrunnlag før kamera settes opp.',
  ['Vurder sikkerhetsbehov, mindre inngripende alternativer og krav etter arbeidsmiljø-/personvernreglene. Kamera i personalområder som toalett, garderobe og pauserom brukes ikke.', 'Avklar utsnitt, formål og lagring; unngå unødvendig overvåking av naboer, offentlig ferdsel eller medarbeidernes arbeid.', 'Drøft og informer før oppstart og bruk nødvendig skilting. Begrens tilgang til opptak og utlevering til personer med saklig behov og grunnlag.', 'Kontroller fortsatt behov og sletting. Endret bruk eller analyse krever ny vurdering; overvåking er ikke et standardkrav i denne håndboken.'],
  'Behov-/grunnlagsvurdering, drøfting, informasjon/skilting, tilgang og sletteplan.',[AML,GDPR,PV],'kamera|overvåk'),
 r('intranet','Publisering på intranett og deling av bilder',5,['K100'],
  'Publisere forståelig informasjon uten å spre private eller fortrolige opplysninger.',
  'Innholdseier vurderer publiseringen. Personvernkontakt bistår med grunnlag og eventuelle rettighetskrav.',
  ['Avklar formål, målgruppe og nødvendig innhold før publisering. Internt innhold kan også omfatte personopplysninger.', 'Kontroller fakta, mottakertilgang, opphavsrett og personverngrunnlag for bilder/navn. Ikke legg personalsaker eller helseopplysninger på felles intranett.', 'Bruk avtalte lagrings-/publiseringssteder og merk hvem som eier innholdet. En lenke med offentlig tilgang behandles som offentlig deling.', 'Rett feil og fjern utgått innhold etter plan. Håndter innvendinger og tilbaketrekking der grunnlaget krever det.'],
  'Publiseringsregler, innholdseier, nødvendige avklaringer og oppdatering/sletting.',[GDPR,PV],'intranett|publiser|bilde|nettsted'),
 r('it-systems','Godkjente IT-systemer og informasjonssikkerhet',5,['K101'],
  'Beskytte firmaets opplysninger ved valg og bruk av digitale tjenester.',
  'Systemeier godkjenner tjenesten. IT-/personvernansvarlig avklarer sikkerhet og databehandling før bruk.',
  ['Vurder formål, opplysninger, leverandør, tilgang, datalagring og gjenoppretting før et system tas i bruk. Avklar databehandleravtale og overføring ved behov.', 'Bruk personlige kontoer, minste nødvendige tilgang og egnet sterk autentisering. Passord og sikkerhetskoder deles ikke.', 'Hold utstyr oppdatert og bruk avtalte steder for filer og sikkerhetskopi. Ikke legg person-, kunde- eller firmadata i en ny sky-/KI-tjeneste uten godkjenning.', 'Meld mistenkelige lenker, tap og feiltilgang straks. Sikre situasjonen og vurder hendelsen, gjenoppretting og eventuell personvernvarsling.'],
  'Godkjent systemoversikt, risiko, tilgang, avtaler, gjenopprettingsprøve og avgrenset hendelseslogg.',[GDPR,IK],'it-system|datasikker|informasjonssikker|digital|ki-tjeneste'),
 r('privacy-rights','Innsyn, retting, sletting og utlevering',5,['K102'],
  'Gi riktig person et korrekt svar på personvernkrav uten å utlevere andres opplysninger.',
  'Personvernkontakt koordinerer kravet. Systemeier finner relevant grunnlag innen fristen.',
  ['Registrer mottak og hva personen ber om. Kontroller identitet på en forholdsmessig måte før opplysninger utleveres.', 'Kartlegg relevant behandling og vurder rettighet, frist, eventuell lovlig begrensning og hensyn til andre personer.', 'Gi forståelig svar gjennom sikker kanal. Retting/sletting eller eventuell lovlig videre oppbevaring begrunnes og følges opp hos relevante mottakere.', 'Dokumenter saksbehandlingen og informer om relevante klagemuligheter. Kravet legges ikke i et bredt delt avviksregister.'],
  'Avgrenset kravlogg, identitets-/rettighetsvurdering, svar og kontrollert oppfølging.',[GDPR],'innsyn|retting|sletting|personvern'),
 r('email-inspection','Innsyn i ansattes e-post og lagret materiale',5,['K103'],
  'Håndtere et eventuelt innsyn etter særreglene og begrense inngrepet.',
  'Ledelsen vurderer lovvilkårene og innhenter nødvendig kompetanse. IT utfører bare en konkret godkjent instruks.',
  ['Vurder om innsyn kan være lovlig etter e-postforskriften og om mindre inngripende tiltak er tilstrekkelige. Teknisk administratorrett gir ikke i seg selv rett til innsyn.', 'Dokumenter behov, omfang og habilitet. Følg kravene til forhåndsvarsel, uttalelse og tilstedeværelse/bistand når de gjelder.', 'Begrens søk og tilgang til relevant materiale. Hold private opplysninger utenfor videre deling og protokollfør gjennomføringen.', 'Gi nødvendig informasjon i etterkant og håndter lagring, rettigheter og sletting. Automatisk videresending av hele tidligere ansattes postkasse brukes ikke som en enkel standardløsning.'],
  'Fortrolig vilkårsvurdering, varsling, innsynsprotokoll, informasjon og bevarings-/slettebeslutning.',[law('Forskrift om arbeidsgivers innsyn i e-postkasse og annet elektronisk lagret materiale','https://lovdata.no/forskrift/2018-07-02-1108'),GDPR,PV],'epost|e-post|innsyn|laptop'),
 r('leaving','Fratredelse, tilbakelevering og sletting',1,['K104','U14'],
  'Avslutte tilgang og arbeidsforhold ordnet uten å slette nødvendig dokumentasjon eller beholde alt.',
  'Leder koordinerer avslutningen. IT-/utstyrsansvarlig og personal-/lønn følger sine kontrollpunkter.',
  ['Avklar sluttdato, pågående leveranser og hvem som overtar oppgaver. Informer relevante kontaktpersoner uten unødvendige private detaljer.', 'Tilbakekall konti, firmamoduler, adgang, nøkler og utstyr ved riktig tidspunkt. Kontroller delte ressurser og eventuelle fullmakter.', 'Vurder bevaring per dokumenttype og grunnlag, samt nødvendig retur/sletting av personopplysninger. Individuelle arbeidsmapper gjennomgås innen lovlige rammer.', 'Kontroller at sperring og tilbakelevering er fullført. E-post eller lagret materiale håndteres etter egen innsynsrutine og uten automatisk full videresending.'],
  'Fortrolig avslutningsliste, overlevering, sperringskontroll, utstyrsretur og dokumentert bevarings-/slettevurdering.',[AML,GDPR,PV],'fratred|slutt|personal|tilgang'),
 r('serious-incident','Alvorlig ulykke, nestenulykke og krisekommunikasjon',2,['U02','U03','U09'],
  'Prioritere hjelp, lovpålagt varsling og trygg oppfølging etter en alvorlig hendelse.',
  'Arbeidsleder leder lokale strakstiltak. Arbeidsgiver vurderer myndighetsvarsling og utpeker informasjonsansvarlig.',
  ['Varsle nødetatene ved akutt fare og gi førstehjelp innen kompetanse og instruks. Sikre området uten å utsette flere for fare.', 'Arbeidsgiver avklarer og utfører pålagt melding, blant annet ved alvorlig personskade/dødsfall. Ivareta berørte personer og samarbeid med nødetater/myndigheter.', 'Bevar relevante fakta, bilder og grunnlag uten å hindre redning. Nestenulykker registreres også for læring, med begrenset bruk av personopplysninger.', 'Informasjonsansvarlig avklarer fakta og kontakt med kunde/media. Undersøk årsak, avtal tiltak og kontroller effekt før gjenopptakelse; fortrolig personoppfølging holdes separat.'],
  'Hendelseslogg, relevante meldinger, årsaks-/tiltaksvurdering og gjenoppstartskontroll. Personalsaksopplysninger begrenses.',[AML,IK],'ulykke|beredskap|krise|ruh'),
 r('special-hazards','Særskilt risiko: storulykke, stråling og helse/miljø',2,['U10'],
  'Avklare særregelverk og fagkompetanse før arbeid med risiko utenfor vanlig drift.',
  'Ledelsen og arbeidsleder innhenter faglig bistand og avklarer ansvar før oppdraget aksepteres.',
  ['Kartlegg radioaktive kilder/stråling, store mengder farlig stoff og mulige konsekvenser for naboer, helse og miljø. Vurder om aktiviteten omfattes av særregler.', 'Avklar tillatelser, meldinger, kompetanse, sikring og samordning med anleggseier og relevante myndigheter.', 'Lag oppgavespesifikk plan med forebyggende tiltak, overvåking og beredskap. Vanlig håndbok/SJA alene er ikke tilstrekkelig ved manglende kvalifikasjoner.', 'Stans ved uavklart risiko og bruk kvalifisert virksomhet. Kontroller vilkår og overlever nødvendig sikkerhetsinformasjon.'],
  'Virkeområdevurdering, faglige avklaringer, relevante tillatelser og særskilt risiko-/beredskapsplan.',[IK,law('Strålevernloven','https://lovdata.no/lov/2000-05-12-36'),law('Storulykkeforskriften','https://lovdata.no/forskrift/2016-06-03-569')],'stråle|radioaktiv|storulykke|farlig stoff'),
 ];
}
