import {useEffect,useId,useRef,useState} from 'react';
import {kshmsRpc} from './kshmsAccess.js';
import DeviationDialog from '../deviations/DeviationDialog.jsx';
import {formatDeviationDate,formatDeviationDateTime} from '../deviations/deviationDates.mjs';
import {publishDeviationChange} from './kshmsDeviations.mjs';
import {useKshmsJobChoices,ProjectChoice} from './KshmsJobChoices.jsx';
import {EXECUTION_STATEMENT,ROUND_SUGGESTIONS,newExecution,newPoint,newRisk,executionContent,executionIssues,riskScore,riskBand,readExecutionDraft,storeExecutionDraft,executionDraftKey,saveExecution} from './kshmsExecutions.mjs';
import './kshmsExecutions.css';

function Field({label,value,onChange,field,type='text',multiline=false,maxLength=5000,hint}){const id=useId();return <label className="ks-field" htmlFor={id}><span>{label}</span>{hint&&<span className="ks-field-hint">{hint}</span>}{multiline?<textarea id={id} data-execution-field={field} value={value??''} rows={3} maxLength={maxLength} onChange={e=>onChange(e.target.value)}/>:<input id={id} data-execution-field={field} type={type} value={value??''} maxLength={maxLength} onChange={e=>onChange(e.target.value)}/>}</label>;}
function Member({label,value,onChange,members,field,readOnly,identity}){return <label className="ks-field"><span>{label}</span>{readOnly?<span>{identity?.name||identity?.email||members.find(m=>m.id===value)?.identity?.name||'Ikke valgt'}</span>:<select data-execution-field={field} value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Velg ansvarlig</option>{value&&!members.some(m=>m.id===value)&&<option value={value}>Tidligere ansvarlig – velg en aktiv bruker</option>}{members.map(m=><option key={m.id} value={m.id}>{m.identity?.name||m.identity?.email||'Aktiv bruker'}</option>)}</select>}</label>;}
function Score({label,p,c,acceptance,planned}){const score=riskScore(p,c),band=riskBand(score,acceptance);return <span className={`ks-risk-score ks-risk-${band.toLowerCase()}`}>{label}: {score??'–'} · {band}{planned&&score!=null?' (forventet)':''}</span>;}
function Matrix({acceptance}){if(!(Number.isInteger(Number(acceptance.low_max))&&Number.isInteger(Number(acceptance.medium_max))&&Number(acceptance.low_max)>=1&&Number(acceptance.low_max)<Number(acceptance.medium_max)&&Number(acceptance.medium_max)<25))return <p role="status">Velg gyldige grenser før matrisen vises.</p>;return <div className="ks-risk-matrix"><table><caption>5×5: sannsynlighet × konsekvens</caption><thead><tr><th scope="col">S ↓ / K →</th>{[1,2,3,4,5].map(n=><th scope="col" key={n}>{n}</th>)}</tr></thead><tbody>{[5,4,3,2,1].map(s=><tr key={s}><th scope="row">{s}</th>{[1,2,3,4,5].map(k=><td key={k} className={'ks-risk-'+riskBand(s*k,acceptance).toLowerCase()}>{s*k}</td>)}</tr>)}</tbody></table><p>Lav: 1–{acceptance.low_max}. Moderat: {Number(acceptance.low_max)+1}–{acceptance.medium_max}. Høy: over {acceptance.medium_max}. En score er støtte for vurderingen. Firmaets faktiske krav og faglige vurdering avgjør hva som må gjøres.</p></div>;}
async function preparePhoto(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10000000)throw Error('Velg et JPG-, PNG- eller WebP-bilde på inntil 10 MB.');
 const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Bildet kunne ikke åpnes.'));img.src=url;});const scale=Math.min(1,1280/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('Nettleseren kunne ikke klargjøre bildet.');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/jpeg',.75);if(data.length>400000)data=canvas.toDataURL('image/jpeg',.45);if(data.length>400000)throw Error('Bildet er fortsatt for stort. Velg et mindre bilde.');return {id:crypto.randomUUID(),data};}finally{URL.revokeObjectURL(url);}
}
export default function KshmsExecutions({context,kind,active=true}){
 const companyId=context.company_id,userId=context.user_id,isRound=kind==='round',label=isRound?'Vernerunder og kontroller':'Risikovurderinger';
 const [data,setData]=useState(null),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[cached,setCached]=useState(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[issues,setIssues]=useState([]),[confirmed,setConfirmed]=useState(false),[status,setStatus]=useState('all'),[query,setQuery]=useState('');
 const jobChoices=useKshmsJobChoices(context,Boolean(editor));
 const scopeRef=useRef(null),lock=useRef(false),loadNumber=useRef(0),editorRef=useRef(null),dialogRef=useRef(null);const current=scope=>scope?.active&&scopeRef.current===scope;
 const scopeValid=value=>value?.company_id===companyId&&value.user_id===userId&&value.enabled;
 const load=async(append=false)=>{const scope=scopeRef.current,sequence=++loadNumber.current;const cursor=append?data?.next:null;const value=await kshmsRpc('kshms_execution_state',{p_company_id:companyId,p_kind:kind,p_status:status,p_query:query,p_before:cursor?.updated_at||null,p_before_id:cursor?.id||null});if(!current(scope)||sequence!==loadNumber.current)return null;if(!scopeValid(value.context))throw Error('Tilgangen til gjennomføringene er endret.');setData(previous=>append?{...value,records:[...(previous?.records||[]),...value.records].filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i)}:value);return value;};
 useEffect(()=>{const scope={active:true};scopeRef.current=scope;setCached(readExecutionDraft(window.localStorage,userId,companyId,kind));return()=>{scope.active=false;loadNumber.current++;};},[companyId,userId,kind,context.manage]);
 useEffect(()=>{const scope=scopeRef.current;if(scope?.active)load().catch(e=>{if(current(scope))setError(e.message);});},[status,query,companyId,userId,kind,context.manage]);
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const cache=next=>{editorRef.current=next;setEditor(next);setDirty(true);setConfirmed(false);setIssues([]);setNotice('');try{storeExecutionDraft(window.localStorage,userId,companyId,next);setCached(next);}catch{setError('Kladden kunne ikke sikres på denne enheten. La dialogen stå åpen og lagre før du går videre.');}};
 const change=content=>cache({...editorRef.current,content,requestId:crypto.randomUUID()});
 const choose=next=>{if(lock.current)return false;if(cached&&cached.id!==next.id&&!window.confirm('Åpne en annen gjennomføring? Den forrige lokale kladden erstattes når du skriver i den nye.'))return false;editorRef.current=next;setEditor(next);setDetail(null);setDirty(false);setError('');setNotice('');setIssues([]);setConfirmed(false);return true;};
 const clearLocal=()=>{setCached(null);try{window.localStorage.removeItem(executionDraftKey(userId,companyId,kind));}catch{/* Confirmed server state remains valid if local cleanup is unavailable. */}};
 const open=async row=>{if(lock.current)return;const scope=scopeRef.current;lock.current=true;setBusy(true);try{const value=await kshmsRpc('kshms_execution_detail',{p_company_id:companyId,p_id:row.id});if(!current(scope))return;if(!scopeValid(value.context)||value.record?.company_id!==companyId||value.record.id!==row.id||value.record.kind!==kind)throw Error('Gjennomføringen er ikke tilgjengelig her.');const r=value.record;const local=cached?.id===r.id&&r.status==='draft'?cached:null;const next=local||{...r,requestId:crypto.randomUUID()};editorRef.current=next;setEditor(next);setDetail(value);setDirty(Boolean(local));setConfirmed(false);setError('');setNotice('');setIssues([]);}catch(e){if(current(scope))setError(e.message);}finally{lock.current=false;if(current(scope))setBusy(false);}};
 const save=async action=>{if(lock.current||!editorRef.current)return;const scope=scopeRef.current;lock.current=true;setBusy(true);setError('');setIssues([]);try{const c=executionContent(editorRef.current.content,kind);if(action==='complete'){const missing=executionIssues(c,kind);if(!confirmed)missing.push({key:'confirmation',message:'Bekreft din egen gjennomgang.'});if(missing.length){setIssues(missing);return;}}const value=await saveExecution({rpc:kshmsRpc,companyId,userId,editor:editorRef.current,action,confirmed,isCurrent:()=>current(scope)});if(!value||!current(scope))return;setDetail(value);setDirty(false);clearLocal();const next={...value.record,requestId:crypto.randomUUID()};editorRef.current=next;setEditor(next);setConfirmed(false);setNotice(action==='complete'?'Gjennomføringen er fullført og ligger i historikken. Åpne avvik må fortsatt følges opp og lukkes av ansvarlig.':'Utkastet er lagret. Du kan fortsette senere.');for(const link of value.links||[])if(link.case)publishDeviationChange(link.case);await load();}catch(e){if(current(scope)){setError(e.message+' Kladden er beholdt.');if(e.code==='40001'){try{const value=await kshmsRpc('kshms_execution_detail',{p_company_id:companyId,p_id:editorRef.current.id});if(current(scope)&&scopeValid(value.context))setDetail(value);}catch{}}}}finally{lock.current=false;if(current(scope))setBusy(false);}};
 const upload=async(pointId,files)=>{if(lock.current)return;const scope=scopeRef.current;lock.current=true;setBusy(true);setError('');try{const photos=[];for(const file of files)photos.push(await preparePhoto(file));if(!current(scope))return;const e=editorRef.current,a=e.content.answers[pointId]||{};const all=[...(a.photos||[]),...photos];if(all.length>3)throw Error('Bruk inntil tre bilder per sjekkpunkt.');const content={...e.content,answers:{...e.content.answers,[pointId]:{...a,photos:all}}};executionContent(content,kind);change(content);}catch(e){if(current(scope))setError(e.message);}finally{lock.current=false;if(current(scope))setBusy(false);}};
 const repeat=()=>{const next=newExecution(kind,userId);next.content.title=editor.content.title;next.content.workplace=editor.content.workplace;next.content.routines=editor.content.routines;if(isRound){next.content.points=structuredClone(editor.content.points);next.template_version_id=editor.template_version_id;next.template_snapshot=editor.template_snapshot;next.project_id=editor.project_id;}else{next.content.risks=editor.content.risks.map(r=>({...newRisk(),activity:r.activity,hazard:r.hazard,consequence:r.consequence}));next.content.basis=editor.content.basis;next.content.acceptance={...editor.content.acceptance,confirmed:false};next.project_id=editor.project_id;}if(choose(next))cache(next);};
 const c=editor?.content,readOnly=editor?.status==='completed',members=data?.members||[],conflict=editor&&detail?.record.status==='draft'&&detail.record.revision!==editor.revision;
 const updatePoint=(id,key,value)=>change({...c,points:c.points.map(p=>p.id===id?{...p,[key]:value}:p)});
 const answer=(id,key,value)=>change({...c,answers:{...c.answers,[id]:{...c.answers[id],[key]:value}}});
 const updateRisk=(id,key,value)=>change({...c,risks:c.risks.map(r=>r.id===id?{...r,[key]:value}:r)});
 const focus=key=>{const target=dialogRef.current?.querySelector(`[data-execution-field="${key}"]`);if(target){const disclosure=target.closest('details');if(disclosure)disclosure.open=true;target.focus();target.scrollIntoView({block:'center'});}};
 return <div className="ks-executions"><div className="ks-card"><h3>{label}</h3><p>{isRound?'Kontroller arbeidsstedet med egne punkter eller en publisert firmaliste. Lagre underveis. Fullfør når kontrollen og oppfølgingen er dokumentert.':'Beskriv jobben og farene. Vurder sannsynlighet og konsekvens før og etter tiltak. Dokumenter hvem som følger opp, frist og en uttrykkelig beslutning.'}</p><div className="ks-execution-actions"><button type="button" disabled={!data||busy} onClick={()=>choose(newExecution(kind,userId))}>{isRound?'Ny vernerunde / kontroll':'Ny risikovurdering'}</button>{cached&&<button type="button" className="secondary" disabled={busy} onClick={()=>{if(cached.revision>0)open({id:cached.id});else{choose(cached);setDirty(true);}}}>Fortsett lokal kladd</button>}<button type="button" className="secondary" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Oppdater</button></div></div>
  {error&&!editor&&<p className="ks-error" role="alert">{error}</p>}{notice&&!editor&&<p className="ks-notice" role="status">{notice}</p>}
  <div className="ks-execution-filters"><Field label="Søk etter navn" maxLength={160} value={query} onChange={setQuery}/><label className="ks-field"><span>Vis gjennomføringer</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Alle</option><option value="draft">Under arbeid</option><option value="completed">Fullførte / historikk</option></select></label></div>
  {!data?<p role="status">Henter gjennomføringer …</p>:<><div className="ks-execution-list">{data.records.map(r=><article className="ks-card" key={r.id}><span className="ks-badge">{r.status==='completed'?'Fullført':'Under arbeid'}</span><h4>{r.title}</h4><p>{r.workplace} · {formatDeviationDate(r.planned_on)}</p>{r.completed_at&&<p>Fullført av {r.completed_identity?.name||r.completed_identity?.email} · {formatDeviationDateTime(r.completed_at)}</p>}<button type="button" className="secondary" disabled={busy} onClick={()=>open(r)}>{r.status==='completed'?'Åpne dokumentasjon':'Fortsett gjennomføring'}</button></article>)}</div>{!data.records.length&&<p>Ingen gjennomføringer i dette utvalget.</p>}{data.next&&<button type="button" className="secondary" disabled={busy} onClick={()=>load(true).catch(e=>setError(e.message))}>Vis eldre gjennomføringer</button>}</>}
  {editor&&active&&<DeviationDialog title={isRound?'Vernerunde / kontroll':'Risikovurdering 5×5'} context={context.company_name} closeLabel="Lukk gjennomføring" busy={busy} onClose={()=>{if(!lock.current){setEditor(null);setDetail(null);setError('');setIssues([]);}}}>
   <div ref={dialogRef} className="ks-executions">{error&&<p role="alert" className="ks-error">{error}</p>}{notice&&<p role="status" className="ks-notice">{notice}</p>}{issues.length>0&&<div role="alert" className="ks-closure-missing"><strong>Dette mangler før fullføring</strong><ul>{issues.map((i,n)=><li key={n}><button type="button" className="ks-issue" onClick={()=>focus(i.key)}>{i.message}</button></li>)}</ul></div>}
    {readOnly&&<p className="ks-notice">Fullført av {editor.completed_identity?.name||editor.completed_identity?.email} · {formatDeviationDateTime(editor.completed_at)}. {editor.statement}</p>}
    {conflict&&<div className="ks-closure-missing"><strong>En annen person har lagret endringer</strong><details><summary>Les lagret utgave før du velger</summary><p>{detail.record.content.title}</p><p>{detail.record.content.review}</p><pre>{JSON.stringify({...detail.record.content,answers:Object.fromEntries(Object.entries(detail.record.content.answers||{}).map(([k,a])=>[k,{...a,photos:(a.photos||[]).length+' bilder'}]))},null,2)}</pre></details><button type="button" className="secondary" disabled={busy} onClick={()=>{cache({...editor,revision:detail.record.revision,requestId:crypto.randomUUID()});setError('Din kladd er beholdt. Neste lagring erstatter den lagrede teksten.');}}>Fortsett med min kladd på nyeste utgave</button><button type="button" className="secondary" disabled={busy} onClick={()=>{const next={...detail.record,requestId:crypto.randomUUID()};if(cached?.id===next.id){try{window.localStorage.removeItem(executionDraftKey(userId,companyId,kind));}catch{setError('Den lokale kladden kunne ikke fjernes. Prøv igjen før du bytter utgave.');return;}setCached(null);}editorRef.current=next;setEditor(next);setDirty(false);setConfirmed(false);setIssues([]);setError('');setNotice('Den lagrede utgaven er åpnet.');setIssues([]);setConfirmed(false);clearLocal();}}>Bruk den lagrede utgaven</button></div>}
    <fieldset className="ks-execution-fields" disabled={busy||readOnly}>
     <Field label="Navn" maxLength={160} value={c.title} onChange={v=>change({...c,title:v})}/><Field label="Arbeidssted / område" field="workplace" maxLength={600} value={c.workplace} onChange={v=>change({...c,workplace:v})}/><Field label="Dato for gjennomføring" field="planned_on" type="date" value={c.planned_on} onChange={v=>change({...c,planned_on:v})}/>
     <Member label="Ansvarlig for gjennomføringen" field="responsible_id" members={members} value={c.responsible_id} readOnly={readOnly} identity={editor.responsible_identity} onChange={v=>change({...c,responsible_id:v})}/>
     <ProjectChoice choices={jobChoices} projectId={editor.project_id} projectName={editor.project_name} fixed={editor.revision>0||readOnly} onSelect={value=>cache({...editor,project_id:value,requestId:crypto.randomUUID()})}/><Field label="Ekstern referanse (valgfritt)" maxLength={600} value={c.reference} onChange={v=>change({...c,reference:v})}/><Field label="Rutiner / utgaver som brukes" multiline maxLength={4000} value={c.routines} hint="Oppgi for eksempel R-012 og versjon 3. Bruk rutinene som er relevante for den konkrete jobben." onChange={v=>change({...c,routines:v})}/><Field label="Deltakere og medvirkning" field="participants" multiline value={c.participants} hint="Oppgi navn, roller og hvordan ansatte og verneombud har bidratt." onChange={v=>change({...c,participants:v})}/>
     {isRound?<>
      {!editor.revision&&<label className="ks-field"><span>Hent publisert sjekkliste (valgfritt)</span><select value={editor.template_version_id||''} onChange={e=>{const v=data.templates.find(v=>v.id===e.target.value);if(Object.values(c.answers).some(a=>a.status||a.comment||a.photos?.length)&&!window.confirm('Bytte sjekkliste? Svarene i dette utkastet tømmes.'))return;if(!v){cache({...editor,template_version_id:null,requestId:crypto.randomUUID(),content:{...c,points:[newPoint()],answers:{}}});return;}change({...c,title:c.title||v.content.title,points:structuredClone(v.content.points),answers:{}});cache({...editorRef.current,template_version_id:v.id,requestId:crypto.randomUUID()});}}><option value="">Egne sjekkpunkter</option>{editor.template_version_id&&!data.templates.some(v=>v.id===editor.template_version_id)&&<option value={editor.template_version_id}>{editor.template_snapshot?.content?.title||'Tidligere publisert sjekkliste'} · versjon {editor.template_snapshot?.number}</option>}{data.templates.map(v=><option key={v.id} value={v.id}>{v.content.title} · versjon {v.number}</option>)}</select></label>}
      {editor.template_version_id&&<p>Fast malutgave: {editor.template_snapshot?.content?.title||data.templates.find(v=>v.id===editor.template_version_id)?.content.title} · versjon {editor.template_snapshot?.number||data.templates.find(v=>v.id===editor.template_version_id)?.number}. Punktene beholdes slik de ble hentet inn.</p>}
      {!editor.template_version_id&&!readOnly&&<details><summary>Forslag til kontrollpunkter</summary><p>Velg relevante temaer og tilpass punktene. Forslagene er ingen ferdig kontroll av arbeidsstedet.</p>{ROUND_SUGGESTIONS.map(title=><button type="button" className="secondary" key={title} disabled={c.points.length>=100} onClick={()=>change({...c,points:[...c.points,{...newPoint(),title}]})}>Legg til: {title}</button>)}</details>}
      {c.points.map((p,i)=>{const a=c.answers[p.id]||{};return <details className="ks-execution-point" key={p.id} ><summary>{i+1}. {p.title||'Nytt sjekkpunkt'} · {{ok:'OK',deviation:'Avvik',na:'Ikke aktuelt'}[a.status]||'Ubesvart'}</summary>{editor.template_version_id?<><h4>{p.title}</h4><p>{p.guidance}</p></>:<><Field label="Tekst for sjekkpunktet" field={'point-'+p.id} maxLength={600} value={p.title} onChange={v=>updatePoint(p.id,'title',v)}/><Field label="Hjelpetekst" multiline maxLength={2000} value={p.guidance} onChange={v=>updatePoint(p.id,'guidance',v)}/><div className="ks-options"><label><input type="checkbox" checked={p.comment_required} onChange={e=>updatePoint(p.id,'comment_required',e.target.checked)}/>Kommentar påkrevd</label><label><input type="checkbox" checked={p.image_required} onChange={e=>updatePoint(p.id,'image_required',e.target.checked)}/>Bilde påkrevd</label></div></>}
       <label className="ks-field"><span>Svar</span><select data-execution-field={'answer-'+p.id} value={a.status||''} onChange={e=>answer(p.id,'status',e.target.value)}><option value="">Velg svar</option><option value="ok">OK</option><option value="deviation">Avvik</option><option value="na">Ikke aktuelt</option></select></label><Field label="Kommentar / begrunnelse" field={'comment-'+p.id} multiline value={a.comment} onChange={v=>answer(p.id,'comment',v)}/>
       {a.status==='deviation'&&<div className="ks-execution-followup"><p>Ved fullføring opprettes én sak i Avvik/RUH. Fullføring av kontrollen lukker ikke saken.</p><Member label="Ansvarlig for retting" field={'owner-'+p.id} members={members} value={a.responsible_id} readOnly={readOnly} identity={a.responsible_identity} onChange={v=>answer(p.id,'responsible_id',v)}/><Field label="Frist for retting" type="date" value={a.due_on} onChange={v=>answer(p.id,'due_on',v)}/></div>}
       <label className="ks-field"><span>Bilder (inntil tre)</span><input data-execution-field={'photo-'+p.id} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const files=[...e.target.files];e.target.value='';upload(p.id,files);}}/></label><div className="ks-execution-photos">{(a.photos||[]).map(photo=><figure key={photo.id}><img src={photo.data} alt={`Dokumentasjon til sjekkpunkt ${i+1}`}/>{!readOnly&&<button type="button" className="secondary" onClick={()=>answer(p.id,'photos',a.photos.filter(x=>x.id!==photo.id))}>Fjern bilde</button>}</figure>)}</div>
       {!editor.template_version_id&&!readOnly&&<button type="button" className="secondary" disabled={c.points.length===1} onClick={()=>change({...c,points:c.points.filter(x=>x.id!==p.id),answers:Object.fromEntries(Object.entries(c.answers).filter(([id])=>id!==p.id))})}>Fjern sjekkpunkt</button>}
      </details>;})}{!editor.template_version_id&&!readOnly&&<button type="button" className="secondary" disabled={c.points.length>=100} onClick={()=>change({...c,points:[...c.points,newPoint()]})}>Legg til eget sjekkpunkt</button>}
     </>:<>
      <Field label="Vurderingsgrunnlag og skala 1–5" field="basis" multiline value={c.basis} hint="Beskriv jobben, kunnskapsgrunnlaget, tidsrommet og hva nivåene for sannsynlighet og konsekvens betyr her. 5×5 er valgt vurderingsmodell, ikke et universelt lovkrav." onChange={v=>change({...c,basis:v})}/><details><summary>Firmaets grenser og krav til aksept</summary><Field label="Øvre grense for lav score" type="number" value={c.acceptance.low_max} onChange={v=>change({...c,acceptance:{...c.acceptance,low_max:v,confirmed:false}})}/><Field label="Øvre grense for moderat score" type="number" value={c.acceptance.medium_max} onChange={v=>change({...c,acceptance:{...c.acceptance,medium_max:v,confirmed:false}})}/><Field label="Hva krever firmaet før risiko kan aksepteres?" field="criteria" multiline value={c.acceptance.description} maxLength={2000} onChange={v=>change({...c,acceptance:{...c.acceptance,description:v,confirmed:false}})}/><label><input type="checkbox" checked={c.acceptance.confirmed} onChange={e=>change({...c,acceptance:{...c.acceptance,confirmed:e.target.checked}})}/>Grensene og kravene er vurdert for denne jobben.</label></details><Matrix acceptance={c.acceptance}/>
      {c.risks.map((r,i)=><details className="ks-execution-point" key={r.id}><summary>{i+1}. {r.hazard||'Ny fare'} · før {riskScore(r.probability_before,r.consequence_before)??'–'} / etter {riskScore(r.probability_after,r.consequence_after)??'–'}</summary>{[['activity','Arbeidsoppgave'],['hazard','Fare / uønsket hendelse'],['consequence','Mulig konsekvens'],['existing_measures','Tiltak som allerede er på plass']].map(([key,name])=><Field key={key} label={name} field={r.id+'-'+key} multiline value={r[key]} onChange={v=>updateRisk(r.id,key,v)}/>)}
       {['before','after'].map(phase=><div className="ks-risk-phase" key={phase}><h4>{phase==='before'?'Risiko før nye tiltak':'Risiko etter nye tiltak'}</h4>{phase==='after'&&<Field label="Nye tiltak som skal gjennomføres" field={r.id+'-planned_measures'} multiline value={r.planned_measures} onChange={v=>updateRisk(r.id,'planned_measures',v)}/>}{[['probability','Sannsynlighet'],['consequence','Konsekvens']].map(([key,name])=><label className="ks-field" key={key}><span>{name} (1–5)</span><select data-execution-field={r.id+'-'+key+'_'+phase} value={r[key+'_'+phase]??''} onChange={e=>updateRisk(r.id,key+'_'+phase,e.target.value)}><option value="">Velg nivå</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n}</option>)}</select></label>)}<Score label={phase==='before'?'Før tiltak':'Etter tiltak'} p={r['probability_'+phase]} c={r['consequence_'+phase]} acceptance={c.acceptance} planned={phase==='after'&&r.effect_status!=='verified'}/></div>)}
       <Member label="Tiltaksansvarlig" field={r.id+'-owner_id'} members={members} value={r.owner_id} readOnly={readOnly} identity={r.owner_identity} onChange={v=>updateRisk(r.id,'owner_id',v)}/><Field label="Frist for tiltak" type="date" value={r.due_on} onChange={v=>updateRisk(r.id,'due_on',v)}/><Field label="Hvordan og når kontrolleres tiltakene?" field={r.id+'-follow_up'} multiline value={r.follow_up} onChange={v=>updateRisk(r.id,'follow_up',v)}/><label className="ks-field"><span>Grunnlaget for risiko etter tiltak</span><select value={r.effect_status} onChange={e=>updateRisk(r.id,'effect_status',e.target.value)}><option value="planned">Forventet effekt – tiltak er planlagt</option><option value="verified">Tiltak er utført og effekten kontrollert</option></select></label>{r.effect_status==='verified'&&<Field label="Dato for kontroll av utførte tiltak" field={r.id+'-verified_on'} type="date" value={r.verified_on} onChange={v=>updateRisk(r.id,'verified_on',v)}/>}<label className="ks-field"><span>Beslutning</span><select data-execution-field={r.id+'-decision'} value={r.decision} onChange={e=>updateRisk(r.id,'decision',e.target.value)}><option value="">Velg beslutning</option><option value="needs_action">Videre tiltak kreves</option><option value="stop">Arbeidet må stanses / utsettes</option><option value="accepted">Gjenværende risiko aksepteres etter kontroll</option></select></label><Field label="Begrunnelse for vurdering og beslutning" field={r.id+'-reason'} multiline value={r.reason} onChange={v=>updateRisk(r.id,'reason',v)}/><p className="ks-field-hint">Forventet lav score dokumenterer ikke at tiltak er gjennomført. «Aksepteres» krever kontrollert effekt og en begrunnelse. Høy gjenværende risiko må ha videre tiltak eller stans.</p>{!readOnly&&<button type="button" className="secondary" disabled={c.risks.length===1} onClick={()=>change({...c,risks:c.risks.filter(x=>x.id!==r.id)})}>Fjern fare</button>}</details>)}{!readOnly&&<button type="button" className="secondary" disabled={c.risks.length>=100} onClick={()=>change({...c,risks:[...c.risks,newRisk()]})}>Legg til fare</button>}
     </>}
     <Field label="Gjennomgang og videre oppfølging" field="review" multiline value={c.review} hint="Beskriv hva som ble gjennomgått, og hvordan tiltak og endringer følges opp. Fullført betyr at dokumentasjonen er ferdig; tiltak og avvik kan fortsatt stå åpne." onChange={v=>change({...c,review:v})}/>
    </fieldset>
    {detail?.links?.length>0&&<div className="ks-card"><h4>Oppfølging av kontrollavvik nå</h4>{detail.links.map(l=><p key={l.point_id}>{l.point_title}: {l.case?l.case.status==='closed'?`Lukket · ${formatDeviationDateTime(l.case.closed_at)}`:'Åpent – følges opp i Avvik/RUH':'Saken er opprettet. Ansvarlig og firmaets KS/HMS-leder følger den opp.'}</p>)}</div>}
    {readOnly?<button type="button" disabled={busy} onClick={repeat}>{isRound?'Start ny gjennomføring fra listen':'Ny vurdering med samme farer'}</button>:<><label className="ks-options"><input data-execution-field="confirmation" type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{EXECUTION_STATEMENT}</label><p className="ks-field-hint">Bare den valgte ansvarlige kan fullføre med sin egen bekreftelse.</p><div className="ks-execution-actions"><button type="button" className="secondary" disabled={busy||conflict} onClick={()=>save('save')}>Lagre utkast</button><button type="button" disabled={busy||conflict} onClick={()=>save('complete')}>{isRound?'Kontroll fullført':'Vurdering fullført'}</button></div></>}
    <p className="ks-field-hint"><a href="https://www.arbeidstilsynet.no/hms/risikovurdering/" target="_blank" rel="noreferrer">Arbeidstilsynets veiledning om risikovurdering og medvirkning</a></p>
   </div>
  </DeviationDialog>}
 </div>;
}
