-- Synthetic fixture only. No real rows, HTTP or email. Entire scenario rolls back.
begin;
set local statement_timeout='12s';
set local lock_timeout='2s';
do $$ declare c uuid:=gen_random_uuid(); u uuid; sys uuid; kind text; pid uuid:=gen_random_uuid(); begin
 insert into public.sales_company_scopes(id,normalized_name,display_name) values(c,public.sales_normalize_company_name('SJA QA '||c),'SJA QA '||c);
 perform set_config('ks.sja.company',c::text,true);
 select id into sys from public.profiles where system_role='systemadmin' and approved and not coalesce(deactivated,false) limit 1;assert sys is not null;
 perform set_config('ks.sja.sys',sys::text,true);
 foreach kind in array array['admin','creator','leader','colleague','without'] loop
  u:=gen_random_uuid();perform set_config('ks.sja.'||kind,u::text,true);
  insert into auth.users(id,aud,role,email,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values(u,'authenticated','authenticated','sja-qa-'||u||'@example.invalid',now(),now(),'{}',jsonb_build_object('full_name','SJA QA '||kind));
  insert into public.profiles(id,email,company_name,approved,deactivated,role,company_role) values(u,'sja-qa-'||u||'@example.invalid','SJA QA '||c,true,false,case when kind='admin' then 'admin' else 'member' end,case when kind='admin' then 'firmaadmin' else 'ansatt' end)
  on conflict(id) do update set company_name=excluded.company_name,approved=true,deactivated=false,role=excluded.role,company_role=excluded.company_role,system_role=null;
  insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(c,u,true,case when kind='admin' then 'firmaadmin' else 'ansatt' end) on conflict(company_id,user_id) do update set workspace_role=excluded.workspace_role;
  insert into public.user_active_company_scope(user_id,company_id) values(u,c) on conflict(user_id) do update set company_id=excluded.company_id;
  insert into public.user_module_access(user_id,module_key) values(u,'projects') on conflict do nothing;
 end loop;
 perform set_config('ks.sja.project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.creator')::uuid,c,'SJA QA unrelated project','{"project":{"projectName":"QA","projectDeviations":[{"id":"unchanged","status":"Åpent"}]},"checklist":{"Point":{"status":"Ok","comment":"keep"}},"overtagelse":{"signKunde":"keep"}}');
 perform set_config('ks.sja.project.data',(select data::text from public.projects where id=pid),true);
 -- Extra project fixtures prove that IDs, not typed references, determine linkage.
 pid:=gen_random_uuid();perform set_config('ks.sja.other_project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.creator')::uuid,c,'SJA QA other project','{"project":{"projectName":"Other QA project"}}');
 u:=gen_random_uuid();insert into public.sales_company_scopes(id,normalized_name,display_name) values(u,public.sales_normalize_company_name('SJA foreign QA '||u),'SJA foreign QA '||u);
 insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(u,current_setting('ks.sja.without')::uuid,false,'ansatt');
 pid:=gen_random_uuid();perform set_config('ks.sja.foreign_project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.without')::uuid,u,'Foreign QA project','{"project":{"projectName":"Foreign QA project"}}');
end $$;
set local role authenticated;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; a uuid:=current_setting('ks.sja.admin')::uuid; creator uuid:=current_setting('ks.sja.creator')::uuid; leader uuid:=current_setting('ks.sja.leader')::uuid; colleague uuid:=current_setting('ks.sja.colleague')::uuid;
 id uuid:=gen_random_uuid();req uuid:=gen_random_uuid();sign_req uuid:=gen_random_uuid();content_data jsonb;payload jsonb;sign_payload jsonb;r jsonb;again jsonb;state jsonb;n integer:=0;
 statement_value text:='Jeg har gjennomgått denne SJA-en sammen med deltakerne. Arbeidsoppgaven, farene, tiltakene og beredskapen er vurdert for forholdene på stedet. Nødvendige tiltak er kontrollert før arbeidet starter. Ved endringer eller uavklart risiko stanser vi og vurderer arbeidet på nytt.';
begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.sys'),true);perform public.kshms_activate(c,true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',creator,'role','reader','enabled',true));
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',leader,'role','reader','enabled',true));
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',colleague,'role','reader','enabled',true));
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.without'),true);
 begin perform public.kshms_sja_state(c);raise exception 'No-grant user read SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 state:=public.kshms_sja_state(c);assert jsonb_array_length(state->'members')=4,'Incorrect active internal members';n:=n+1;
 content_data:=jsonb_build_object('title','QA konkret jobb','leader_id',leader,'steps',jsonb_build_array(jsonb_build_object('id',gen_random_uuid())),'participants',jsonb_build_array(jsonb_build_object('id',gen_random_uuid())));
 payload:=jsonb_build_object('id',id,'revision',0,'content',content_data);
 r:=public.kshms_sja_command(c,'save',req,payload);assert r->'sja'->>'status'='draft' and r->'sja'->>'revision'='1','Partial draft not saved';n:=n+1;
 assert r->'sja'->'content'->>'task'='' and r->'sja'->'content'->>'reviewed_on'='' and r->'sja'->>'signed_by' is null,'Draft filled or signed itself';n:=n+1;
 again:=public.kshms_sja_command(c,'save',req,payload);assert again=r,'Lost response retry changed the saved draft';n:=n+1;
 begin perform public.kshms_sja_command(c,'save',req,jsonb_set(payload,'{content,title}','"Different"'));raise exception 'Reused request accepted different content';exception when serialization_failure then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',colleague::text,true);
 assert public.kshms_sja_state(c)->>'total'='0','Another employee saw a private draft';n:=n+1;
 begin perform public.kshms_sja_detail(c,id);raise exception 'Unassigned reader saw draft details';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(payload,'{revision}','1'));raise exception 'Unassigned reader edited draft';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',leader::text,true);
 assert public.kshms_sja_state(c)->>'total'='1','Assigned leader did not receive draft';n:=n+1;
 content_data:=(r->'sja'->'content')||jsonb_build_object('workplace','QA arbeidssted','task','QA oppgave','planned_on','2026-10-08','reviewed_on','2026-10-07','routines','Firmaets relevante rutine','equipment','Avklart arbeidsutstyr','ppe','Vurdert verneutstyr','emergency','QA varsling og førstehjelp','stop_conditions','Stans ved endrede forhold','communication','Gjennomgått med arbeidslaget');
 content_data:=jsonb_set(content_data,'{steps}',jsonb_build_array((content_data->'steps'->0)||jsonb_build_object('activity','QA arbeidstrinn','hazard','QA fare','consequence','QA konsekvens','measures','QA tiltak','owner','QA leder','check','QA kontroll før start')));
 content_data:=jsonb_set(content_data,'{participants}',jsonb_build_array((content_data->'participants'->0)||jsonb_build_object('name','QA deltaker','role','Utførende','involvement','Gjennomgikk arbeidssted og tiltak')));
 payload:=jsonb_build_object('id',id,'revision',1,'content',content_data);
 r:=public.kshms_sja_command(c,'save',gen_random_uuid(),payload);assert r->'sja'->>'revision'='2','Assigned leader could not save';n:=n+1;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),payload);raise exception 'Stale draft overwrote the leader';exception when serialization_failure then n:=n+1;end;
 assert public.kshms_sja_detail(c,id)->'sja'->'content'->>'task'='QA oppgave','Stale save erased task';n:=n+1;
 sign_payload:=jsonb_build_object('id',id,'revision',2,'content',content_data,'statement',statement_value,'prepared',true,'signed_identity',jsonb_build_object('id',creator,'name','Spoofed'));
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),sign_payload);raise exception 'Creator signed for the selected leader';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),sign_payload);raise exception 'Admin signed for the selected leader';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',leader::text,true);
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_set(sign_payload,'{prepared}','false'));raise exception 'Unchecked signature accepted';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_set(sign_payload,'{statement}','"Wrong statement"'));raise exception 'Wrong statement accepted';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_set(sign_payload,'{content,steps,0,hazard}',to_jsonb(E'\t\n'::text)));raise exception 'Blank hazard signed';exception when raise_exception then if sqlerrm='Blank hazard signed' then raise;end if;n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(sign_payload,'{content,planned_on}','"2026-02-30"'));raise exception 'Invalid date accepted';exception when datetime_field_overflow then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(sign_payload,'{content,steps,0,measures}','true'));raise exception 'Boolean measure accepted';exception when raise_exception then if sqlerrm='Boolean measure accepted' then raise;end if;n:=n+1;end;
 r:=public.kshms_sja_command(c,'sign',sign_req,sign_payload);
 assert r->'sja'->>'status'='signed' and r->'sja'->>'signed_by'=leader::text and r->'sja'->'signed_identity'->>'id'=leader::text and r->'sja'->'signed_identity'->>'name'='SJA QA leader' and r->'sja'->>'signed_at' is not null,'Signer identity not server-derived';n:=n+1;
 assert r->'sja'->>'statement'=statement_value and r->'sja'->'content'->'participants'->0->>'involvement'='Gjennomgikk arbeidssted og tiltak','Medvirkning/statement lost';n:=n+1;
 again:=public.kshms_sja_command(c,'sign',sign_req,sign_payload);assert again=r,'Signature retry changed signed record';n:=n+1;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(sign_payload,'{content,task}','"erase"'));raise exception 'Signed SJA edited';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),sign_payload);raise exception 'Admin edited signed SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',colleague::text,true);
 assert public.kshms_sja_state(c,'konkret','signed')->>'total'='1' and public.kshms_sja_detail(c,id)->'sja'->>'signed_by'=leader::text,'Employee cannot read completed job documentation';n:=n+1;
 assert public.kshms_sja_state(c,'no match')->>'total'='0','SJA search ignored query';n:=n+1;
 begin perform public.kshms_sja_command(c,'sign',sign_req,sign_payload);raise exception 'Other actor replayed a signature';exception when serialization_failure then n:=n+1;end;
 begin perform public.kshms_sja_state(gen_random_uuid());raise exception 'Foreign company read';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.kshms_command(c,'access',jsonb_build_object('user_id',leader,'role','reader','enabled',false));
 perform set_config('request.jwt.claim.sub',leader::text,true);
 begin perform public.kshms_sja_detail(c,id);raise exception 'Revoked leader read SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.sja.id',id::text,true);perform set_config('ks.sja.count',n::text,true);
end $$;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; creator uuid:=current_setting('ks.sja.creator')::uuid; pid uuid:=current_setting('ks.sja.project')::uuid; other_pid uuid:=current_setting('ks.sja.other_project')::uuid;
 id uuid:=gen_random_uuid(); req uuid:=gen_random_uuid(); sign_req uuid:=gen_random_uuid(); payload jsonb; original jsonb; r jsonb; state jsonb; n integer:=current_setting('ks.sja.count')::integer; begin
 perform set_config('request.jwt.claim.sub',creator::text,true);
 original:=public.kshms_sja_detail(c,current_setting('ks.sja.id')::uuid)->'sja';
 payload:=jsonb_build_object('id',id,'revision',0,'project_id',pid,'content',(original->'content')||jsonb_build_object('title','QA prosjektkoblet jobb','project_reference','','leader_id',creator));
 r:=public.kshms_sja_command(c,'save',req,payload);assert r->'sja'->>'project_id'=pid::text,'Project ID not saved';n:=n+1;
 assert public.kshms_sja_command(c,'save',req,payload)=r,'Project retry created or moved a job';n:=n+1;
 state:=public.kshms_project_sja_state(c,pid);assert state->'context'->>'project_id'=pid::text and state->>'total'='1' and state->'items'->0->>'id'=id::text,'Project list includes another job';n:=n+1;
 assert public.kshms_project_sja_state(c,other_pid)->>'total'='0','Other project inherited SJA';n:=n+1;
 assert public.kshms_sja_state(c,'prosjektkoblet')->>'total'='1','Project job missing in global KS list';n:=n+1;
 assert public.kshms_sja_detail(c,id)->'sja'->>'project_name'='QA','Project name not read from project';n:=n+1;
 payload:=jsonb_set(payload,'{revision}','1');
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(payload,'{project_id}',to_jsonb(other_pid)));raise exception 'Existing SJA moved to another project';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(payload,'{project_id}','null'));raise exception 'Project link silently removed';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(jsonb_set(payload,'{id}',to_jsonb(gen_random_uuid())),'{project_id}',to_jsonb(current_setting('ks.sja.foreign_project')::uuid))||jsonb_build_object('revision',0));raise exception 'Cross-company project accepted';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.colleague'),true);
 begin perform public.kshms_project_sja_state(c,pid);raise exception 'Employee without project rights opened project SJA';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_detail(c,id);raise exception 'Employee without project rights read details';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.without'),true);
 begin perform public.kshms_project_sja_state(c,pid);raise exception 'Employee without KS grant read project SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 r:=public.kshms_sja_command(c,'save',gen_random_uuid(),payload-'project_id');assert r->'sja'->>'project_id'=pid::text,'Older client lost existing link';n:=n+1;
 payload:=jsonb_set(payload,'{revision}',to_jsonb((r->'sja'->>'revision')::bigint))||jsonb_build_object('prepared',true,'statement',original->>'statement');
 r:=public.kshms_sja_command(c,'sign',sign_req,payload);assert r->'sja'->>'status'='signed' and r->'sja'->>'project_id'=pid::text and r->'sja'->>'signed_by'=creator::text,'Own project signature or linkage missing';n:=n+1;
 assert public.kshms_sja_command(c,'sign',sign_req,payload)=r,'Project signature retry changed snapshot';n:=n+1;
 state:=public.kshms_project_sja_state(c,pid,'','signed');assert state->>'total'='1' and state->'items'->0->>'project_id'=pid::text,'Signed history no longer follows project';n:=n+1;
 perform set_config('ks.sja.project_sja_id',id::text,true);perform set_config('ks.sja.project_sign_request',sign_req::text,true);perform set_config('ks.sja.project_sign_payload',payload::text,true);perform set_config('ks.sja.count',n::text,true);
end $$;
reset role;
do $$ declare pid uuid:=current_setting('ks.sja.other_project')::uuid; begin update public.projects set locked=true where id=pid;end $$;
set local role authenticated;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; pid uuid:=current_setting('ks.sja.other_project')::uuid; payload jsonb; n integer:=current_setting('ks.sja.count')::integer; begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.creator'),true);
 assert (public.kshms_project_sja_state(c,pid)->'project'->>'locked')::boolean,'Locked project not reported';n:=n+1;
 payload:=jsonb_build_object('id',gen_random_uuid(),'revision',0,'project_id',pid,'content',public.kshms_sja_detail(c,current_setting('ks.sja.id')::uuid)->'sja'->'content');
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),payload);raise exception 'New SJA written to locked project';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.sja.count',n::text,true);
end $$;
reset role;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid;n integer:=current_setting('ks.sja.count')::integer;begin
 update public.projects set user_id=current_setting('ks.sja.admin')::uuid where id=current_setting('ks.sja.project')::uuid;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.creator'),true);
 begin perform public.kshms_sja_command(c,'sign',current_setting('ks.sja.project_sign_request')::uuid,current_setting('ks.sja.project_sign_payload')::jsonb);raise exception 'Receipt leaked project after access removal';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_detail(c,current_setting('ks.sja.project_sja_id')::uuid);raise exception 'Signed project history bypassed revoked project access';exception when insufficient_privilege then n:=n+1;end;
 assert public.kshms_sja_state(c,'prosjektkoblet')->>'total'='0','Global list leaked a project without current project access';n:=n+1;
 update public.projects set user_id=current_setting('ks.sja.creator')::uuid where id=current_setting('ks.sja.project')::uuid;
 assert not has_function_privilege('anon','public.kshms_project_sja_state(uuid,uuid,text,text)','execute') and not has_function_privilege('authenticated','kshms_private.sja_state(uuid,text,text,uuid)','execute'),'New RPC/helper ACL exposed';n:=n+1;
 perform set_config('ks.sja.count',n::text,true);
end $$;
set local role authenticated;
reset role;
-- Additional checks use the SJA script's synthetic company and roll back with it.
set local role authenticated;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; a uuid:=current_setting('ks.sja.admin')::uuid; u uuid:=current_setting('ks.sja.creator')::uuid; pid uuid:=current_setting('ks.sja.project')::uuid;
 r jsonb; second jsonb; third jsonb; fourth jsonb; v1 jsonb; v2 jsonb; state jsonb; incident jsonb; retry jsonb; payload jsonb; req uuid:=gen_random_uuid(); case_id uuid; n integer:=current_setting('ks.sja.count')::integer;
 draft jsonb:=jsonb_build_object('title','QA støv ved mur og flis','chapter','HMSK','goal','QA mål','responsibility','QA ansvar','procedure','QA metode for jobben','documentation','QA dokumentasjon','confirmation','QA gjennomgang','references',jsonb_build_array());
begin
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',u,'role','responsible','enabled',true));
 perform public.kshms_command(c,'settings',jsonb_build_object('revision',0,'trades',jsonb_build_array('mur_flis','tomrer'),'responsible_user_id',u));
 r:=public.kshms_command(c,'save',jsonb_build_object('draft',draft));
 second:=public.kshms_command(c,'save',jsonb_build_object('draft',draft||jsonb_build_object('title','QA arkivert rutine')));
 third:=public.kshms_command(c,'save',jsonb_build_object('draft',draft||jsonb_build_object('title','QA kun utkast')));
 assert r->>'reference_number'='1' and second->>'reference_number'='2' and third->>'reference_number'='3','Routine sequence is not company-specific';n:=n+1;
 assert jsonb_array_length(public.kshms_job_choices(c)->'routines')=0,'Unpublished drafts leaked into job choices';n:=n+1;
 v1:=public.kshms_command(c,'publish',jsonb_build_object('id',r->>'id','revision',r->>'revision','change_summary','QA første utgave'));
 r:=public.kshms_command(c,'save',jsonb_build_object('id',r->>'id','revision',2,'draft',draft||jsonb_build_object('procedure','QA ny godkjent arbeidsmetode')));
 assert r->>'reference_number'='1','Editing changed stable routine number';n:=n+1;
 v2:=public.kshms_command(c,'publish',jsonb_build_object('id',r->>'id','revision',r->>'revision','change_summary','QA andre utgave'));
 perform public.kshms_command(c,'publish',jsonb_build_object('id',second->>'id','revision',second->>'revision','change_summary','QA arkivtest utgave'));
 perform public.kshms_command(c,'archive',jsonb_build_object('id',second->>'id','revision',2));
 fourth:=public.kshms_command(c,'save',jsonb_build_object('draft',draft||jsonb_build_object('title','QA neste nye rutine')));
 assert fourth->>'reference_number'='4','Archive reused a routine number';n:=n+1;
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',u,'role','reader','enabled',true));
 perform set_config('request.jwt.claim.sub',u::text,true);
 state:=public.kshms_job_choices(c);
 assert state->'context'->>'user_id'=u::text and state->'context'->>'company_id'=c::text,'Choices lost actor/company context';n:=n+1;
 assert jsonb_array_length(state->'projects')=1 and state->'projects'->0->>'id'=pid::text,'Inactive, foreign or inaccessible project leaked';n:=n+1;
 assert public.kshms_job_choices(c,'no matching project')->>'project_total'='0','Project search did not filter real rows';n:=n+1;
 assert jsonb_array_length(state->'routines')=1 and state->'routines'->0->>'id'=v2->>'id' and state->'routines'->0->>'reference_number'='1' and state->'routines'->0->>'number'='2','Wrong edition or archived/draft routine offered';n:=n+1;
 assert public.kshms_get_state(c)->'routines'->0 ? 'reference_number','Reader handbook missing routine number';n:=n+1;
 assert exists(select 1 from jsonb_array_elements(public.kshms_get_state(c)->'versions') v where v->>'id'=v1->>'id' and v->>'content_hash'=v1->>'content_hash' and v->'content'=v1->'content'),'Numbering changed published content';n:=n+1;
 payload:=jsonb_build_object('request_id',req,'title','QA RUH ved fliskapping','event','QA støv observert ved arbeidsstedet','category','ruh','responsible_id',u,'due_on',current_date+3,'source_kind','company','project_id',pid,'project_reference','Egen referanse beholdes','routines','R-001 – QA støv ved mur og flis (versjon 2)','immediate_action','Arbeid stanset og område sikret');
 incident:=public.kshms_deviation_command(c,'create',payload);case_id:=(incident->>'id')::uuid;
 assert incident->>'category'='ruh' and incident->>'project_id'=pid::text and incident->>'routines'=payload->>'routines' and incident->>'project_reference'=payload->>'project_reference','RUH lost project or routine/reference';n:=n+1;
 retry:=public.kshms_deviation_command(c,'create',payload);assert retry=incident,'RUH retry duplicated or changed case';n:=n+1;
 state:=public.kshms_project_ruh_state(c,pid);
 assert state->'context'->>'project_id'=pid::text and state->'cases'->0->>'id'=case_id::text and state->'counts'->>'open'='1','Project RUH list missing exact case';n:=n+1;
 assert public.kshms_project_ruh_state(c,current_setting('ks.sja.other_project')::uuid)->'counts'->>'open'='0','RUH follows wrong project';n:=n+1;
 assert exists(select 1 from jsonb_array_elements(public.kshms_deviation_tasks(c)->'items') i where i->>'id'=case_id::text),'Responsible has no persistent RUH task';n:=n+1;
 retry:=public.kshms_deviation_command(c,'create',(payload-'project_id')||jsonb_build_object('request_id',gen_random_uuid(),'title','QA ekstern RUH','project_reference','Ekstern ordre 123'));
 assert retry->'project_id'='null'::jsonb and retry->>'project_reference'='Ekstern ordre 123','External RUH gained project or lost manual reference';n:=n+1;
 begin perform public.kshms_deviation_command(c,'create',payload||jsonb_build_object('request_id',gen_random_uuid(),'project_id',current_setting('ks.sja.foreign_project')::uuid));raise exception 'Foreign project accepted for RUH';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_deviation_command(c,'create',payload||jsonb_build_object('request_id',gen_random_uuid(),'project_id',current_setting('ks.sja.other_project')::uuid));raise exception 'Locked project accepted for RUH';exception when raise_exception then if sqlerrm='Locked project accepted for RUH' then raise;end if;n:=n+1;end;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.colleague'),true);
 assert public.kshms_job_choices(c)->>'project_total'='0','Reader gained another employee project';n:=n+1;
 begin perform public.kshms_project_ruh_state(c,pid);raise exception 'Reader without project access read RUH';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.without'),true);
 begin perform public.kshms_job_choices(c);raise exception 'No KS/HMS grant read choices';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_ruh_state(c,pid);raise exception 'No KS/HMS grant read RUH';exception when insufficient_privilege then n:=n+1;end;
 payload:=jsonb_build_object('id',case_id,'revision',1,'controlled',true,'cause','OK','improvement_action','OK','control_note','OK');
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.kshms_deviation_command(c,'close',payload);raise exception 'Admin closed someone else RUH';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',u::text,true);
 incident:=public.kshms_deviation_command(c,'close',payload);
 assert incident->>'closed_by'=u::text and incident->>'status'='closed' and incident->>'routines'='R-001 – QA støv ved mur og flis (versjon 2)','Responsible closure lost history/reference';n:=n+1;
 assert public.kshms_project_ruh_state(c,pid,'closed')->'cases'->0->>'id'=case_id::text,'Closed RUH missing from project history';n:=n+1;
 assert jsonb_array_length(public.kshms_deviation_detail(c,case_id)->'events')=2,'RUH retry produced duplicate history';n:=n+1;
 assert not exists(select 1 from jsonb_array_elements(public.kshms_deviation_tasks(c)->'items') i where i->>'id'=case_id::text),'Closed RUH kept responsible task';n:=n+1;
 perform set_config('ks.sja.routine_id',r->>'id',true);perform set_config('ks.sja.routine_v2',v2->>'id',true);perform set_config('ks.sja.ruh_id',case_id::text,true);perform set_config('ks.sja.count',n::text,true);
end $$;
reset role;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; u uuid:=current_setting('ks.sja.creator')::uuid; n integer:=current_setting('ks.sja.count')::integer;begin
 begin update public.kshms_routines set reference_number=99 where id=current_setting('ks.sja.routine_id')::uuid;raise exception 'Routine reference renumbered';exception when insufficient_privilege then n:=n+1;end;
 assert (select count(*) from public.kshms_notification_outbox where deviation_id=current_setting('ks.sja.ruh_id')::uuid)=1,'RUH retry duplicated assignment notification';n:=n+1;
 delete from public.kshms_assignments where version_id=current_setting('ks.sja.routine_v2')::uuid and user_id=u;
 perform set_config('request.jwt.claim.sub',u::text,true);
 assert jsonb_array_length(public.kshms_job_choices(c)->'routines')=0,'Old assignment exposed a new, unassigned edition';n:=n+1;
 assert not has_function_privilege('anon','public.kshms_job_choices(uuid,text)','execute') and not has_function_privilege('anon','public.kshms_project_ruh_state(uuid,uuid,text,text,timestamptz,uuid)','execute'),'Anonymous access to new RPCs';n:=n+1;
 assert not has_table_privilege('authenticated','public.kshms_routines','select') and not has_table_privilege('authenticated','public.kshms_deviations','insert'),'RPC-only table permissions changed';n:=n+1;
 begin update public.projects set company_scope_id=(select company_scope_id from public.projects where id=current_setting('ks.sja.foreign_project')::uuid) where id=current_setting('ks.sja.project')::uuid;raise exception 'Linked safety project moved company';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.sja.count',n::text,true);
end $$;

do $$ declare c uuid:=current_setting('ks.sja.company')::uuid;target_sja uuid:=current_setting('ks.sja.id')::uuid;n integer:=current_setting('ks.sja.count')::integer; begin
 begin update public.kshms_sjas set content='{}' where public.kshms_sjas.id=target_sja;raise exception 'Signed snapshot mutated directly';exception when insufficient_privilege then n:=n+1;end;
 begin delete from public.kshms_sjas where public.kshms_sjas.id=target_sja;raise exception 'Signed snapshot deleted';exception when insufficient_privilege then n:=n+1;end;
 begin
  insert into public.kshms_sjas(id,company_id,content,status,leader_id,created_by,creator_identity,updated_by,signed_by,signed_identity,signed_at,statement)
  select gen_random_uuid(),company_id,content,'signed',null,created_by,creator_identity,updated_by,signed_by,signed_identity,signed_at,statement from public.kshms_sjas where public.kshms_sjas.id=target_sja;
  raise exception 'Signed SJA without selected leader passed its constraint';
 exception when check_violation then n:=n+1;end;
 assert not has_function_privilege('anon','public.kshms_sja_state(uuid,text,text)','execute') and not has_function_privilege('anon','public.kshms_sja_command(uuid,text,uuid,jsonb)','execute');n:=n+1;
 assert not has_table_privilege('authenticated','public.kshms_sjas','select') and not has_table_privilege('authenticated','public.kshms_sja_commands','update');n:=n+1;
 assert (select relrowsecurity from pg_class where oid='public.kshms_sjas'::regclass) and (select relrowsecurity from pg_class where oid='public.kshms_sja_commands'::regclass);n:=n+1;
 assert (select data from public.projects where public.projects.id=current_setting('ks.sja.project')::uuid)=current_setting('ks.sja.project.data')::jsonb,'Existing project/checklist/signature changed';n:=n+1;
 update public.company_module_access set enabled=false where company_id=c and module_key='kshms';
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.admin'),true);
 begin perform public.kshms_sja_state(c);raise exception 'Disabled company exposed SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.sja.count',n::text,true);
end $$;
select 'PASS: '||current_setting('ks.sja.count')||' SJA/RUH access, actual project choices, stable routine references, exact editions, retry/history/regression assertions; all synthetic rows rolled back' as result;
rollback;
