-- Synthetic fixture only. No real rows, HTTP or email. Entire scenario rolls back.
begin;
set local statement_timeout='12s';
set local lock_timeout='2s';
do $$ declare c uuid:=gen_random_uuid(); u uuid; sys uuid; kind text; pid uuid:=gen_random_uuid(); begin
 insert into public.sales_company_scopes(id,normalized_name,display_name) values(c,public.sales_normalize_company_name('SJA QA '||c),'SJA QA '||c);
 perform set_config('ks.sja.company',c::text,true);
 select id into sys from public.profiles where system_role='systemadmin' and approved and not coalesce(deactivated,false) limit 1;assert sys is not null;
 perform set_config('ks.sja.sys',sys::text,true);
 foreach kind in array array['admin','creator','leader','colleague','without'] loop
  u:=gen_random_uuid();perform set_config('ks.sja.'||kind,u::text,true);
  insert into auth.users(id,aud,role,email,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values(u,'authenticated','authenticated','sja-qa-'||u||'@example.invalid',now(),now(),'{}',jsonb_build_object('full_name','SJA QA '||kind));
  insert into public.profiles(id,email,company_name,approved,deactivated,role,company_role) values(u,'sja-qa-'||u||'@example.invalid','SJA QA '||c,true,false,case when kind='admin' then 'admin' else 'member' end,case when kind='admin' then 'firmaadmin' else 'ansatt' end)
  on conflict(id) do update set company_name=excluded.company_name,approved=true,deactivated=false,role=excluded.role,company_role=excluded.company_role,system_role=null;
  insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(c,u,true,case when kind='admin' then 'firmaadmin' else 'ansatt' end) on conflict(company_id,user_id) do update set workspace_role=excluded.workspace_role;
  insert into public.user_active_company_scope(user_id,company_id) values(u,c) on conflict(user_id) do update set company_id=excluded.company_id;
  insert into public.user_module_access(user_id,module_key) values(u,'projects') on conflict do nothing;
 end loop;
 perform set_config('ks.sja.project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.creator')::uuid,c,'SJA QA unrelated project','{"project":{"projectName":"QA","projectDeviations":[{"id":"unchanged","status":"Åpent"}]},"checklist":{"Point":{"status":"Ok","comment":"keep"}},"overtagelse":{"signKunde":"keep"}}');
 perform set_config('ks.sja.project.data',(select data::text from public.projects where id=pid),true);
 -- Extra project fixtures prove that IDs, not typed references, determine linkage.
 pid:=gen_random_uuid();perform set_config('ks.sja.other_project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.creator')::uuid,c,'SJA QA other project','{"project":{"projectName":"Other QA project"}}');
 u:=gen_random_uuid();insert into public.sales_company_scopes(id,normalized_name,display_name) values(u,public.sales_normalize_company_name('SJA foreign QA '||u),'SJA foreign QA '||u);
 insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(u,current_setting('ks.sja.without')::uuid,false,'ansatt');
 pid:=gen_random_uuid();perform set_config('ks.sja.foreign_project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.without')::uuid,u,'Foreign QA project','{"project":{"projectName":"Foreign QA project"}}');
end $$;
set local role authenticated;
do $$ declare
 c uuid:=current_setting('ks.sja.company')::uuid; a uuid:=current_setting('ks.sja.admin')::uuid;
 u uuid:=current_setting('ks.sja.creator')::uuid; leader uuid:=current_setting('ks.sja.creator')::uuid;
 pid uuid:=current_setting('ks.sja.project')::uuid; sid uuid:=gen_random_uuid(); draft uuid:=gen_random_uuid(); other_sja uuid:=gen_random_uuid(); external_sja uuid:=gen_random_uuid();
 rid uuid; quality_id uuid; other_ruh uuid; private_sja uuid:=gen_random_uuid(); private_ruh uuid; content_data jsonb; r jsonb; signed jsonb; incident jsonb; first_snapshot jsonb; state jsonb; k text; n integer:=0;
 statement_value text:='Jeg har gjennomgått denne SJA-en sammen med deltakerne. Arbeidsoppgaven, farene, tiltakene og beredskapen er vurdert for forholdene på stedet. Nødvendige tiltak er kontrollert før arbeidet starter. Ved endringer eller uavklart risiko stanser vi og vurderer arbeidet på nytt.';
begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.sys'),true); perform public.kshms_activate(c,true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 foreach k in array array['creator','leader','colleague'] loop perform public.kshms_command(c,'access',jsonb_build_object('user_id',current_setting('ks.sja.'||k)::uuid,'role','reader','enabled',true)); end loop;
 perform set_config('request.jwt.claim.sub',u::text,true);
 content_data:=jsonb_build_object('title','QA signert prosjekt-SJA','leader_id',leader,'planned_on','2026-10-08','reviewed_on','2026-10-08','routines','R-012 – QA støv ved mur og flis (versjon 3)',
 'steps',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'activity','QA kapping','hazard','QA støv','consequence','QA skade','measures','QA avsug','owner','QA ansvar','check','QA kontroll')),
 'participants',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'name','QA deltaker','role','Flislegger','company','QA ekstern','involvement','QA gjennomgang på stedet')));
 foreach k in array array['workplace','task','equipment','ppe','emergency','stop_conditions','communication'] loop content_data:=content_data||jsonb_build_object(k,'QA vurdert '||k); end loop;
 r:=public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_build_object('id',sid,'project_id',pid,'revision',0,'content',content_data));
 perform set_config('request.jwt.claim.sub',leader::text,true);
 signed:=public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_build_object('id',sid,'project_id',pid,'revision',1,'content',content_data,'prepared',true,'statement',statement_value))->'sja';
 perform set_config('request.jwt.claim.sub',u::text,true);
 perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_build_object('id',draft,'project_id',pid,'revision',0,'content',content_data||jsonb_build_object('title','QA usignert utkast')));
 perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_build_object('id',other_sja,'project_id',current_setting('ks.sja.other_project')::uuid,'revision',0,'content',content_data));
 perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_build_object('id',external_sja,'revision',0,'content',content_data||jsonb_build_object('project_reference',pid)));
 incident:=public.kshms_deviation_command(c,'create',jsonb_build_object('request_id',gen_random_uuid(),'title','QA prosjekt-RUH','event','QA nestenulykke på arbeidsstedet','category','ruh','source_kind','company','project_id',pid,'responsible_id',u,'due_on','2026-10-10','routines','R-012 – QA støv ved mur og flis (versjon 3)','immediate_action','QA sikret området'));
 rid:=(incident->>'id')::uuid;
 r:=public.kshms_deviation_command(c,'create',jsonb_build_object('request_id',gen_random_uuid(),'title','QA kvalitetsavvik','event','QA annet kvalitetsavvik på stedet','category','quality','source_kind','company','project_id',pid,'responsible_id',u,'due_on','2026-10-10')); quality_id:=(r->>'id')::uuid;
 r:=public.kshms_deviation_command(c,'create',jsonb_build_object('request_id',gen_random_uuid(),'title','QA RUH annet prosjekt','event','QA hendelse tilhører et annet prosjekt','category','ruh','source_kind','company','project_id',current_setting('ks.sja.other_project')::uuid,'responsible_id',u,'due_on','2026-10-10')); other_ruh:=(r->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_build_object('id',private_sja,'project_id',pid,'revision',0,'content',content_data||jsonb_build_object('leader_id',a,'title','QA privat admin-utkast')));
 r:=public.kshms_deviation_command(c,'create',jsonb_build_object('request_id',gen_random_uuid(),'title','QA privat admin-RUH','event','QA hendelse som bare admin er involvert i','category','ruh','source_kind','company','project_id',pid,'responsible_id',a,'due_on','2026-10-10')); private_ruh:=(r->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',u::text,true);
 state:=public.kshms_project_report(c,pid);
 assert jsonb_array_length(state#>'{choices,sjas}')=2 and jsonb_array_length(state#>'{choices,ruhs}')=1,'Report choices include external/other project or wrong category';n:=n+1;
 assert state#>>'{context,project_id}'=pid::text and state#>>'{context,user_id}'=u::text,'Report scope missing';n:=n+1;
 state:=public.kshms_project_report(c,pid,array[sid,draft],array[rid]);
 assert state->'sjas'->0=signed,'Signed SJA snapshot rewritten';n:=n+1;
 assert state#>>'{sjas,1,status}'='draft','Draft status lost';n:=n+1;
 assert state#>>'{ruhs,0,routines}'='R-012 – QA støv ved mur og flis (versjon 3)' and state#>>'{ruhs,0,status}'='open','Open RUH/routine snapshot lost';n:=n+1;
 first_snapshot:=state;
 state:=public.kshms_project_report(c,pid,'{}','{}');assert state->'sjas'='[]'::jsonb and state->'ruhs'='[]'::jsonb,'Empty selection includes documents';n:=n+1;
 begin perform public.kshms_project_report(c,pid,array[other_sja],'{}');raise exception 'Other-project SJA exported';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,array[external_sja],'{}');raise exception 'Manual SJA exported via typed reference';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,'{}',array[other_ruh]);raise exception 'Other-project RUH exported';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,'{}',array[quality_id]);raise exception 'Non-RUH case exported';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,array[sid,gen_random_uuid()],array[rid]);raise exception 'Partial report returned';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,current_setting('ks.sja.foreign_project')::uuid);raise exception 'Foreign project choices read';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(gen_random_uuid(),pid);raise exception 'Foreign company read';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,array[sid,sid],'{}');raise exception 'Duplicate IDs accepted';exception when raise_exception then assert sqlerrm like 'Velg inntil%';n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,array[null::uuid],'{}');raise exception 'Null ID accepted';exception when raise_exception then assert sqlerrm like 'Velg inntil%';n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,array_fill(sid,array[101]),'{}');raise exception 'Too many IDs accepted';exception when raise_exception then assert sqlerrm like 'Velg inntil%';n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,null,'{}');raise exception 'Mixed list/export mode accepted';exception when raise_exception then assert sqlerrm='Ugyldig rapportvalg.';n:=n+1;end;
 incident:=public.kshms_deviation_command(c,'close',jsonb_build_object('request_id',gen_random_uuid(),'id',rid,'revision',incident->'revision','cause','QA manglende sikring','improvement_action','QA område sikret og kontrollert','control_note','QA resultatet kontrollert på stedet','controlled',true));
 state:=public.kshms_project_report(c,pid,array[sid],array[rid]);
 assert state->'ruhs'->0=incident and state#>>'{ruhs,0,closed_by}'=u::text and state#>>'{ruhs,0,status}'='closed','Fresh closure/identity missing';n:=n+1;
 assert state->'sjas'->0=signed,'RUH closure changed signed content';n:=n+1;
 assert first_snapshot#>>'{ruhs,0,status}'='open','Snapshot mutated after closure';n:=n+1;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.colleague'),true);
 begin perform public.kshms_project_report(c,pid);raise exception 'Colleague without project access read choices';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',u::text,true);
 state:=public.kshms_project_report(c,pid);assert jsonb_array_length(state#>'{choices,sjas}')=2 and jsonb_array_length(state#>'{choices,ruhs}')=1,'Reader saw private draft/RUH';n:=n+1;
 assert public.kshms_project_report(c,pid,array[sid],'{}')->'sjas'->0=signed,'Reader cannot export visible signed SJA';n:=n+1;
 begin perform public.kshms_project_report(c,pid,array[private_sja],'{}');raise exception 'Private draft exported';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_project_report(c,pid,'{}',array[private_ruh]);raise exception 'Private RUH exported';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.without'),true);
 begin perform public.kshms_project_report(c,pid);raise exception 'User without module read choices';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.report.signed_id',sid::text,true);perform set_config('ks.report.signed',signed::text,true);perform set_config('ks.report.ruh_id',rid::text,true);perform set_config('ks.report.count',n::text,true);
end $$;
reset role;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; pid uuid:=current_setting('ks.sja.project')::uuid; sid uuid:=current_setting('ks.report.signed_id')::uuid; n integer:=current_setting('ks.report.count')::integer;begin
 assert (select data::text from public.projects where id=pid)=current_setting('ks.sja.project.data'),'Report read changed project/checklist/warranty/portal JSON';n:=n+1;
 update public.projects set locked=true where id=pid;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.creator'),true);
 assert public.kshms_project_report(c,pid,array[sid],array[current_setting('ks.report.ruh_id')::uuid])->'sjas'->0=current_setting('ks.report.signed')::jsonb,'Locked-project report denied/changed';n:=n+1;
 update public.profiles set email='changed-qa-'||id||'@example.invalid' where id=current_setting('ks.sja.creator')::uuid;
 assert public.kshms_project_report(c,pid,array[sid],'{}')->'sjas'->0=current_setting('ks.report.signed')::jsonb,'Current profile rewrote frozen signatory';n:=n+1;
 assert not has_function_privilege('anon','public.kshms_project_report(uuid,uuid,uuid[],uuid[])','execute') and has_function_privilege('authenticated','public.kshms_project_report(uuid,uuid,uuid[],uuid[])','execute'),'RPC execute grants incorrect';n:=n+1;
 assert (select prosecdef and proconfig @> array['search_path=""'] from pg_proc where oid='public.kshms_project_report(uuid,uuid,uuid[],uuid[])'::regprocedure),'RPC search path/definer incorrect';n:=n+1;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.admin'),true);
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',current_setting('ks.sja.creator')::uuid,'role','reader','enabled',false));
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.creator'),true);
 begin perform public.kshms_project_report(c,pid,array[sid],'{}');raise exception 'Revoked access exported selected SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.sys'),true);perform public.kshms_activate(c,false);
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.leader'),true);
 begin perform public.kshms_project_report(c,pid,array[sid],'{}');raise exception 'Disabled company module exported';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.kshms_project_report(c,pid);raise exception 'Unauthenticated read';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.report.count',n::text,true);
end $$;
select 'PASS' as result,current_setting('ks.report.count')::integer as report_assertions;
rollback;
