-- Synthetic fixtures only. Never invoke the HTTP sender. All writes roll back.
begin;
set local statement_timeout='25s';
set local lock_timeout='2s';
create function pg_temp.rv_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'REVIEW REMINDER QA: %',label;end if;perform set_config('ks.rv.checks',(coalesce(nullif(current_setting('ks.rv.checks',true),''),'0')::integer+1)::text,true);end$$;
create function pg_temp.rv_reject(query text,code text) returns void language plpgsql as $$declare got text;begin begin execute query;exception when others then get stacked diagnostics got=returned_sqlstate;end;perform pg_temp.rv_assert(got=code,'rejected request with '||code);end$$;
do $$declare c uuid:=gen_random_uuid();sys uuid;u uuid;k text;begin
 insert into public.sales_company_scopes(id,normalized_name,display_name) values(c,public.sales_normalize_company_name('REVIEW REMINDER QA '||c),'REVIEW REMINDER QA '||c);perform set_config('ks.rv.company',c::text,true);
 select id into sys from public.profiles where system_role='systemadmin' and approved and not coalesce(deactivated,false) limit 1;assert sys is not null;perform set_config('ks.rv.sys',sys::text,true);
 foreach k in array array['admin','responsible','reader'] loop
  u:=gen_random_uuid();perform set_config('ks.rv.'||k,u::text,true);
  insert into auth.users(id,aud,role,email,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values(u,'authenticated','authenticated','review-reminder-qa-'||u||'@example.invalid',now(),now(),'{}',jsonb_build_object('full_name','REVIEW REMINDER QA '||k));
  insert into public.profiles(id,email,company_name,approved,deactivated,role,company_role) values(u,'review-reminder-qa-'||u||'@example.invalid','REVIEW REMINDER QA '||c,true,false,case when k='admin' then 'admin' else 'member' end,case when k='admin' then 'firmaadmin' else 'ansatt' end) on conflict(id) do update set company_name=excluded.company_name,approved=true,deactivated=false,role=excluded.role,company_role=excluded.company_role,system_role=null;
  insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(c,u,true,case when k='admin' then 'firmaadmin' else 'ansatt' end) on conflict(company_id,user_id) do update set workspace_role=excluded.workspace_role;
  insert into public.user_active_company_scope(user_id,company_id) values(u,c) on conflict(user_id) do update set company_id=excluded.company_id;
 end loop;
end$$;
set local role authenticated;
do $$declare c uuid:=current_setting('ks.rv.company')::uuid;r jsonb;v jsonb;begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.sys'),true);perform public.kshms_activate(c,true);
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.admin'),true);
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',current_setting('ks.rv.responsible'),'role','responsible','enabled',true));
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',current_setting('ks.rv.reader'),'role','reader','enabled',true));
 perform public.kshms_command(c,'settings',jsonb_build_object('revision',0,'trades',jsonb_build_array('mur_flis'),'responsible_user_id',current_setting('ks.rv.admin')));
 r:=public.kshms_command(c,'save',jsonb_build_object('draft',jsonb_build_object('title','REVIEW REMINDER QA rutine','chapter','QA','goal','QA mål','responsibility','QA ansvar','procedure','QA fremgangsmåte','documentation','QA dokumentasjon','confirmation','QA gjennomgang','references','[]'::jsonb)));
 v:=public.kshms_command(c,'publish',jsonb_build_object('id',r->'id','revision',r->'revision','change_summary','Første QA utgave','requires_ack',true));
 perform set_config('ks.rv.version',v->>'id',true);
 perform pg_temp.rv_assert(public.kshms_review_task(c)->'task'='null'::jsonb,'future revision creates no task');
 perform pg_temp.rv_reject('select public.kshms_review_task(gen_random_uuid())','42501');
 perform pg_temp.rv_reject('select kshms_private.sync_review_reminders()','42501');
 perform pg_temp.rv_reject('select * from public.kshms_notification_outbox','42501');
end$$;
reset role;
do $$declare c uuid:=current_setting('ks.rv.company')::uuid;today date:=(now() at time zone 'Europe/Oslo')::date;begin
 update public.kshms_settings set next_review_on=today+7 where company_id=c;
end$$;
set local role authenticated;
do $$declare c uuid:=current_setting('ks.rv.company')::uuid;r jsonb;begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.admin'),true);r:=public.kshms_review_task(c);
 perform pg_temp.rv_assert(r->>'as_of'=(now() at time zone 'Europe/Oslo')::date::text and r->'task'->>'deadline_status'='soon','server Oslo date and seven-day warning');
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.responsible'),true);
 perform pg_temp.rv_assert(public.kshms_review_task(c)->'task'='null'::jsonb,'other qualified responsible has no appointed task');
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.reader'),true);
 perform pg_temp.rv_assert(public.kshms_review_task(c)->'task'='null'::jsonb,'reader has no revision task');
end$$;
reset role;
do $$declare c uuid:=current_setting('ks.rv.company')::uuid;today date:=(now() at time zone 'Europe/Oslo')::date;o public.kshms_notification_outbox%rowtype;n bigint;begin
 update public.kshms_settings set next_review_on=today where company_id=c;
 perform pg_temp.rv_assert(not exists(select 1 from public.kshms_notification_outbox where company_id=c and notification_kind='review'),'no overdue email on due day');
 update public.kshms_settings set next_review_on=today-90 where company_id=c;
 perform kshms_private.sync_due_reviews();perform kshms_private.sync_due_reviews();
 perform pg_temp.rv_assert((select count(*)=1 from public.kshms_notification_outbox where company_id=c and notification_kind='review'),'one initial assignment for old overdue revision');
 perform kshms_private.sync_review_reminders();
 perform pg_temp.rv_assert(not exists(select 1 from public.kshms_notification_outbox where company_id=c and notification_phase='reminder'),'disabled worker creates no reminders');
 update kshms_private.email_worker_settings set enabled=true,app_url='https://review-qa.example.com';
 perform kshms_private.sync_review_reminders();
 perform pg_temp.rv_assert(not exists(select 1 from public.kshms_notification_outbox where company_id=c and notification_phase='reminder'),'activation and pending initial assignment prevent backlog');
 update kshms_private.email_worker_settings set reminders_enabled_since=now()-interval '120 days';
 update public.company_module_access set updated_at=now()-interval '120 days' where company_id=c and module_key='kshms';
 update public.sales_company_memberships set updated_at=now()-interval '120 days' where company_id=c;
 update public.kshms_member_access set changed_at=now()-interval '120 days' where company_id=c;
 update public.kshms_notification_outbox set status='sent',created_at=now()-interval '8 days',sent_at=now() where company_id=c;
 perform kshms_private.sync_review_reminders();
 perform pg_temp.rv_assert(not exists(select 1 from public.kshms_notification_outbox where company_id=c and notification_phase='reminder'),'late initial delivery gets seven quiet days');
 update public.kshms_notification_outbox set sent_at=now()-interval '8 days' where company_id=c;
 perform kshms_private.sync_review_reminders();perform kshms_private.sync_review_reminders();
 perform pg_temp.rv_assert((select count(*)=1 from public.kshms_notification_outbox where company_id=c and notification_phase='reminder'),'current reminder inserted once, original unique index no longer blocks it');
 select * into o from public.kshms_notification_outbox where company_id=c and notification_phase='reminder';
 perform set_config('ks.rv.reminder',o.id::text,true);
 perform pg_temp.rv_assert(o.reminder_on=kshms_private.reminder_slot(today-90,today) and o.reminder_due_on=today-90 and kshms_private.notification_active(o),'only current weekly slot with matching due date is deliverable');
 o.reminder_on:=o.reminder_on-7;
 perform pg_temp.rv_assert(not kshms_private.notification_active(o),'expired reminder slot is not deliverable');
 select * into o from public.kshms_notification_outbox where id=current_setting('ks.rv.reminder')::uuid;
 update public.kshms_settings set next_review_on=today-91 where company_id=c;
 perform pg_temp.rv_assert(not kshms_private.notification_active(o),'changed revision date invalidates old queued reminder');
 perform pg_temp.rv_assert((select status='suppressed' from public.kshms_notification_outbox where id=o.id),'changed date suppresses pending reminder');
 update public.kshms_settings set responsible_user_id=current_setting('ks.rv.responsible')::uuid where company_id=c;
 update public.kshms_settings set responsible_user_id=current_setting('ks.rv.admin')::uuid where company_id=c;
 perform pg_temp.rv_assert(not kshms_private.notification_active(o),'A-B-A responsibility does not revive old generation');
 perform kshms_private.sync_review_reminders();
 perform pg_temp.rv_assert((select count(*)=1 from public.kshms_notification_outbox where company_id=c and notification_phase='reminder'),'new assignment prevents immediate follow-up duplicate');
 update public.kshms_notification_outbox set status='sent',created_at=now()-interval '8 days',sent_at=now()-interval '8 days' where company_id=c;
 perform kshms_private.sync_review_reminders();
 select * into o from public.kshms_notification_outbox where company_id=c and notification_phase='reminder' and status='pending';
 perform pg_temp.rv_assert(o.id is not null and kshms_private.notification_active(o),'current generation has its own reminder');
 perform set_config('ks.rv.current',o.id::text,true);
 update public.kshms_notification_outbox set status='sending',attempts=1,reserved_at=now(),delivery_email=(select lower(trim(email)) from public.profiles where id=o.user_id) where id=o.id;
 perform pg_temp.rv_assert(public.kshms_email_validate_attempt(o.id,1),'fresh current reminder reservation validates immediately before delivery');
 update public.company_module_access set enabled=false where company_id=c and module_key='kshms';
 perform pg_temp.rv_assert(not kshms_private.notification_active(o),'module revocation invalidates reminder');
 update public.company_module_access set enabled=true where company_id=c and module_key='kshms';
 update public.company_module_access set updated_at=now()+interval '1 second' where company_id=c and module_key='kshms';
 perform pg_temp.rv_assert(not kshms_private.notification_active(o),'module reactivation fences old reminder');
 update public.company_module_access set updated_at=now()-interval '120 days' where company_id=c and module_key='kshms';
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.sys'),true);
 update public.profiles set approved=false where id=o.user_id;
 update public.profiles set approved=true where id=o.user_id;
 perform pg_temp.rv_assert((select status='suppressed' from public.kshms_notification_outbox where id=o.id),'profile eligibility cycle suppresses reserved reminder');
 update public.kshms_notification_outbox set status='pending',attempts=0,reserved_at=null where id=o.id;
end$$;
set local role service_role;
do $$begin
 perform pg_temp.rv_assert(not public.kshms_email_validate_attempt(current_setting('ks.rv.current')::uuid,1),'stale reservation attempt cannot send');
end$$;
reset role;
set local role authenticated;
do $$declare c uuid:=current_setting('ks.rv.company')::uuid;r jsonb;s jsonb;snapshot jsonb;begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.rv.admin'),true);
 r:=public.kshms_review_task(c);perform pg_temp.rv_assert(r->'task'->>'deadline_status'='overdue','own task remains until explicit saved revision');
 s:=public.kshms_get_state(c);
 select jsonb_agg(jsonb_build_object('id',v->>'id','hash',v->>'content_hash') order by v->>'id') into snapshot from jsonb_array_elements(s->'versions') v;
 perform public.kshms_command(c,'review',jsonb_build_object('settings_revision',s->'settings'->'revision','version_snapshot',snapshot,'findings','QA checked all retained routine versions.','follow_up','QA follow up documented; no external communication.','next_review_on',current_date+300));
 perform pg_temp.rv_assert(public.kshms_review_task(c)->'task'='null'::jsonb,'saved signed review clears responsible task');
 perform pg_temp.rv_assert(jsonb_array_length(public.kshms_get_state(c)->'reviews')=1,'one actual signed review recorded');
end$$;
reset role;
do $$declare c uuid:=current_setting('ks.rv.company')::uuid;begin
 perform pg_temp.rv_assert(not exists(select 1 from public.kshms_notification_outbox where company_id=c and notification_kind='review' and status in('pending','sending')),'signed revision suppresses both assignment and reminder');
 perform pg_temp.rv_assert((select count(*)=1 from public.kshms_versions where company_id=c),'historical handbook version retained');
 update public.kshms_settings set responsible_user_id=current_setting('ks.rv.responsible')::uuid,next_review_on=(now() at time zone 'Europe/Oslo')::date-30 where company_id=c;
 update public.kshms_notification_outbox set status='sent',created_at=now()-interval '8 days',sent_at=now()-interval '8 days' where company_id=c;
 perform kshms_private.sync_review_reminders();
 perform pg_temp.rv_assert((select count(*)=1 from public.kshms_notification_outbox o where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid and notification_phase='reminder' and status='pending' and kshms_private.notification_active(o)),'appointed non-admin responsible receives own current reminder');
 update public.kshms_member_access set enabled=false where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid;
 perform pg_temp.rv_assert((select bool_and(not kshms_private.notification_active(o)) from public.kshms_notification_outbox o where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid and notification_phase='reminder'),'revoked responsible grant invalidates queued reminder');
 update public.kshms_member_access set enabled=true,role='reader' where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid;
 perform pg_temp.rv_assert((select bool_and(not kshms_private.notification_active(o)) from public.kshms_notification_outbox o where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid and notification_phase='reminder'),'reader grant cannot deliver designated review reminder');
 update public.kshms_member_access set role='responsible',changed_at=now()+interval '1 second' where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid;
 perform pg_temp.rv_assert((select bool_and(not kshms_private.notification_active(o)) from public.kshms_notification_outbox o where company_id=c and user_id=current_setting('ks.rv.responsible')::uuid and notification_phase='reminder'),'restored grant fences pre-activation reminder');
 perform pg_temp.rv_assert(not has_function_privilege('anon','public.kshms_review_task(uuid)','execute') and has_function_privilege('authenticated','public.kshms_review_task(uuid)','execute'),'read RPC only authenticated');
 perform pg_temp.rv_assert(not has_function_privilege('service_role','kshms_private.sync_review_reminders()','execute'),'private collector has no direct service execution');
end$$;
select current_setting('ks.rv.checks')::int as passed_assertions,'all synthetic writes rolled back; no HTTP sender invoked' as result;
rollback;
