-- Synthetic fixture only. No real rows, HTTP or email. Entire scenario rolls back.
begin;
set local statement_timeout='12s';
set local lock_timeout='2s';
do $$ declare c uuid:=gen_random_uuid(); u uuid; sys uuid; kind text; pid uuid:=gen_random_uuid(); begin
 insert into public.sales_company_scopes(id,normalized_name,display_name) values(c,public.sales_normalize_company_name('SJA QA '||c),'SJA QA '||c);
 perform set_config('ks.sja.company',c::text,true);
 select id into sys from public.profiles where system_role='systemadmin' and approved and not coalesce(deactivated,false) limit 1;assert sys is not null;
 perform set_config('ks.sja.sys',sys::text,true);
 foreach kind in array array['admin','creator','leader','colleague','without'] loop
  u:=gen_random_uuid();perform set_config('ks.sja.'||kind,u::text,true);
  insert into auth.users(id,aud,role,email,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values(u,'authenticated','authenticated','sja-qa-'||u||'@example.invalid',now(),now(),'{}',jsonb_build_object('full_name','SJA QA '||kind));
  insert into public.profiles(id,email,company_name,approved,deactivated,role,company_role) values(u,'sja-qa-'||u||'@example.invalid','SJA QA '||c,true,false,case when kind='admin' then 'admin' else 'member' end,case when kind='admin' then 'firmaadmin' else 'ansatt' end)
  on conflict(id) do update set company_name=excluded.company_name,approved=true,deactivated=false,role=excluded.role,company_role=excluded.company_role,system_role=null;
  insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(c,u,true,case when kind='admin' then 'firmaadmin' else 'ansatt' end) on conflict(company_id,user_id) do update set workspace_role=excluded.workspace_role;
  insert into public.user_active_company_scope(user_id,company_id) values(u,c) on conflict(user_id) do update set company_id=excluded.company_id;
 end loop;
 perform set_config('ks.sja.project',pid::text,true);
 insert into public.projects(id,user_id,company_scope_id,title,data) values(pid,current_setting('ks.sja.creator')::uuid,c,'SJA QA unrelated project','{"project":{"projectName":"QA","projectDeviations":[{"id":"unchanged","status":"Åpent"}]},"checklist":{"Point":{"status":"Ok","comment":"keep"}},"overtagelse":{"signKunde":"keep"}}');
 perform set_config('ks.sja.project.data',(select data::text from public.projects where id=pid),true);
end $$;
set local role authenticated;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid; a uuid:=current_setting('ks.sja.admin')::uuid; creator uuid:=current_setting('ks.sja.creator')::uuid; leader uuid:=current_setting('ks.sja.leader')::uuid; colleague uuid:=current_setting('ks.sja.colleague')::uuid;
 id uuid:=gen_random_uuid();req uuid:=gen_random_uuid();sign_req uuid:=gen_random_uuid();content_data jsonb;payload jsonb;sign_payload jsonb;r jsonb;again jsonb;state jsonb;n integer:=0;
 statement_value text:='Jeg har gjennomgått denne SJA-en sammen med deltakerne. Arbeidsoppgaven, farene, tiltakene og beredskapen er vurdert for forholdene på stedet. Nødvendige tiltak er kontrollert før arbeidet starter. Ved endringer eller uavklart risiko stanser vi og vurderer arbeidet på nytt.';
begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.sys'),true);perform public.kshms_activate(c,true);
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',creator,'role','reader','enabled',true));
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',leader,'role','reader','enabled',true));
 perform public.kshms_command(c,'access',jsonb_build_object('user_id',colleague,'role','reader','enabled',true));
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.without'),true);
 begin perform public.kshms_sja_state(c);raise exception 'No-grant user read SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 state:=public.kshms_sja_state(c);assert jsonb_array_length(state->'members')=4,'Incorrect active internal members';n:=n+1;
 content_data:=jsonb_build_object('title','QA konkret jobb','leader_id',leader,'steps',jsonb_build_array(jsonb_build_object('id',gen_random_uuid())),'participants',jsonb_build_array(jsonb_build_object('id',gen_random_uuid())));
 payload:=jsonb_build_object('id',id,'revision',0,'content',content_data);
 r:=public.kshms_sja_command(c,'save',req,payload);assert r->'sja'->>'status'='draft' and r->'sja'->>'revision'='1','Partial draft not saved';n:=n+1;
 assert r->'sja'->'content'->>'task'='' and r->'sja'->'content'->>'reviewed_on'='' and r->'sja'->>'signed_by' is null,'Draft filled or signed itself';n:=n+1;
 again:=public.kshms_sja_command(c,'save',req,payload);assert again=r,'Lost response retry changed the saved draft';n:=n+1;
 begin perform public.kshms_sja_command(c,'save',req,jsonb_set(payload,'{content,title}','"Different"'));raise exception 'Reused request accepted different content';exception when serialization_failure then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',colleague::text,true);
 assert public.kshms_sja_state(c)->>'total'='0','Another employee saw a private draft';n:=n+1;
 begin perform public.kshms_sja_detail(c,id);raise exception 'Unassigned reader saw draft details';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(payload,'{revision}','1'));raise exception 'Unassigned reader edited draft';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',leader::text,true);
 assert public.kshms_sja_state(c)->>'total'='1','Assigned leader did not receive draft';n:=n+1;
 content_data:=(r->'sja'->'content')||jsonb_build_object('workplace','QA arbeidssted','task','QA oppgave','planned_on','2026-10-08','reviewed_on','2026-10-07','routines','Firmaets relevante rutine','equipment','Avklart arbeidsutstyr','ppe','Vurdert verneutstyr','emergency','QA varsling og førstehjelp','stop_conditions','Stans ved endrede forhold','communication','Gjennomgått med arbeidslaget');
 content_data:=jsonb_set(content_data,'{steps}',jsonb_build_array((content_data->'steps'->0)||jsonb_build_object('activity','QA arbeidstrinn','hazard','QA fare','consequence','QA konsekvens','measures','QA tiltak','owner','QA leder','check','QA kontroll før start')));
 content_data:=jsonb_set(content_data,'{participants}',jsonb_build_array((content_data->'participants'->0)||jsonb_build_object('name','QA deltaker','role','Utførende','involvement','Gjennomgikk arbeidssted og tiltak')));
 payload:=jsonb_build_object('id',id,'revision',1,'content',content_data);
 r:=public.kshms_sja_command(c,'save',gen_random_uuid(),payload);assert r->'sja'->>'revision'='2','Assigned leader could not save';n:=n+1;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),payload);raise exception 'Stale draft overwrote the leader';exception when serialization_failure then n:=n+1;end;
 assert public.kshms_sja_detail(c,id)->'sja'->'content'->>'task'='QA oppgave','Stale save erased task';n:=n+1;
 sign_payload:=jsonb_build_object('id',id,'revision',2,'content',content_data,'statement',statement_value,'prepared',true,'signed_identity',jsonb_build_object('id',creator,'name','Spoofed'));
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),sign_payload);raise exception 'Creator signed for the selected leader';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),sign_payload);raise exception 'Admin signed for the selected leader';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',leader::text,true);
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_set(sign_payload,'{prepared}','false'));raise exception 'Unchecked signature accepted';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_set(sign_payload,'{statement}','"Wrong statement"'));raise exception 'Wrong statement accepted';exception when insufficient_privilege then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'sign',gen_random_uuid(),jsonb_set(sign_payload,'{content,steps,0,hazard}',to_jsonb(E'\t\n'::text)));raise exception 'Blank hazard signed';exception when raise_exception then if sqlerrm='Blank hazard signed' then raise;end if;n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(sign_payload,'{content,planned_on}','"2026-02-30"'));raise exception 'Invalid date accepted';exception when datetime_field_overflow then n:=n+1;end;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(sign_payload,'{content,steps,0,measures}','true'));raise exception 'Boolean measure accepted';exception when raise_exception then if sqlerrm='Boolean measure accepted' then raise;end if;n:=n+1;end;
 r:=public.kshms_sja_command(c,'sign',sign_req,sign_payload);
 assert r->'sja'->>'status'='signed' and r->'sja'->>'signed_by'=leader::text and r->'sja'->'signed_identity'->>'id'=leader::text and r->'sja'->'signed_identity'->>'name'='SJA QA leader' and r->'sja'->>'signed_at' is not null,'Signer identity not server-derived';n:=n+1;
 assert r->'sja'->>'statement'=statement_value and r->'sja'->'content'->'participants'->0->>'involvement'='Gjennomgikk arbeidssted og tiltak','Medvirkning/statement lost';n:=n+1;
 again:=public.kshms_sja_command(c,'sign',sign_req,sign_payload);assert again=r,'Signature retry changed signed record';n:=n+1;
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),jsonb_set(sign_payload,'{content,task}','"erase"'));raise exception 'Signed SJA edited';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 begin perform public.kshms_sja_command(c,'save',gen_random_uuid(),sign_payload);raise exception 'Admin edited signed SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',colleague::text,true);
 assert public.kshms_sja_state(c,'konkret','signed')->>'total'='1' and public.kshms_sja_detail(c,id)->'sja'->>'signed_by'=leader::text,'Employee cannot read completed job documentation';n:=n+1;
 assert public.kshms_sja_state(c,'no match')->>'total'='0','SJA search ignored query';n:=n+1;
 begin perform public.kshms_sja_command(c,'sign',sign_req,sign_payload);raise exception 'Other actor replayed a signature';exception when serialization_failure then n:=n+1;end;
 begin perform public.kshms_sja_state(gen_random_uuid());raise exception 'Foreign company read';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('request.jwt.claim.sub',a::text,true);perform public.kshms_command(c,'access',jsonb_build_object('user_id',leader,'role','reader','enabled',false));
 perform set_config('request.jwt.claim.sub',leader::text,true);
 begin perform public.kshms_sja_detail(c,id);raise exception 'Revoked leader read SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.sja.id',id::text,true);perform set_config('ks.sja.count',n::text,true);
end $$;
reset role;
do $$ declare c uuid:=current_setting('ks.sja.company')::uuid;target_sja uuid:=current_setting('ks.sja.id')::uuid;n integer:=current_setting('ks.sja.count')::integer; begin
 begin update public.kshms_sjas set content='{}' where public.kshms_sjas.id=target_sja;raise exception 'Signed snapshot mutated directly';exception when insufficient_privilege then n:=n+1;end;
 begin delete from public.kshms_sjas where public.kshms_sjas.id=target_sja;raise exception 'Signed snapshot deleted';exception when insufficient_privilege then n:=n+1;end;
 begin
  insert into public.kshms_sjas(id,company_id,content,status,leader_id,created_by,creator_identity,updated_by,signed_by,signed_identity,signed_at,statement)
  select gen_random_uuid(),company_id,content,'signed',null,created_by,creator_identity,updated_by,signed_by,signed_identity,signed_at,statement from public.kshms_sjas where public.kshms_sjas.id=target_sja;
  raise exception 'Signed SJA without selected leader passed its constraint';
 exception when check_violation then n:=n+1;end;
 assert not has_function_privilege('anon','public.kshms_sja_state(uuid,text,text)','execute') and not has_function_privilege('anon','public.kshms_sja_command(uuid,text,uuid,jsonb)','execute');n:=n+1;
 assert not has_table_privilege('authenticated','public.kshms_sjas','select') and not has_table_privilege('authenticated','public.kshms_sja_commands','update');n:=n+1;
 assert (select relrowsecurity from pg_class where oid='public.kshms_sjas'::regclass) and (select relrowsecurity from pg_class where oid='public.kshms_sja_commands'::regclass);n:=n+1;
 assert (select data from public.projects where public.projects.id=current_setting('ks.sja.project')::uuid)=current_setting('ks.sja.project.data')::jsonb,'Existing project/checklist/signature changed';n:=n+1;
 update public.company_module_access set enabled=false where company_id=c and module_key='kshms';
 perform set_config('request.jwt.claim.sub',current_setting('ks.sja.admin'),true);
 begin perform public.kshms_sja_state(c);raise exception 'Disabled company exposed SJA';exception when insufficient_privilege then n:=n+1;end;
 perform set_config('ks.sja.count',n::text,true);
end $$;
select 'PASS: '||current_setting('ks.sja.count')||' SJA access/draft/signature/retry/history/regression assertions; all synthetic rows rolled back' as result;
rollback;
