-- Synthetic versioned-subform proof. Every write is rolled back.
begin;
set local statement_timeout='15s';
set local lock_timeout='2s';
create function pg_temp.sub_assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'SUBFORM QA: %',label;end if;perform set_config('ks.sub.checks',(coalesce(nullif(current_setting('ks.sub.checks',true),''),'0')::integer+1)::text,true);end$$;
create function pg_temp.sub_reject(query text,pattern text) returns void language plpgsql as $$declare failed boolean:=false;message text;begin begin execute query;exception when others then failed:=true;message:=sqlerrm;end;perform pg_temp.sub_assert(failed and message ilike '%'||pattern||'%','expected rejection containing '||pattern||', got '||coalesce(message,'success'));end$$;
do $$declare company uuid:=gen_random_uuid();admin_id uuid:=gen_random_uuid();sys uuid;begin
 insert into public.sales_company_scopes(id,normalized_name,display_name) values(company,public.sales_normalize_company_name('subform-qa-'||company),'subform-qa-'||company);perform set_config('ks.sub.company',company::text,true);
 select id into sys from public.profiles where system_role='systemadmin' and approved and not coalesce(deactivated,false) limit 1;assert sys is not null;perform set_config('ks.sub.sys',sys::text,true);
 insert into auth.users(id,aud,role,email,created_at,updated_at,raw_app_meta_data,raw_user_meta_data) values(admin_id,'authenticated','authenticated','subform-qa-'||admin_id||'@example.invalid',now(),now(),'{}','{}');
 insert into public.profiles(id,email,company_name,approved,deactivated,role,company_role) values(admin_id,'subform-qa-'||admin_id||'@example.invalid','subform-qa-'||company,true,false,'admin','firmaadmin');
 insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role) values(company,admin_id,true,'firmaadmin') on conflict(company_id,user_id) do update set workspace_role='firmaadmin',is_primary=true;insert into public.user_active_company_scope(user_id,company_id) values(admin_id,company) on conflict(user_id) do update set company_id=excluded.company_id;
 perform set_config('ks.sub.admin',admin_id::text,true);
end$$;
set local role authenticated;
do $$declare company uuid:=current_setting('ks.sub.company')::uuid;admin_id uuid:=current_setting('ks.sub.admin')::uuid;child_template uuid:=gen_random_uuid();parent_template uuid:=gen_random_uuid();child_point uuid:=gen_random_uuid();parent_point uuid:=gen_random_uuid();round_id uuid:=gen_random_uuid();
 child_content jsonb;parent_content jsonb;child_result jsonb;parent_result jsonb;child_v1 jsonb;child_v2 jsonb;parent_v1 jsonb;parent_v2 jsonb;state jsonb;execution jsonb;begin
 perform set_config('request.jwt.claim.sub',current_setting('ks.sub.sys'),true);perform public.kshms_activate(company,true);perform set_config('request.jwt.claim.sub',admin_id::text,true);
 child_content:=jsonb_build_object('title','QA trykkprøve','trade','Rørlegger','instructions','Utfør trykkprøve','points',jsonb_build_array(jsonb_build_object('id',child_point,'title','Kontroller trykk','guidance','Les av manometer','image_required',true,'comment_required',false)));
 child_result:=public.kshms_checklist_command(company,'publish',gen_random_uuid(),jsonb_build_object('id',child_template,'revision',0,'content',child_content));child_v1:=child_result->'version';
 perform pg_temp.sub_assert(child_v1#>>'{content,title}'='QA trykkprøve','child v1 published');
 parent_content:=jsonb_build_object('title','QA hovedkontroll','trade','Rørlegger','instructions','Før innbygging','points',jsonb_build_array(jsonb_build_object('id',parent_point,'title','Kontroller rør','guidance','','image_required',false,'comment_required',false,'subform_version_id',child_v1->>'id')));
 parent_result:=public.kshms_checklist_command(company,'publish',gen_random_uuid(),jsonb_build_object('id',parent_template,'revision',0,'content',parent_content));parent_v1:=parent_result->'version';
 perform pg_temp.sub_assert(jsonb_array_length(parent_v1#>'{content,root_points}')=1 and parent_v1#>>'{content,root_points,0,subform_version_id}'=child_v1->>'id','root keeps exact child edition');
 perform pg_temp.sub_assert(jsonb_array_length(parent_v1#>'{content,points}')=2 and parent_v1#>>'{content,points,1,title}'='Underskjema · QA trykkprøve · Kontroller trykk','execution points flattened');
 perform pg_temp.sub_assert(parent_v1#>>'{content,dependencies,0,version_id}'=child_v1->>'id' and parent_v1#>>'{content,dependencies,0,content_hash}'=child_v1->>'content_hash','dependency id/hash snapshot');
 child_content:=jsonb_set(child_content,'{points,0,title}','"Kontroller nytt trykk"');child_result:=public.kshms_checklist_command(company,'publish',gen_random_uuid(),jsonb_build_object('id',child_template,'revision',child_result#>>'{template,revision}','content',child_content));child_v2:=child_result->'version';
 perform pg_temp.sub_assert(child_v2->>'number'='2' and child_v2->>'id'<>child_v1->>'id','child v2 published');
 perform pg_temp.sub_assert((select value->'content'=parent_v1->'content' from jsonb_array_elements(public.kshms_checklist_state(company)->'versions') where value->>'id'=parent_v1->>'id'),'child edit did not rewrite parent v1');
 parent_result:=public.kshms_checklist_command(company,'publish',gen_random_uuid(),jsonb_build_object('id',parent_template,'revision',parent_result#>>'{template,revision}','content',parent_content));
 perform pg_temp.sub_assert(parent_result#>>'{version,id}'=parent_v1->>'id','same pinned child reuses parent edition');
 parent_content:=jsonb_set(parent_content,'{points,0,subform_version_id}',to_jsonb(child_v2->>'id'));parent_result:=public.kshms_checklist_command(company,'publish',gen_random_uuid(),jsonb_build_object('id',parent_template,'revision',parent_result#>>'{template,revision}','content',parent_content));parent_v2:=parent_result->'version';
 perform pg_temp.sub_assert(parent_v2->>'number'='2' and parent_v2#>>'{content,dependencies,0,version_id}'=child_v2->>'id','parent v2 pins child v2');
 perform pg_temp.sub_assert(not (parent_v2#>'{content,points,0}')?'subform_version_id','execution point excludes dependency reference');
 perform public.kshms_execution_command(company,'save',gen_random_uuid(),jsonb_build_object('id',round_id,'kind','round','revision',0,'project_id',null,'template_version_id',parent_v2->>'id','content',jsonb_build_object('title','QA underskjemakontroll','workplace','','planned_on','','responsible_id',admin_id,'participants','','review','','reference','','routines','','basis','','points',parent_v2#>'{content,points}','answers','{}'::jsonb,'risks','[]'::jsonb,'acceptance',jsonb_build_object('low_max',null,'medium_max',null,'description','','confirmed',false))));execution:=public.kshms_execution_detail(company,round_id);
 perform pg_temp.sub_assert(execution#>>'{record,template_snapshot,content,dependencies,0,version_id}'=child_v2->>'id' and jsonb_array_length(execution#>'{record,content,points}')=2,'standalone run accepts flattened immutable snapshot');
 perform pg_temp.sub_reject(format('select public.kshms_checklist_command(%L,''save'',%L,%L::jsonb)',company,gen_random_uuid(),jsonb_build_object('id',child_template,'revision',child_result#>>'{template,revision}','content',jsonb_set(child_content,'{points,0,subform_version_id}',to_jsonb(parent_v2->>'id')))),'sirkel');
 perform pg_temp.sub_reject(format('select public.kshms_checklist_command(%L,''save'',%L,%L::jsonb)',company,gen_random_uuid(),jsonb_build_object('id',parent_template,'revision',parent_result#>>'{template,revision}','content',jsonb_set(parent_content,'{points,0,subform_version_id}',to_jsonb(gen_random_uuid()::text)))),'ikke tilgjengelig');
 perform public.kshms_checklist_command(company,'archive',gen_random_uuid(),jsonb_build_object('id',child_template,'revision',child_result#>>'{template,revision}'));
 perform pg_temp.sub_reject(format('select public.kshms_checklist_command(%L,''save'',%L,%L::jsonb)',company,gen_random_uuid(),jsonb_build_object('id',parent_template,'revision',parent_result#>>'{template,revision}','content',parent_content)),'arkivert');
 state:=public.kshms_checklist_state(company);perform pg_temp.sub_assert(jsonb_array_length(state->'versions')=4,'central returns every selectable edition');
 perform set_config('ks.sub.parent_version',parent_v1->>'id',true);
end$$;
reset role;
select pg_temp.sub_assert(not has_function_privilege('authenticated','kshms_private.checklist_snapshot(uuid,uuid,jsonb)','execute'),'private snapshot helper closed');
select pg_temp.sub_assert(not has_function_privilege('anon','public.kshms_checklist_state(uuid)','execute'),'anonymous central closed');
select pg_temp.sub_assert((select content#>>'{dependencies,0,content_hash}' is not null from public.kshms_checklist_versions where id=current_setting('ks.sub.parent_version')::uuid),'stored dependency remains readable to server');
select 'PASS – versioned subforms; all synthetic rows rolled back' result,current_setting('ks.sub.checks')::integer assertions;
rollback;
