begin;
set local statement_timeout='35s';set local lock_timeout='2s';
create function pg_temp.g_assert(ok boolean,label text)returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'GROUP QA: %',label;end if;perform set_config('org.g.count',(coalesce(nullif(current_setting('org.g.count',true),''),'0')::integer+1)::text,true);end$$;
create function pg_temp.g_reject(q text,code text)returns void language plpgsql as $$declare failed boolean:=false;got text;begin begin execute q;exception when others then failed:=true;get stacked diagnostics got=returned_sqlstate;end;perform pg_temp.g_assert(failed and got=code,'expected '||code||' got '||coalesce(got,'success')||' on '||q);end$$;
create function pg_temp.g_write(c uuid,g uuid,action text,p jsonb)returns jsonb language plpgsql as $$begin return public.organization_group_command(c,g,(public.organization_group_state(c,g)->>'revision')::integer,action,p);end$$;
do $$declare ids uuid[];c uuid;u uuid;k text;i integer;begin
 for i in 1..4 loop c:=gen_random_uuid();ids:=array_append(ids,c);insert into public.sales_company_scopes(id,normalized_name,display_name)values(c,'org-g-qa-'||c,case i when 1 then 'Ringside Rørleggerbedrift' when 2 then 'Bademiljø Expo' when 3 then 'Expo Proffsenter' else 'Utenfor kartet' end);insert into public.company_module_access(company_id,module_key,enabled)values(c,'kshms',true);perform set_config('org.g.c'||i,c::text,true);end loop;
 foreach k in array array['admin','self','ks','head','system'] loop
 u:=gen_random_uuid();perform set_config('org.g.'||k,u::text,true);
 insert into auth.users(id,aud,role,email,created_at,updated_at,raw_app_meta_data,raw_user_meta_data)values(u,'authenticated','authenticated','org-g-qa-'||u||'@example.invalid',now(),now(),'{}',jsonb_build_object('full_name','Syntetisk '||k));
 insert into public.profiles(id,email,company_name,approved,deactivated,role,company_role)values(u,'org-g-qa-'||u||'@example.invalid','org-g-qa-'||ids[1],true,false,case when k='admin' then 'admin' else 'member' end,case when k='admin' then 'firmaadmin' else 'ansatt' end)on conflict(id)do update set approved=true,deactivated=false,role=excluded.role,company_role=excluded.company_role,system_role=null;
 for i in 1..case when k in ('head','system')then 1 else 4 end loop
 insert into public.sales_company_memberships(company_id,user_id,is_primary,workspace_role)values(ids[i],u,i=1,case when k='admin' then 'firmaadmin' else 'ansatt' end)on conflict(company_id,user_id)do update set workspace_role=excluded.workspace_role;
 if k<>'system' then insert into public.kshms_member_access(company_id,user_id,role,enabled,changed_by)values(ids[i],u,case when k='ks' then 'responsible' else 'reader' end,true,u);end if;
 end loop;
 insert into public.user_active_company_scope(user_id,company_id)values(u,ids[1])on conflict(user_id)do update set company_id=excluded.company_id;
 end loop;
 update public.profiles set is_admin=true,system_role='systemadmin' where id=current_setting('org.g.system')::uuid;
 perform set_config('org.g.hr_before',(select count(*)from hr_private.employees)::text,true);
 perform set_config('org.g.org_before',(select count(*)from org_private.units)::text,true);
end$$;
set local role authenticated;
do $$declare c uuid:=current_setting('org.g.c1')::uuid;b uuid:=current_setting('org.g.c2')::uuid;d uuid:=current_setting('org.g.c3')::uuid;foreignc uuid:=current_setting('org.g.c4')::uuid;g uuid:=gen_random_uuid();otherg uuid:=gen_random_uuid();a uuid:=current_setting('org.g.admin')::uuid;u uuid:=current_setting('org.g.self')::uuid;x jsonb;before jsonb;p jsonb;bad jsonb;ids uuid[];units uuid[];unit uuid;board uuid;r integer;i integer;head uuid:=current_setting('org.g.head')::uuid;begin
 perform set_config('request.jwt.claim.sub',a::text,true);perform set_config('org.g.group',g::text,true);
 p:=jsonb_build_object('id',g,'name','Ringside','company_ids',jsonb_build_array(c,b,d),'confirm',true);
 perform pg_temp.g_reject(format('select public.organization_group_create(%L,%L::jsonb)',c,p||'{"confirm":false}'),'22023');
 perform pg_temp.g_reject(format('select public.organization_group_create(%L,%L::jsonb)',c,p||'{"medical":"secret"}'),'22023');
 perform pg_temp.g_reject(format('select public.organization_group_create(%L,%L::jsonb)',c,jsonb_set(p,'{company_ids}',jsonb_build_array(c,c))),'22023');
 perform pg_temp.g_reject(format('select public.organization_group_create(%L,%L::jsonb)',c,jsonb_set(p,'{company_ids}',jsonb_build_array(b,d))),'22023');
 x:=public.organization_group_create(c,p);
 perform pg_temp.g_assert(x->>'chart_name'='Ringside' and jsonb_array_length(x->'companies')=3 and jsonb_array_length(x->'units')=4,'create board + three explicit companies');
 select(v->>'id')::uuid into board from jsonb_array_elements(x->'units')v where v->>'name'='Styret';
 perform pg_temp.g_assert((select count(*)from jsonb_array_elements(x->'units')v where v->>'parent_id'=board::text)=3,'three peers');
 perform pg_temp.g_assert((select count(*)from jsonb_array_elements(x->'people')v where v->>'user_id'=u::text)=3,'same account three rows');
 perform pg_temp.g_assert((select count(distinct v->>'id')from jsonb_array_elements(x->'people')v where v->>'user_id'=u::text)=3,'distinct per-company placement identity');
 perform pg_temp.g_assert((select count(*)from jsonb_array_elements(public.organization_group_options(c)->'groups')v where v->>'id'=g::text)=1,'available group');
 perform pg_temp.g_reject(format('select public.organization_group_create(%L,%L::jsonb)',c,p),'40001');
 ids:=array[c,b,d];
 for i in 1..3 loop select(v->>'id')::uuid into unit from jsonb_array_elements(x->'units')v where v->>'company_id'=ids[i]::text;units:=array_append(units,unit);
 x:=pg_temp.g_write(c,g,'place',jsonb_build_object('employee_id',ids[i]::text||':'||u::text,'company_id',ids[i],'user_id',u,'unit_id',units[i],'title',case i when 1 then 'Prosjektleder' when 2 then 'Butikksjef' else 'Faglig leder' end,'kind',case when i=2 then 'middle' else 'leader' end));end loop;
 perform pg_temp.g_assert((select count(distinct v->>'title')from jsonb_array_elements(x->'people')v where v->>'user_id'=u::text)=3,'one identity different firm titles');
 perform pg_temp.g_assert((select count(distinct v->>'kind')from jsonb_array_elements(x->'people')v where v->>'user_id'=u::text)=2,'different firm roles');
 before:=x;r:=(x->>'revision')::integer;
 bad:=jsonb_build_object('employee_id',c::text||':'||u::text,'company_id',c,'user_id',u,'unit_id',units[2],'title','Rørlegger','kind','employee');
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''place'',%L::jsonb)',c,g,r,bad),'42501');
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''place'',%L::jsonb)',c,g,r,bad||jsonb_build_object('employee_id',foreignc::text||':'||u::text,'company_id',foreignc)),'42501');
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''place'',%L::jsonb)',c,g,r,bad||jsonb_build_object('unit_id',units[1],'employee_id',u::text)),'42501');
 perform pg_temp.g_assert(public.organization_group_state(c,g)=before,'rejections cause no writes');
 p:=jsonb_build_object('chart_name','Ringside','units',(select jsonb_agg(v-'editable'-'manager_name')from jsonb_array_elements(x->'units')v),'removed_ids','[]'::jsonb,'confirm_removal',false);
 x:=pg_temp.g_write(c,g,'layout',p);perform pg_temp.g_assert((x->>'revision')::integer=r+1,'layout CAS advances once');
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,p),'40001');
 r:=(x->>'revision')::integer;before:=x;
 bad:=p||jsonb_build_object('units',(p->'units')||jsonb_build_object('id',gen_random_uuid(),'name','Sent ugyldig','color','teal','company_id',foreignc));
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'42501');
 perform pg_temp.g_assert(public.organization_group_state(c,g)=before,'invalid late unit atomic rollback');
 -- Local branch leader need only access their own firm, and receives no edit/HR grant.
 bad:=jsonb_set(p,'{units}',(select jsonb_agg(case when v->>'id'=units[1]::text then v||jsonb_build_object('manager_id',head)else v end)from jsonb_array_elements(p->'units')v));
 x:=pg_temp.g_write(c,g,'layout',bad);perform pg_temp.g_assert((select v->>'manager_id'=head::text from jsonb_array_elements(x->'units')v where v->>'id'=units[1]::text),'single-firm chart leader');
 p:=bad;r:=(x->>'revision')::integer;before:=x;
 bad:=jsonb_set(p,'{units}',(select jsonb_agg(case when v->>'id'=units[1]::text then v||jsonb_build_object('parent_id',units[2])else v end)from jsonb_array_elements(p->'units')v));
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 bad:=jsonb_set(p,'{units}',(select jsonb_agg(case when v->>'id'=board::text then v||jsonb_build_object('parent_id',units[1])else v end)from jsonb_array_elements(p->'units')v));
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 bad:=jsonb_set(p,'{units}',(select jsonb_agg(case when v->>'id'=units[1]::text then v||jsonb_build_object('company_id',null,'manager_id',null)else v end)from jsonb_array_elements(p->'units')v));
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 perform pg_temp.g_assert(public.organization_group_state(c,g)=before,'moving bound branch rolls all back');
 -- A different group with globally unique units; cannot hijack them.
 x:=public.organization_group_create(c,jsonb_build_object('id',otherg,'name','Annet kart','company_ids',jsonb_build_array(c,b,d),'confirm',true));
 bad:=jsonb_set(p,'{units}',(p->'units')||jsonb_build_object('id',x#>>'{units,0,id}','name','Foreign ID','color','teal'));
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'42501');
 x:=pg_temp.g_write(c,otherg,'remove_group','{"confirm":true}');
 -- Explicit branch deletion preserves title, account and ordinary chart.
 bad:=jsonb_set(p,'{units}',(select jsonb_agg(v)from jsonb_array_elements(p->'units')v where v->>'id'<>units[1]::text))||jsonb_build_object('removed_ids',jsonb_build_array(units[1]));
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 x:=pg_temp.g_write(c,g,'layout',bad||'{"confirm_removal":true}');
 perform pg_temp.g_assert((select v->>'unit_id' is null and v->>'title'='Prosjektleder' from jsonb_array_elements(x->'people')v where v->>'id'=c::text||':'||u::text),'delete branch unplaces + preserves title');
 perform pg_temp.g_assert(jsonb_array_length(x->'units')=3,'only selected branch removed');
 perform set_config('org.g.payload',p::text,true);
end$$;
-- Reading/writing denied from partial membership, system-role and KS-responsible.
do $$declare c uuid:=current_setting('org.g.c1')::uuid;g uuid:=current_setting('org.g.group')::uuid;u uuid:=current_setting('org.g.self')::uuid;k text;x jsonb;begin
 perform set_config('request.jwt.claim.sub',u::text,true);x:=public.organization_group_state(c,g);perform pg_temp.g_assert(x#>>'{context,administer}'='false','reader with all firms can read only');
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''remove_group'',''{"confirm":true}'')',c,g,(x->>'revision')::integer),'42501');
 perform set_config('request.jwt.claim.sub',current_setting('org.g.ks'),true);x:=public.organization_group_state(c,g);
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,(x->>'revision')::integer,current_setting('org.g.payload')),'42501');
 perform set_config('request.jwt.claim.sub',current_setting('org.g.head'),true);
 perform pg_temp.g_reject(format('select public.organization_group_state(%L,%L)',c,g),'42501');
 perform pg_temp.g_assert(jsonb_array_length(public.organization_group_options(c)->'groups')=0,'partial access hides even group name');
 perform pg_temp.g_assert(public.organization_state(c)#>>'{context,user_id}'=current_setting('org.g.head'),'ordinary own-firm chart still works');
 perform set_config('request.jwt.claim.sub',current_setting('org.g.system'),true);perform pg_temp.g_reject(format('select public.organization_group_state(%L,%L)',c,g),'42501');
end$$;
reset role;
update public.kshms_member_access set enabled=false where company_id=current_setting('org.g.c2')::uuid and user_id=current_setting('org.g.self')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('org.g.self'),true);
select pg_temp.g_reject(format('select public.organization_group_state(%L,%L)',current_setting('org.g.c1'),current_setting('org.g.group')),'42501');
select pg_temp.g_assert(jsonb_array_length(public.organization_group_options(current_setting('org.g.c1')::uuid)->'groups')=0,'revoked other firm removes group');
reset role;
update public.kshms_member_access set enabled=true where company_id=current_setting('org.g.c2')::uuid and user_id=current_setting('org.g.self')::uuid;
insert into hr_private.closed_employments(company_id,user_id,employee_id,previous_revision)values(current_setting('org.g.c2')::uuid,current_setting('org.g.self')::uuid,gen_random_uuid(),1);
set local role authenticated;
select pg_temp.g_reject(format('select public.organization_group_state(%L,%L)',current_setting('org.g.c1'),current_setting('org.g.group')),'42501');
select set_config('request.jwt.claim.sub',current_setting('org.g.admin'),true);
select pg_temp.g_assert((select count(*)from jsonb_array_elements(public.organization_group_state(current_setting('org.g.c1')::uuid,current_setting('org.g.group')::uuid)->'people')v where v->>'user_id'=current_setting('org.g.self'))=2,'ended employment removes only its firm row');
do $$declare c uuid:=current_setting('org.g.c1')::uuid;g uuid:=current_setting('org.g.group')::uuid;x jsonb;p jsonb;bad jsonb;prev uuid:=null;r integer;i integer;begin
 x:=public.organization_group_state(c,g);r:=(x->>'revision')::integer;
 p:=jsonb_build_object('chart_name','Ringside','units',(select jsonb_agg(v-'editable'-'manager_name')from jsonb_array_elements(x->'units')v),'removed_ids','[]'::jsonb,'confirm_removal',false);
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,p||'{"hr_readers":[]}'),'22023');
 bad:=p||'{"units":[]}';for i in 1..13 loop bad:=jsonb_set(bad,'{units}',(bad->'units')||jsonb_build_object('id',gen_random_uuid(),'name','Level '||i,'color','teal','parent_id',prev));prev:=(bad#>>array['units',(i-1)::text,'id'])::uuid;end loop;
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 bad:=p||'{"units":[]}';for i in 1..101 loop bad:=jsonb_set(bad,'{units}',(bad->'units')||jsonb_build_object('id',gen_random_uuid(),'name','Unit '||i,'color','teal'));end loop;
 perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 bad:=jsonb_set(p,'{units,0,parent_id}',to_jsonb(gen_random_uuid()::text));perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 bad:=jsonb_set(p,'{units}',(p->'units')||(p->'units'->0));perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'42501');
 bad:=jsonb_set(p,'{units,0,manager_id}','true');perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 bad:=jsonb_set(p,'{units,0,manager_id}',to_jsonb(current_setting('org.g.system')));perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'42501');
 bad:=jsonb_set(p,'{units,0,color}','"invalid"');perform pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''layout'',%L::jsonb)',c,g,r,bad),'22023');
 perform pg_temp.g_assert(public.organization_group_state(c,g)=x,'all structural rejects atomic');
 perform set_config('request.jwt.claim.sub',current_setting('org.g.ks'),true);
 perform pg_temp.g_reject(format('select public.organization_group_create(%L,%L::jsonb)',c,jsonb_build_object('id',gen_random_uuid(),'name','Forbidden','company_ids',jsonb_build_array(c,current_setting('org.g.c2'),current_setting('org.g.c3')),'confirm',true)),'42501');
 perform set_config('request.jwt.claim.sub',current_setting('org.g.admin'),true);
end$$;
reset role;
update public.sales_company_memberships set workspace_role='ansatt' where company_id=current_setting('org.g.c2')::uuid and user_id=current_setting('org.g.admin')::uuid;
set local role authenticated;
select pg_temp.g_assert(public.organization_group_state(current_setting('org.g.c1')::uuid,current_setting('org.g.group')::uuid)#>>'{context,administer}'='false','one lost admin strips all-group edit');
select pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''remove_group'',''{"confirm":true}'')',current_setting('org.g.c1'),current_setting('org.g.group'),(public.organization_group_state(current_setting('org.g.c1')::uuid,current_setting('org.g.group')::uuid)->>'revision')::integer),'42501');
reset role;
update public.sales_company_memberships set workspace_role='firmaadmin' where company_id=current_setting('org.g.c2')::uuid and user_id=current_setting('org.g.admin')::uuid;
update public.company_module_access set enabled=false where company_id=current_setting('org.g.c2')::uuid and module_key='kshms';
set local role authenticated;
select pg_temp.g_reject(format('select public.organization_group_state(%L,%L)',current_setting('org.g.c1'),current_setting('org.g.group')),'42501');
select pg_temp.g_assert(jsonb_array_length(public.organization_group_options(current_setting('org.g.c1')::uuid)->'groups')=0,'disabled company hides all-group metadata');
reset role;
update public.company_module_access set enabled=true where company_id=current_setting('org.g.c2')::uuid and module_key='kshms';
update public.user_active_company_scope set company_id=current_setting('org.g.c4')::uuid where user_id=current_setting('org.g.admin')::uuid;
set local role authenticated;
select pg_temp.g_reject(format('select public.organization_group_state(%L,%L)',current_setting('org.g.c1'),current_setting('org.g.group')),'42501');
reset role;
update public.user_active_company_scope set company_id=current_setting('org.g.c1')::uuid where user_id=current_setting('org.g.admin')::uuid;
set local role authenticated;
select pg_temp.g_reject(format('select public.organization_group_command(%L,%L,%s,''remove_group'',''{"confirm":"true"}'')',current_setting('org.g.c1'),current_setting('org.g.group'),(public.organization_group_state(current_setting('org.g.c1')::uuid,current_setting('org.g.group')::uuid)->>'revision')::integer),'22023');
select pg_temp.g_write(current_setting('org.g.c1')::uuid,current_setting('org.g.group')::uuid,'remove_group','{"confirm":true}') is not null;
reset role;
select pg_temp.g_assert(not exists(select 1 from org_private.groups where id=current_setting('org.g.group')::uuid),'group removed');
select pg_temp.g_assert((select count(*)from hr_private.employees)::text=current_setting('org.g.hr_before'),'HR untouched');
select pg_temp.g_assert((select count(*)from org_private.units)::text=current_setting('org.g.org_before'),'company chart untouched');
select pg_temp.g_assert((select count(*)from public.sales_company_memberships where user_id=current_setting('org.g.self')::uuid)=4,'same account memberships untouched');
do $$declare t text;begin foreach t in array array['groups','group_companies','group_units','group_placements']loop perform pg_temp.g_assert(not has_table_privilege('authenticated','org_private.'||t,'SELECT') and not has_table_privilege('anon','org_private.'||t,'SELECT'),'private ACL '||t);end loop;end$$;
select current_setting('org.g.count')::integer as group_assertions_pass;
rollback;
