// Expo ProffDok – FASE 45B
// Smal prisflate: Din nto pris beregnes fra Kundepris eks. mva.; Ringsides ERP-nettopris er aldri klientdata.
import { getSalesSupportCompanyId } from "../sales/services/salesSupabase.js";
function ensureClient(supabase) { if (!supabase?.rpc) throw new Error("Supabase-klient mangler."); return supabase; }
function unwrap(data,error,fallback) { if (error) throw new Error(error.message||fallback); return data; }
export async function searchProStoreCatalog(supabase,query,limit=30){const client=ensureClient(supabase);const supportCompanyId=getSalesSupportCompanyId();const request=supportCompanyId?client.rpc("search_pro_store_catalog_support",{p_company_id:supportCompanyId,p_query:query,p_limit:limit}):client.rpc("search_pro_store_catalog",{p_query:query,p_limit:limit});const {data,error}=await request;return unwrap(data||[],error,"Kunne ikke søke i proff-vareregisteret.");}
export async function canAccessProStoreCatalog(supabase){const client=ensureClient(supabase);const supportCompanyId=getSalesSupportCompanyId();if(supportCompanyId){const {data,error}=await client.rpc("list_store_catalog_company_supplier_access",{p_company_id:supportCompanyId});if(error)return false;return Array.isArray(data)?data.some((row)=>row?.is_active===true):Array.isArray(data?.data)?data.data.some((row)=>row?.is_active===true):false;}const {data,error}=await client.rpc("current_user_has_pro_store_catalog_access");return error?false:data===true;}
export async function canViewMyNetPrice(supabase){const {data,error}=await ensureClient(supabase).rpc("current_user_can_view_store_catalog_net_price");return error?false:data===true;}
export async function listCatalogCompanies(supabase){const {data,error}=await ensureClient(supabase).rpc("list_store_catalog_company_scopes");return unwrap(data||[],error,"Kunne ikke hente firmaer.");}
export async function listCatalogSuppliers(supabase){const {data,error}=await ensureClient(supabase).rpc("list_store_catalog_suppliers");return unwrap(data||[],error,"Kunne ikke hente leverandører.");}
export async function listCompanySupplierAccess(supabase,companyId){const {data,error}=await ensureClient(supabase).rpc("list_store_catalog_company_supplier_access",{p_company_id:companyId});return unwrap(data||[],error,"Kunne ikke hente leverandørtilganger.");}
export async function setCompanySupplierAccess(supabase,{companyId,supplierKey,discountPercent=0,isActive=true}){const {data,error}=await ensureClient(supabase).rpc("set_store_catalog_company_supplier_access",{p_company_id:companyId,p_supplier_key:supplierKey,p_discount_percent:discountPercent,p_is_active:isActive});return unwrap(data,error,"Kunne ikke lagre leverandørtilgang.");}
export async function listUserNetPriceAccess(supabase){const {data,error}=await ensureClient(supabase).rpc("list_store_catalog_user_net_price_access");return unwrap(data||[],error,"Kunne ikke hente prisinnsyn.");}
export async function setUserNetPriceAccess(supabase,userId,canView){const {data,error}=await ensureClient(supabase).rpc("set_store_catalog_user_net_price_access",{p_user_id:userId,p_can_view:canView===true});return unwrap(data,error,"Kunne ikke lagre prisinnsyn.");}
