-- Expo ProffDok – systemadminstyrt e-postutsending
-- Skiller nødvendige driftsmeldinger fra samtykkebasert markedsføring.

create table if not exists public.marketing_email_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email_opt_in boolean not null default false,
  consent_at timestamptz,
  consent_source text not null default 'app_settings',
  unsubscribed_at timestamptz,
  unsubscribe_token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint marketing_email_preferences_token_unique unique (unsubscribe_token),
  constraint marketing_email_preferences_source_check check (
    consent_source in ('app_settings', 'email_unsubscribe')
  ),
  constraint marketing_email_preferences_consent_check check (
    not email_opt_in or consent_at is not null
  )
);

create table if not exists public.marketing_email_preference_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email_opt_in boolean not null,
  source text not null,
  created_at timestamptz not null default now(),
  constraint marketing_email_preference_events_source_check check (
    source in ('app_settings', 'email_unsubscribe')
  )
);

create table if not exists public.systemadmin_email_campaigns (
  id uuid primary key default gen_random_uuid(),
  client_request_id uuid not null unique,
  created_by uuid not null,
  message_type text not null,
  recipient_group text not null,
  subject text not null,
  message text not null,
  recipient_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  status text not null default 'processing',
  resend_batch_ids jsonb not null default '[]'::jsonb,
  error_summary text,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint systemadmin_email_campaigns_message_type_check check (
    message_type in ('operational', 'marketing')
  ),
  constraint systemadmin_email_campaigns_recipient_group_check check (
    recipient_group in ('active', 'pending', 'all_registered', 'systemadmins')
  ),
  constraint systemadmin_email_campaigns_status_check check (
    status in ('processing', 'sent', 'partial', 'failed')
  ),
  constraint systemadmin_email_campaigns_count_check check (
    recipient_count >= 0 and sent_count >= 0 and failed_count >= 0
  )
);

alter table public.marketing_email_preferences enable row level security;
alter table public.marketing_email_preference_events enable row level security;
alter table public.systemadmin_email_campaigns enable row level security;

-- Preferansetoken, samtykkehistorikk og utsendingslogg skal aldri leses direkte
-- fra nettleseren. Brukerflaten går via de avgrensede RPC-ene under.
revoke all on table public.marketing_email_preferences from public, anon, authenticated, service_role;
revoke all on table public.marketing_email_preference_events from public, anon, authenticated, service_role;
revoke all on table public.systemadmin_email_campaigns from public, anon, authenticated, service_role;
grant select, update on table public.marketing_email_preferences to service_role;
grant select, insert, update on table public.systemadmin_email_campaigns to service_role;

drop policy if exists marketing_email_preferences_client_deny
  on public.marketing_email_preferences;
create policy marketing_email_preferences_client_deny
  on public.marketing_email_preferences
  for all to anon, authenticated
  using (false)
  with check (false);

drop policy if exists marketing_email_preference_events_client_deny
  on public.marketing_email_preference_events;
create policy marketing_email_preference_events_client_deny
  on public.marketing_email_preference_events
  for all to anon, authenticated
  using (false)
  with check (false);

drop policy if exists systemadmin_email_campaigns_client_deny
  on public.systemadmin_email_campaigns;
create policy systemadmin_email_campaigns_client_deny
  on public.systemadmin_email_campaigns
  for all to anon, authenticated
  using (false)
  with check (false);

create index if not exists marketing_email_preference_events_user_created_idx
  on public.marketing_email_preference_events (user_id, created_at desc);
create index if not exists systemadmin_email_campaigns_created_by_created_idx
  on public.systemadmin_email_campaigns (created_by, created_at desc);

create or replace function public.log_marketing_email_preference_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' or old.email_opt_in is distinct from new.email_opt_in then
    insert into public.marketing_email_preference_events (
      user_id,
      email_opt_in,
      source
    ) values (
      new.user_id,
      new.email_opt_in,
      new.consent_source
    );
  end if;
  return new;
end;
$$;

drop trigger if exists marketing_email_preference_event_trigger
  on public.marketing_email_preferences;
create trigger marketing_email_preference_event_trigger
after insert or update of email_opt_in on public.marketing_email_preferences
for each row execute function public.log_marketing_email_preference_event();

create or replace function public.get_my_marketing_email_preference()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.marketing_email_preferences%rowtype;
begin
  if v_uid is null then
    raise exception 'Du må være innlogget.' using errcode = '42501';
  end if;

  select * into v_row
  from public.marketing_email_preferences
  where user_id = v_uid;

  return jsonb_build_object(
    'email_opt_in', coalesce(v_row.email_opt_in, false),
    'consent_at', v_row.consent_at,
    'unsubscribed_at', v_row.unsubscribed_at
  );
end;
$$;

create or replace function public.set_my_marketing_email_preference(p_opt_in boolean)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_existing public.marketing_email_preferences%rowtype;
  v_row public.marketing_email_preferences%rowtype;
begin
  if v_uid is null then
    raise exception 'Du må være innlogget.' using errcode = '42501';
  end if;
  if p_opt_in is null then
    raise exception 'E-postvalget mangler.' using errcode = '22023';
  end if;

  select * into v_existing
  from public.marketing_email_preferences
  where user_id = v_uid;

  if found and v_existing.email_opt_in = p_opt_in then
    v_row := v_existing;
  else
    insert into public.marketing_email_preferences (
      user_id,
      email_opt_in,
      consent_at,
      consent_source,
      unsubscribed_at,
      updated_at
    ) values (
      v_uid,
      p_opt_in,
      case when p_opt_in then now() else null end,
      'app_settings',
      case when p_opt_in then null else now() end,
      now()
    )
    on conflict (user_id) do update
      set email_opt_in = excluded.email_opt_in,
          consent_at = case
            when excluded.email_opt_in then now()
            else public.marketing_email_preferences.consent_at
          end,
          consent_source = 'app_settings',
          unsubscribed_at = case when excluded.email_opt_in then null else now() end,
          updated_at = now()
    returning * into v_row;
  end if;

  return jsonb_build_object(
    'email_opt_in', v_row.email_opt_in,
    'consent_at', v_row.consent_at,
    'unsubscribed_at', v_row.unsubscribed_at
  );
end;
$$;

revoke all on function public.log_marketing_email_preference_event() from public, anon, authenticated;
revoke all on function public.get_my_marketing_email_preference() from public, anon;
revoke all on function public.set_my_marketing_email_preference(boolean) from public, anon;
grant execute on function public.get_my_marketing_email_preference() to authenticated;
grant execute on function public.set_my_marketing_email_preference(boolean) to authenticated;

comment on table public.marketing_email_preferences is
  'Gjeldende frivillig samtykke til nyheter/markedsføring per bruker. Token er kun servertilgjengelig.';
comment on table public.marketing_email_preference_events is
  'Sporbar historikk for samtykke og avmelding.';
comment on table public.systemadmin_email_campaigns is
  'Serverstyrt auditlogg for systemadminutsendinger uten klienttilgang.';
